### ISSUE TITLE
class for disabled nav button

### ISSUE THREAD

**Issue by n0th1nk** [ganlanyuan/tiny-slider#1]
Hi William,

Thanks for your slider, this is awesome! 

How I can add 'disabled' class for nav buttons? 
ie - in nonLoop mode, if slide is first - add class 'disabled' for PREV button. If slide is last - add class 'disabled' for NEXT button. 

Thanks again! :)

**Comment by ganlanyuan** [comment]
Hi, I will consider this and let you know soon.
Thank you for your interesting with tiny-slider.

**Comment by ganlanyuan** [comment]
Added, please check [this commit](https://github.com/ganlanyuan/tiny-slider/tree/5dc617b8f454c77e320c6d4e6013b49ab6f42c69) or [demo](http://creatiointl.org/gallery/william/tiny-slider/demo/).
