### ISSUE TITLE
Error in tiny-slider.js that breaks the demo

### ISSUE THREAD

**Issue by kieranpblack** [ganlanyuan/tiny-slider#102]
__Issue description__:  
Error in tiny-slider.js that breaks the demo

__Demo link/slider setting__:   
http://ganlanyuan.github.io/tiny-slider/tests/index.html

_Tiny-slider version_:   
Latest on demo site

_Browser name && version_:  
Safari 10.1.1

_OS name && version_:   
macOS 10.12.5 Sierra

**Comment by ganlanyuan** [comment]
Thanks @kieranpblack 
It's fixed.

**Comment by kieranpblack** [comment]
cheers!
