### ISSUE TITLE
Using items options with too few carousel items causes them to stretch

### ISSUE THREAD

**Issue by justindmyers** [ganlanyuan/tiny-slider#104]
I'm working on a site that has two carousel above and below each other. There is no guarantee that there will be enough items to fully fill the carousel and the current behavior of tiny-slider is to simply ignore the `items: X` option and fill the space.

Here's a working example:
https://codepen.io/justindmyers/pen/PObrRM

When a carousel with a specified number of items has less than that number, it would make sense to still use the correct width per item and not simply stretch them out.

**Comment by ganlanyuan** [comment]
Added a fix in this [commit](https://github.com/ganlanyuan/tiny-slider/commit/9968b15f2d11a5ae94d57fb45853d62f547b7589).

**Comment by ganlanyuan** [comment]
Should be fixed in [v2.3.3](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.3.3)
