### ISSUE TITLE
Loop: false and mouseDrag: true causes carousel to break

### ISSUE THREAD

**Issue by justindmyers** [ganlanyuan/tiny-slider#105]
__Issue description__:  

Setting both loop to false and mouseDrag to true causes the carousel to slide incorrectly. In the demo simply drag past the first or last item and the carousel will become stuck.

__Demo link/slider setting__:   

https://codepen.io/justindmyers/pen/EbNBJR

**Comment by jechav** [comment]
@justindmyers yea i agree, should prevent drag animation in the first and last slide.

**Comment by ganlanyuan** [comment]
Hey, fixed in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/943b82c14d5c9587a1f1c711d5f7ef53f7ada2ab)

**Comment by ganlanyuan** [comment]
Should be fixed in [v2.3.3](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.3.3)

**Comment by jechav** [comment]
yea was fixed, but sometimes the drag event stop to work. well very often. :(

**Comment by ganlanyuan** [comment]
@jechav , `touch/drag` will not work when the slider didn't finished the previous transition. Is this the case drag stop work for you?
