### ISSUE TITLE
swipe is not working on iOS & Android after any vertical scroll on the page 

### ISSUE THREAD

**Issue by nfoenki** [ganlanyuan/tiny-slider#108]
__Issue description__:  
swipe in slider
touch outside slider and scroll
try to swipe again on the slider
it does not swipe

__Demo link/slider setting__:   
any
_Tiny-slider version_:   latest 2.0
_Browser name && version_:  Safari mobile (latest), chrome mobile (latest)
_OS name && version_:   iOS, Android

**Comment by ganlanyuan** [comment]
Fixed in [v2.3.4](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.3.4)

**Comment by viktorlarsson** [comment]
I noticed this yesterday but I thought that was only in the emulator on Chrome.

**Comment by jvelumani** [comment]
Only in actual device (iPhone 6). In emulator looks fine for me.

**Comment by ganlanyuan** [comment]
@jvelumani Could you check out v2.7.0?

**Comment by doishub** [comment]
I am using v2.9.1. The bug also exists on the iPhone X and XS. After scrolling vertically, swiping left/right is no longer possible.

**Comment by doishub** [comment]
I am using v2.9.1. The bug also exists on the iPhone X and XS. After scrolling vertically, swiping left/right is no longer possible.
