### ISSUE TITLE
Slider breaks if number of slides is lower than `items` setting 

### ISSUE THREAD

**Issue by norin89** [ganlanyuan/tiny-slider#109]
__Issue description__:  
When number of slides is lower than `items` option the plugin breaks. 

__Screenshot__:   
That's what happens when I set `items` option to 5 and have only 4 slides in the code.
![screen shot 2017-11-18 at 23 41 43](https://user-images.githubusercontent.com/7902324/32985394-160ab712-ccba-11e7-886b-4046869a9371.png)

-----
_Tiny-slider version_:   2.3.4
_Browser name && version_:  Google Chrome 62.0.3202.94
_OS name && version_:   macOS 10.12.6

**Comment by ganlanyuan** [comment]
Thanks @norin89 ,will check it soon
Related to #104

**Comment by ganlanyuan** [comment]
May I know your settings?
I can't reproduce this issue.

**Comment by norin89** [comment]
Sure:
```js
  var slider = tns({
    container: '.slider',
    items: 9,
    loop: false,
  });
```

it seems that `loop: false;` is the key. Other way the slider doesn't break.

**Comment by ganlanyuan** [comment]
Could you check [this commit](https://github.com/ganlanyuan/tiny-slider/commit/2bf9183aba16324725b7e35616ee40d3db352a24)?
Looks fine for me.

**Comment by norin89** [comment]
@ganlanyuan it seems to work well for my issue.

But... For some reason when I set `items: 99` for `base` in `scripts.js` (w/o `loop: false` option) I see the same error and the slider breaks.

**Comment by ganlanyuan** [comment]
Okay, will check this again later.
Thanks for your feedback

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ganlanyuan** [comment]
Hey,
It works fine to me after I changed the `items` to 99 or any greater numbers.
I made a demo so you could check it: https://codepen.io/ganlanyuan/pen/MOrZxd

**Comment by norin89** [comment]
Sorry, it break with huge `items` amount and `loop: true` - https://codepen.io/anon/pen/yPprPR

**Comment by ganlanyuan** [comment]
Okay,
[This commit](https://github.com/ganlanyuan/tiny-slider/commit/c47b6eb30e43770cfd8e0f8b9f03c15ebfc64c5d) should fix it.
Demo: https://codepen.io/ganlanyuan/pen/bYaymP

**Comment by ganlanyuan** [comment]
Published a [new release](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.3.5) for this.
