### ISSUE TITLE
Feature Request: rewind option

### ISSUE THREAD

**Issue by faboulaws** [ganlanyuan/tiny-slider#11]
when rewind is enabled, the next button is not disabled when the last slide is reached. Clicking it would jump back to the first slide.

[https://github.com/ganlanyuan/tiny-slider/pull/10](see pull request)

**Comment by ganlanyuan** [comment]
Hey, there's a `loop` option which has similar function.
When `loop` is on, the slider will never stop when you click the navigation buttons.

**Comment by faboulaws** [comment]
The option i added is not like the loop. Its the opposite. The loop is circular. The rewind actually goes back to the first slide .  pressing the next button with loop = true would move foward to the first slide. But with rewind clicking next would go backward to the first slide.

**Comment by ganlanyuan** [comment]
I see, result is the same but different direction.
So should it directly jump to the last item when the prev button is clicked while the slider is on the first item?

**Comment by faboulaws** [comment]
No. The rewind is only when the next but is clicked when the last item is visible. The prev button behaves as normal.

Example slider : http://zkreations.github.io/SheetSlider/

**Comment by ganlanyuan** [comment]
Merged, thanks!
