### ISSUE TITLE
No option to disable slider on certain breakpoints

### ISSUE THREAD

**Issue by norin89** [ganlanyuan/tiny-slider#110]
__It's feature request, not a bug__:  
It would be nice if we could disable the carousel on certain breakpoints w/o writing custom event listeners to check breakpoint and then `slider.destroy()` or re-init. 

*The feature is available for example in [Slick Carousel](http://kenwheeler.github.io/slick/) - by passing `unslick` as value of `settings` option for given breakpoint.*

In `tiny-slider` it could look similar to this:
```
var slider = tns({
    container: '#carousel',
    items: 1,
    responsive: {
        400: {
            items: 2,
        },
        800: false, // or 'unslide' or anything
    },
  });
```

-----
_Tiny-slider version_:   -
_Browser name && version_:  -
_OS name && version_:   -

**Comment by ganlanyuan** [comment]
Hey,
There's an option for that: "disable".
You could check https://github.com/ganlanyuan/tiny-slider/blob/master/README.md#options

Sent from ProtonMail mobile

-------- Original Message --------
