### ISSUE TITLE
Strange effect when swiping the last slide on mobile

### ISSUE THREAD

**Issue by mqnrk** [ganlanyuan/tiny-slider#112]
__Issue description__:
Strange effect when swiping the last slide on mobile.
This happens only if we use fixedWidth and loop is disabled.

__Demo link/slider setting__: https://jsfiddle.net/n1a5kwcu/4/

_Tiny-slider version_:   2.3.5
_Browser name && version_:  Safari
_OS name && version_:   iOS 10.3.2

**Comment by ganlanyuan** [comment]
Thanks @mqnrk , this should be fixed in [v2.3.6](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.3.6)

**Comment by mqnrk** [comment]
It is now working as expected 🙂  Thanks @ganlanyuan !
