### ISSUE TITLE
should hide the "prev" and "next" at appropriate times when loop is false

### ISSUE THREAD

**Issue by heaversm** [ganlanyuan/tiny-slider#114]
__Issue description__:  
If loop is false, the previous button should be hidden initially, and the next should be hidden when you reach the end.

__Demo link/slider setting__:   

```
var sliderConfig = {
            container: '.js-slider',
            items: 2,
            responsive: {},
            slideBy: 'page', //or integer for number of slides
            autoplay: false,
            lazyload: true,
            nav: false,
            loop: false,
        }
```

_Tiny-slider version_:   2.3.7
_Browser name && version_: chrome  
_OS name && version_:   osx

**Comment by heaversm** [comment]
just saw it adds "disabled" to the button. Can style off that. Sorry!

**Comment by m2k6artworks** [comment]
Maybe this code can help someone who still don't know how to solve this problem yet.

.next[aria-disabled=true],
.prev[aria-disabled=true] {
   display: none;
}

.next[aria-disabled=false],
.prev[aria-disabled=false] {
   display: block;
}
