### ISSUE TITLE
JS error when calling destroy() on slider in mode: 'gallery'

### ISSUE THREAD

**Issue by asquet** [ganlanyuan/tiny-slider#115]
__Issue description__:  

Calling `destroy()` on slider with `mode: 'gallery'` causes js error.
It seems, that `destroy` expects more cloned elements than are actually created.
[Here](https://github.com/ganlanyuan/tiny-slider/blob/master/src/tiny-slider.module.js#L604
) we get `cloneCount` elements created (since `carousel` is false). 
[Here](https://github.com/ganlanyuan/tiny-slider/blob/master/src/tiny-slider.module.js#L2195
) we try to destroy `cloneCount * 2` elements, ignoring `carousel`

__Demo link/slider setting__:   

https://jsfiddle.net/e5fpg3ej/

_Tiny-slider version_:   2.3.7
_Browser name && version_:  Chrome 62
_OS name && version_:

**Comment by ganlanyuan** [comment]
Thanks @asquet , just added a [fix](https://github.com/ganlanyuan/tiny-slider/commit/1bd241a9e2a4d3513a654961cb2cc3a7bcd83229) for this.

**Comment by ganlanyuan** [comment]
The fix added in v2.3.8

**Comment by asquet** [comment]
Thanks!

**Comment by mohanathas** [comment]
@ganlanyuan I still get an error when trying to destroy the slider when it is on mode 'gallery'. Would you be so kind and check that again?
