### ISSUE TITLE
Autoplay timer doesn't reset or pause when user clicks to previous slide on slider nav

### ISSUE THREAD

**Issue by joshuarule** [ganlanyuan/tiny-slider#116]
__Issue description__:  
Autoplay timer doesn't reset when user clicks navigation backwards. This leads to the possibly quickly changing to the next slide right after a user clicks to navigate to a previous slide. For example below if the slider is on the 2nd slide and after 4 seconds of being on the 2nd slide the user clicks on the navigation to take them to the 1st slide. The carousel will automatically move forward to the second slide after 1 second.

__Demo link/slider setting__:   

```
var photoSlider = tns({
      container: '.photo_slider',
      items: 1,
      autoplay: true,
      autoplayTimeout: 5000,
      autoplayHoverPause: true,
      controls: false,
      mouseDrag: true,
      slideBy: "page"
    })
```

_Tiny-slider version_:   2.3.7
_Browser name && version_:  Chrome 62.0.3202.94
_OS name && version_:   OSX 10.13.1 (17B48)

**Comment by ganlanyuan** [comment]
The `autoplay` direction (forward/backward) is defined in the slider setting, it will not affected by user action. 
But it seems a good idea to pause the slider when user click the `controls`/`nav`, even though there is a `autoplayButton` for this purpose.

**Comment by joshuarule** [comment]
I saw the `autoplayButton` but I didn't want to add an additional start/stop button.

**Comment by ganlanyuan** [comment]
`autoplay` will be stopped when clicking `controls/nav` or pressing certain keys on them from v2.3.8

**Comment by Jack89ita** [comment]
Hi, would it be possible to reset the autoplay timer also when user drag to the next/previous slide? Maybe it would be a good idea to create a function that reset the timer every time a slide change, regardless of the gesture.
Thank you!

**Comment by ganlanyuan** [comment]
@silo-sietse There is just not enough info to know if the slider.goTo('next') is from end user or not.

**Comment by aferrerallu** [comment]
You can reset autoplay of the slider when using slider.goTo like this:
````
slider.pause();
slider.play();
slider.goTo(direction);
````

**Comment by KZTN** [comment]
> You can reset autoplay of the slider when using slider.goTo like this:
> 
> ```
> slider.pause();
> slider.play();
> slider.goTo(direction);
> ```

A simple solution to solve this boring behavior. Thanks!
