### ISSUE TITLE
When I switch to display:none & return to diplay:block slider not working

### ISSUE THREAD

**Issue by avernikoz** [ganlanyuan/tiny-slider#117]
__Issue description__:  Hello. On my page I have 3 tabs, and in summary I have 8 sliders. But rest assured, all sliders on my page not displayed at once. Not active sliders have class:
`display:none`
And I have a liitle bit code to switch on/off sliders. Here is a problem: when I turn off one of my slider, and then turn on, the slider didn't work!

After that I thought that I have some mistakes in my code (turn off/on my slider), and I have tried manually add `display:none` to one of the slider's container, and then clear this property in ccs — and I had the same result

Please, keep me informed, because you have a very good slider at all, expcept this issue.

__Demo link/slider setting__:   https://jsfiddle.net/so4p6svn/3/

_Tiny-slider version_:   2.3.7
_Browser name && version_:  Google Chrome Canary 64.0.3279.0
_OS name && version_:  MacOS OS X 10.9.4

**Comment by ganlanyuan** [comment]
The issue is: browser will not fire `onTransitionEnd` event on a hidden element which will prevent the slider from running again. 
I'm not sure how to "fix" this right now. But still one solution is to manually pause the `autoplay` before disable the slider and then restart it before enable it.
Demo: https://jsfiddle.net/h7qp2tw4/1/

**Comment by avernikoz** [comment]
Thank you. It works for me.

**Comment by ganlanyuan** [comment]
FYI, [v2.3.9](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.3.9) add a fix to this.
The `autoplay` slider will keep running even when its hidden. You still need to manually stop it if you want to.
