### ISSUE TITLE
Should the slider recognize padding on parent element?

### ISSUE THREAD

**Issue by lonepalmus** [ganlanyuan/tiny-slider#12]
if i place the tinyslider inside an element with padding, the slides are too wide.. 

(it should probably use innerwidth instead?)

**Comment by ganlanyuan** [comment]
Hey, 
[v0.4.2](https://github.com/ganlanyuan/tiny-slider/tree/v0.4.2) fixed this issue. Could you check it?
Please let me know if this works for you.

**Comment by lonepalmus** [comment]
works great, thanks :)
