### ISSUE TITLE
Lot of empty style tag in the head

### ISSUE THREAD

**Issue by jimblue** [ganlanyuan/tiny-slider#120]
http://ganlanyuan.github.io/tiny-slider/tests/index.html

<img width="1920" alt="screen shot 2017-12-03 at 03 58 21" src="https://user-images.githubusercontent.com/10623367/33521855-7ba96300-d7de-11e7-9470-425673fe4e17.png">

**Comment by ganlanyuan** [comment]
I don't know why browser can't display the inline styles inserted through JavaScript, but they're actually not empty. You can check this by removing some of them, you will notice the styles change.

**Comment by jimblue** [comment]
ok thanks for your rapid answer

**Comment by ganlanyuan** [comment]
No problem.
