### ISSUE TITLE
Importing via webpack tns can't resolve 'tiny-slider.module' in non relative path

### ISSUE THREAD

**Issue by jayden2** [ganlanyuan/tiny-slider#121]
__Issue description__:  
As stated in the docs importing is using a relative `path/to/src/tiny-slider.module`, however it is not possible to use a relative path when using docker or best practice to import with a relative path within `node_moules`, and should be possible to be able to resolve with `import { tns } from 'tiny-slider.module'`, this may be fixed by simply having `tiny-slider.module` within `dist/`
Thanks!

_Tiny-slider version_: 2.3.7/2.3.8
_Browser name && version_:  latest firefox and chrome
_OS name && version_:  Ubuntu 16.04

**Comment by jayden2** [comment]
didnt see https://github.com/ganlanyuan/tiny-slider/issues/20#issuecomment-346971369 until after posting, you may want to make this clearer in the docs! :smile:

**Comment by ganlanyuan** [comment]
Thanks @jayden2 , docs updated.
