### ISSUE TITLE
Carousel Pagination problem

### ISSUE THREAD

**Issue by Gietson** [ganlanyuan/tiny-slider#122]
__Issue description__:  
Problem with refresh circles pagination.
(ss 1)
First load page show 4 items and no carousel pagination it's ok. 
First breakpoint show 2 items and 2 circles it's ok. 
Next breakpoint show 1 item and 2 circles its not good because should show 4 circles.

(ss 2)
First load page show 1 item and 4 circles it's ok. 
First breakpoint show 2 items and 4 circles it's not good because should show 2 circles. 
Next breakpoint show 4 items and no carousel pagination it's ok.

config:
var slider = tns({
        "container": '.slider',
        "items": 1,
        "controls": false,
        "mouseDrag": true,
        "slideBy": "page",
        "nav": true,
        "rewind": false,
        "responsive": {
            "960": {
                "items": 4
            },
            "600": {
                "items": 2
            }
        }
       
    });

__Demo link/slider setting__:   
https://imgur.com/a/Qh8Cl

_Tiny-slider version_:   2.3.9
_Browser name && version_:  Firefox 57.0.2 / Chrome
_OS name && version_:   Windows 10

**Comment by ganlanyuan** [comment]
Thanks, should be fixed in v2.3.10

**Comment by ganlanyuan** [comment]
Note: you may not be able to fetch from npm because of an issue I couldn't publish there.
