### ISSUE TITLE
Disable Option in responsive breaks IE11 [Assignment to read-only properties is not allowed]

### ISSUE THREAD

**Issue by knynkwl** [ganlanyuan/tiny-slider#123]
__Issue description__:  I don't think this has to do with the disable option but I am getting the following error in IE11:

`Unhandled promise rejection TypeError: Assignment to read-only properties is not allowed in strict mode`

I found out where it's breaking. 

line 1271 `container.style = '';` since `.style` looks for a child property, switching to `container.removeAttribute('style');` fixes the issue.

__Demo link/slider setting__:   
```
this.sldr = tns({
        container: this.slider,
        items: this.items ? Number(this.items) : 1,
        slideBy: slide ? Number(slide) : 'page',
        mouseDrag: true,
        edgePadding: edge ? Number(edge) : 0,
        nav: nav ? nav : false,
        controlsText: [`<svg viewBox="0 0 24 40" width="24" height="40"><path d="M24 35.36L9.087 20 24 4.72 19.417 0 0 20l19.417 20z"/></svg>`, `<svg viewBox="0 0 24 40" width="24" height="40"><path d="M0 35.36L14.913 20 0 4.72 4.583 0 24 20 4.583 40z"/></svg>`],
        responsive: {
          0: { disable: 0 },
          640: { disable: 0 },
          900: { disable: 1 }
        },
        onInit: () => {
          this.smallSlider();
        }
      });
```

_Tiny-slider version_:   2.3.6 ES MODULE
_Browser name && version_:  IE11
_OS name && version_:  n/a

**Comment by knynkwl** [comment]
Here's my PR b2be8f66f5a047d985b1b41359a3a57f92a032cc

**Comment by ganlanyuan** [comment]
Hey, I couldn't reproduce the issue.
I tried with your setting in IE11 on Win7/8/10, but could get the error you described. Are you able to make a demo page?

**Comment by ganlanyuan** [comment]
Thanks @TuckerWhitehouse , `el.style = ''` was replaced with `el.style.cssText = ''` in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/6cdce84100cb7f2e3cdb3ce249d6ffe7f664392a), could you check if this works for you?

**Comment by ganlanyuan** [comment]
Added in v2.6.å
