### ISSUE TITLE
Is there a way to "peek" the next image

### ISSUE THREAD

**Issue by heaversm** [ganlanyuan/tiny-slider#124]
__Issue description__:  

Similar to some mobile characters, is there a way to display a certain number of images onscreen, but have the next offscreen image still a fraction visible on the right side of the screen?

![screen shot 2017-12-11 at 11 02 58 am](https://user-images.githubusercontent.com/520541/33848536-ebd40362-de62-11e7-9175-c6126b3dbccf.png)

__Demo link/slider setting__:   

```
var sliderConfig = {
            container: '.js-slider',
            items: 1,
            responsive: {},
            slideBy: 1, //or integer for number of slides
            autoplay: false,
            lazyload: true,
            nav: false,
            arrowKeys: true,
            loop: true
        }
        sliderConfig.responsive[GLOBAL_CONSTANTS.BREAKPOINTS.SMALL] = {
            items: 2
        }
        sliderConfig.responsive[GLOBAL_CONSTANTS.BREAKPOINTS.MEDIUM] = {
            items: 4
        }
```

_Tiny-slider version_:   Version: 2.3.7
_Browser name && version_:  Chrome Latest
_OS name && version_:   Mac High Sierra

**Comment by ganlanyuan** [comment]
Hey, you can use `edgePadding`.
```javascript
var sliderConfig = {
  edgePadding: 50, // 50px
  …
}
```
