### ISSUE TITLE
Add startIndex option

### ISSUE THREAD

**Issue by jgerbes** [ganlanyuan/tiny-slider#125]
It would be great if you could set the start index of the slider without an additional call to `goTo()`

Sidenote: calling `goTo()` in this scenario is not a good option because it will animate over to the index.

**Comment by ganlanyuan** [comment]
Hey @jgerbes ,
May I know the reason you want to start the slider from index other than 0?

**Comment by jgerbes** [comment]
Hey @ganlanyuan,
I’m using the slider in React, and each time it gets re-rendered it is destroyed and re-initialised. The slider needs to be at the same index after re-rendering as it was before being destroyed.

**Comment by makedonec88** [comment]
Same here, I have a slider with versions of a product. Active slide is a current version, but I also have future versions. So my current version might be at index 10 (from 15) and user should be able to go back to see prev versions and further - for future one.

**Comment by ganlanyuan** [comment]
Added in [v2.4.0](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.4.0).

**Comment by jgerbes** [comment]
@ganlanyuan Thanks for adding this option. I have just tested this and there seems to be an issue with the navigation buttons when re-rendering the slider. 

E.G:
1. Create slider with 2 pages and nav buttons
2. Destroy slider
3. Re-create slider with startIndex: 1
4. Back nav button is disabled

**Comment by ganlanyuan** [comment]
Hey @jgerbes ,
Could you make a demo?
I tried, but couldn't reproduce the issue you described.

**Comment by jgerbes** [comment]
Hey @ganlanyuan. Sorry for the late reply.

Here's a demo: [JSFiddle](https://jsfiddle.net/f14uc67L/).
Please note that in this demo `loop` is disabled and `startIndex` is set to 1.

Notice that the 'prev' button is disabled on init even though a previous item (index 0) exists.

**Comment by ganlanyuan** [comment]
Added a fix in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/5e7dd8f1280b7ba896c02d441dceb9e768a14573).

**Comment by jgerbes** [comment]
Thanks @ganlanyuan. That works great :)
