### ISSUE TITLE
Custom easing function

### ISSUE THREAD

**Issue by heaversm** [ganlanyuan/tiny-slider#128]
__Issue description__:  
Is there a way to pass a custom easing function? Or even just use linear easing? I'm being asked to create a constant, rolling slide show

__Demo link/slider setting__:   

```
const sliderConfig = {
            container: CLASSES.SLIDER,
            items: 1,
            responsive: {},
            slideBy: 'page', //or integer for number of slides
            autoplay: true,
            lazyload: true,
            nav: false,
            arrowKeys: true,
            loop: true,
            speed: 3000,
            autoplayTimeout: 1,
        };
```

_Tiny-slider version_:   
_Browser name && version_:  
_OS name && version_:

**Comment by ganlanyuan** [comment]
There is no *default* timing function, so you can just add it
```css
.tiny-slider {
  transition-timing-function: your-timing-function;
}
```
