### ISSUE TITLE
Knowing the position of a slide in the slider

### ISSUE THREAD

**Issue by faboulaws** [ganlanyuan/tiny-slider#13]
The slider when initialised duplicates slides to create a circular illusion when **loop=true**(I think). Because of this, there is no accurate way to know the index of the specific slide in the slider. Is there a way to know the real index of a specific slide? Or is there a possibility to add an index/position attribute?

**Comment by ganlanyuan** [comment]
Hey, 
May I know what you would like to do with the index?

**Comment by faboulaws** [comment]
Example usage

For UI event tracking when an item is clicked we would like to know the index that was clicked in the slider.
Obviously there are alternative options to track clicked index but it is nice to have a real index data from the slider itself.

**Comment by ganlanyuan** [comment]
Okay,
Which is better for you? Add a class to the current item or add a function
to get the index

**Comment by faboulaws** [comment]
A function seems better.

Thanks

**Comment by ganlanyuan** [comment]
Use method `getIndex` to get the real index from [v0.6.3](https://github.com/ganlanyuan/tiny-slider/tree/v0.6.3).   
```javascript
var slider = tinySlider(options);
slider.init();

// click listener
button.addEventlistener('click', function(){
    console.log(slider.getIndex()); // output index
});
```

**Comment by faboulaws** [comment]
Thanks so much
