### ISSUE TITLE
localStorage permission error log

### ISSUE THREAD

**Issue by danny7i** [ganlanyuan/tiny-slider#130]
__Issue description__:  
If the user agent has blocked website data in the settings, accessing localStorage in this line `var tnsStorage = localStorage;` will cause Chrome and Safari to throw errors in the log and halting the execution of the remaining code. 

It would be nice to wrap that assignment line side the try/catch block to test both the support and permission for localStorage. Something like this:

`
			var localStorageAccess;
                        var tnsStorage;

			try {
				localStorageAccess = !!window.localStorage
				if (localStorageAccess) {
                                        tnsStorage = window.localStorage;
					.......
				}
			} catch (err) {
				localStorageAccess = false;
                        }
`

_Tiny-slider version_:   2.3.5
_Browser name && version_:  Chrome, Safari (Mobile and Desktop)
_OS name && version_:  MacOS, Windows, Android, iOS

Thank you very much!

**Comment by ganlanyuan** [comment]
Hi,
This has been fixed from v2.3.8.

**Comment by danny7i** [comment]
Thanks!
