### ISSUE TITLE
[Bug] Navigation with page slider

### ISSUE THREAD

**Issue by katiasmet** [ganlanyuan/tiny-slider#131]
__Issue description__:  
I've got an slider with 6 items. The slider slides with 4 items at a time (so sliding by page).
I want custom navigation, so I used a navContainer with 6 items just like the original navigation. But it shows 6 dots instead of 2 (the original shows 2 dots). The original works with a hidden="true" on some tags, but when I use this on my custom dots it doesn't work. 

__Demo link/slider setting__:   
```
<div class="c-pagination__dots c-pagination--products__dots u-display--inline o-list-bare o-list-inline">
    <button data-nav="0" tabindex="0" aria-selected="true" aria-controls="tns1-item0" type="button" class="c-pagination__dot link--none u-display--block tns-nav-active"></button>
    <button data-nav="1" tabindex="-1" aria-selected="false" aria-controls="tns1-item1" type="button" class="c-pagination__dot link--none u-display--block" hidden=true></button>
    <button data-nav="2" tabindex="-1" aria-selected="false" aria-controls="tns1-item2" type="button" class="c-pagination__dot link--none u-display--block" hidden=true></button>
    <button data-nav="3" tabindex="-1" aria-selected="false" aria-controls="tns1-item3" type="button" class="c-pagination__dot link--none u-display--block" hidden=true></button>
    <button data-nav="4" tabindex="-1" aria-selected="false" aria-controls="tns1-item4" type="button" class="c-pagination__dot link--none u-display--block"></button>
    <button data-nav="5" tabindex="-1" aria-selected="false" aria-controls="tns1-item5" type="button" class="c-pagination__dot link--none u-display--block" hidden=true></button>
    <button data-nav="6" tabindex="-1" aria-selected="false" aria-controls="tns1-item6" type="button" class="c-pagination__dot link--none u-display--block" hidden=true></button>
</div>
```

```
var slider = tns({
        container: '.c-slider--products',
        items: 4,
        slideBy: 'page',
        autoplay: true,
        nav: true,
        navContainer: '.c-pagination--products__dots',
        controls: false
      });
```
_Tiny-slider version_:   Chrome  63.0.3239.84
_Browser name && version_:  Chrome latest version
_OS name && version_:   OSX Sierra 10.12.6

**Comment by ganlanyuan** [comment]
Hey @katiasmet 
I can't hide customized dots in case they're thumbnails. So the behaviors of customized dots are different with native ones.

**Comment by katiasmet** [comment]
Ok thanks for the fast response :). 

For others: I 'resolved' this by moving the original dots to a custom container. 

```

**Comment by ganlanyuan** [comment]
I will consider to add an option (something like `navAsThumbnails`) to make it easier.

**Comment by ganlanyuan** [comment]
Added `navAsThumbnails` option in [v2.5.0](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.5.0).

For your case, you don't need to do anything since the default behavior of customized `nav` will be same as native one.
