### ISSUE TITLE
Cannot read property 'tC' of null (when localStorage is null in chrome mobile android)

### ISSUE THREAD

**Issue by danny7i** [ganlanyuan/tiny-slider#134]
__Issue description__:  

On certain browsers with certain settings, the window.localStorage will be null. This will cause null error to be thrown starting from this line

`CALC = checkStorageValue(tnsStorage['tC']) || setLocalStorage('tC', calc(), localStorageAccess),`

_Tiny-slider version_:   2.5.0
_Browser name && version_:  Chrome Mobile 63.0.3239
_OS name && version_:   Android 7.0

Thanks!

**Comment by ganlanyuan** [comment]
Hey, 
Could you provide more detailed information, such as devices, browser setting and slider setting?
I did a quick test on some Andriod 7.0 devices with cookies blocked, couldn't find the issue you described.

**Comment by danny7i** [comment]
Hi, we have multiple users having this issue. This is indeed a rare occurrences but the common pattern is they all use Chrome Mobile. Here are some sample logs I've got 

`
browserName
Chrome Mobile
browserVersion
63.0.3239
locale
en-GB
osName
Android 7.0
time
2018-01-17T09:05:07.790Z
userAgent
Mozilla/5.0 (Linux; Android 7.0; SM-G920F Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/63.0.3239.111 Mobile Safari/537.36

browserName
Chrome Mobile
browserVersion
63.0.3239
locale
en-GB
osName
Android 7.0
time
2018-01-29T16:28:32.971Z
userAgent
Mozilla/5.0 (Linux; Android 7.0; SM-G925F Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/63.0.3239.111 Mobile Safari/537.36

browserName
Chrome Mobile
browserVersion
64.0.3282
locale
en-GB
osName
Android 7.0
time
2018-01-28T18:40:47.441Z
userAgent
Mozilla/5.0 (Linux; Android 7.0; SM-G930F Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/64.0.3282.123 Mobile Safari/537.36

browserName
Chrome Mobile
browserVersion
63.0.3239
locale
en-GB
osName
Android 7.0
time
2018-01-27T23:44:42.181Z
userAgent
Mozilla/5.0 (Linux; Android 7.0; SM-G955F Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/63.0.3239.111 Mobile Safari/537.36

browserName
Chrome Mobile
browserVersion
63.0.3239
locale
en-GB
osName
Android 7.1
time
2018-01-27T08:23:02.544Z
userAgent
Mozilla/5.0 (Linux; Android 7.1.1; F5321 Build/34.3.A.0.238; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/63.0.3239.111 Mobile Safari/537.36
`

I also could not reproduce it on Chrome Mobile. I'd venture a guess it happens on webview in a native app, where localStorage access is disabled. See https://stackoverflow.com/questions/8701015/html-localstorage-is-null-on-android-when-using-webview

Either way I think it would be better to test for null as well. Thank you.

**Comment by ganlanyuan** [comment]
Should be fixed in v2.5.2

**Comment by danny7i** [comment]
Super! Appreciated!
