### ISSUE TITLE
Outro animation class not being added

### ISSUE THREAD

**Issue by nr1q** [ganlanyuan/tiny-slider#135]
__Issue description__:  As said in title, the outro animation class is not being added, last release I had it working is 2.3.7

__Demo link/slider setting__:  To demonstrate the issue: https://jsfiddle.net/6jxfhxcp/1/

_Tiny-slider version_:  2.5.0
_Browser name && version_:  Google Chrome 63.0.3239.132
_OS name && version_:  OS X 10.11.6

**Comment by nr1q** [comment]
Thanks a lot! It is working now, also thanks for such a nice slider library.

**Comment by ganlanyuan** [comment]
Added in [v2.5.1](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.5.1)
