### ISSUE TITLE
Blank space at end of slider 

### ISSUE THREAD

**Issue by maddyBoy** [ganlanyuan/tiny-slider#136]
__Issue description__:   I created a vertical slider, there are few problem that i am not able to solve
1) Blank space at end of slider
2) If content varies, browser scroll keeps moving up and down

content : 
```
<div id="vertical_slider_homes">

                            <div class="item">
                             <h3>lorem ipsum <span>20 hours ago</span></h3>
                             <div class="ratings">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                             </div>
                             <h3>Elated with team</h3>
                             <p>Lorem iolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conpsum dolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, conolor sit amet, consectetur adipisicing elit.</p>
                       </div>
                      <div class="item">
                           <h3>lorem ipsum <span>20 hours ago</span></h3>
                             <div class="ratings">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                             </div>
                             <h3>Elated with team</h3>
                             <p>Lorem iolor sit amet </p>
                       </div> 
                       <div class="item">
                           <h3>lorem ipsum <span>20 hours ago</span></h3>
                             <div class="ratings">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                             </div>
                             <h3>Elated with team</h3>
                             <p>Lorem iolor sit amet Lorem iolor sit amet </p>
                       </div>
</div>
```

__Demo link/slider setting__:   
 ```
var slider = tns({
              container: '#vertical_slider_homes',
              items: 3,
              axis:'vertical',
              slideBy: 'page',
              autoplay: true,
              autoplayButtonOutput: false,
              speed: 400
              // rewind: true
             // autoHeight:true

           });

```
_Tiny-slider version_:   any
_Browser name && version_:  any
_OS name && version_:   any

**Comment by ganlanyuan** [comment]
Hey @maddyBoy, 
I made a demo based on your options: https://codepen.io/ganlanyuan/pen/goZPaB. I changed `items` to 2.
I couldn't see the issues.

**Comment by maddyBoy** [comment]
Here is the  demo website where i am using it 

http://magento2.hestalabs.com/ 

On vertical sidebar ( Magento 2 Platform)  i am having the issue.
I got white space once slider reaches the last div.item

**Comment by maddyBoy** [comment]
http://magento2.hestalabs.com/

I m using this slider at above link ( Magento 2 Platform).

when we reach the last div.item ( which populated through loop) we got empty space.

**Comment by ganlanyuan** [comment]
> 1. Blank space at end of slider

I still couldn't find this issue.
> 2. If content varies, browser scroll keeps moving up and down

This is the slider is trying to match the overall visible slides' height, so slider height is keep changing as you clicking the prev/next button.

**Comment by maddyBoy** [comment]
I tried to solve the issue at my end but not succeeded, I made a gif of the issue .

When you keep clicking the up arrow and we reach to last slide it shows blank area.

And the items:3 which I am currently using still shows more number of items specially on desktop.

Is there any issue if designer gave some paddings and line height to inner content.
![20180120_061845](https://user-images.githubusercontent.com/26545067/35177916-0811a474-fdaa-11e7-936e-53588f5cafb4.gif)

**Comment by ganlanyuan** [comment]
May I know which browser/version are you testing on?
I still couldn't see the issue on my end.

**Comment by ganlanyuan** [comment]
Sorry but I still couldn't reproduce the issue outside the website.

I noticed that the same variable name was used in many sliders,
```javascript
var slider = tns({
…
```
Could you change them to different names or even just call the function directly,
```javascript
tns({
  …
})
```
I'm not sure if this will help or not.
