### ISSUE TITLE
Slider pause and play autoplay functions

### ISSUE THREAD

**Issue by jayden2** [ganlanyuan/tiny-slider#137]
__Issue description__:  
If I'm not mistaken there's currently no function to allow external controls to pause or play a slider

Example being:
```
// go to slides by number or keywords
const slider = tns(...);

document.querySelector('.pause-button').onclick = () => {
  slider.pause();
};

document.querySelector('.play-button').onclick = () => {
  slider.play();
};
```
__Demo link/slider setting__:   

_Tiny-slider version_:   
_Browser name && version_:  
_OS name && version_:

**Comment by ganlanyuan** [comment]
For "go to certain slide", check [goTo](https://github.com/ganlanyuan/tiny-slider#goto) function.
For controls to pause/play a slider, you could use [customized `autoplayButton`](https://github.com/ganlanyuan/tiny-slider#options). You may want to check out [this demo](http://ganlanyuan.github.io/tiny-slider/tests/index.html#customize_wrapper) as well.

**Comment by jayden2** [comment]
Yeah, I guess its possible to programaitcally call the button to play/pause.

The reason for this is because we have videos in the slider, so when play is pressed on the play thumbnail we need to pause the autoplay.

Thanks for your help! :)

**Comment by jayden2** [comment]
My solution has been to hide a custom autoplay button and pause/unpause via an onclick in JS, which feels bit dumb.

It would be really handy to have the startAutoplay and stopAutoplay functions emitted as an event the same way goTo is:
https://github.com/ganlanyuan/tiny-slider/blob/a72ff9043cd41fda218ec04af77f2e1a60ddb101/src/tiny-slider.module.js#L2191

**Comment by ganlanyuan** [comment]
Add `play`, `pause` function in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/67b7688d6a6592466eda726ae1a4fb3cba207cf1), they will be delivered in next release.

**Comment by jayden2** [comment]
Thank you, much appreciated!

**Comment by ganlanyuan** [comment]
Added in [v2.5.1](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.5.1)

**Comment by jayden2** [comment]
works as intended, thank you again!
