### ISSUE TITLE
Autoplay cuts off animation

### ISSUE THREAD

**Issue by strohrdanz** [ganlanyuan/tiny-slider#139]
__Issue description__:  
When using autoplay: true, the fade animation is cut off in gallery mode. I've also tried using custom animations, and the same thing happens - the animate out animation doesn't play through.

__Demo link/slider setting__:   
  container: sliderContainer,
  items: 1,
  autoplay: true,
  autoplayTimeout: 5000,
  speed: 1000,
  mode: 'gallery',
  animateIn: "fadeIn",
  animateOut: "fadeOut",

**Comment by ganlanyuan** [comment]
Should be same as #135 ,
The fix will be added in next release

**Comment by ganlanyuan** [comment]
Added in [v2.5.1](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.5.1)
