### ISSUE TITLE
Carousel breaks when total number of slides is less than the current responsive breakpoint 'items:' setting

### ISSUE THREAD

**Issue by kyleaffolder** [ganlanyuan/tiny-slider#140]
__Issue description__:  
Seems that when the `responsive: true` option is set and responsive breakpoint options are defined in the slider, when the total number of slides is lower than the largest defined breakpoint `items: #`, the carousel breaks and applies a `.tns-transparent` class to the slides.

The only thing I'm seeing is that if several more slides are added, this doesn't break. For example, in the Fiddle, I have a total of 7 slides. When you view the Fiddle at a browser viewport of, say, 1900px, the carousel is broken. It appears the slider works up to a viewport of around 1810px. However, if I add one more slide, it then [works](https://jsfiddle.net/79m9jLmf/) _(minus the other issue you'll notice I have logged [here](https://github.com/ganlanyuan/tiny-slider/issues/88#issuecomment-359554437))_.

__Demo link/slider setting__:   
https://jsfiddle.net/7zq0s8xm/

_Tiny-slider version_:   2.5.0
_Browser name && version_:  63.0.3239.132 (Official Build) (64-bit)
_OS name && version_:   macOS High Sierra 10.13.2

**Comment by ganlanyuan** [comment]
Thanks @kyleaffolder ,
Just commit a [fix](https://github.com/ganlanyuan/tiny-slider/commit/34338cc3560d7f78a9fd6fcd1ed50ead691d1192).
Please let me know if this fix your issue.

**Comment by ganlanyuan** [comment]
Added in [v2.5.1](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.5.1)

**Comment by kyleaffolder** [comment]
@ganlanyuan Seems to still be an issue. I've created an updated [codepen](https://jsfiddle.net/uy76ho0j/1/). Seems that when you're at a viewport width of 1850px or wider, the `.tns-transparent` class is still getting applied to slide elements.

**Comment by ganlanyuan** [comment]
Could you try [this commit](https://github.com/ganlanyuan/tiny-slider/commit/f6528112461d6b5d34e0ad58b68dcddb99d16c76)?

**Comment by ganlanyuan** [comment]
Should be fixed in v2.5.2

**Comment by kyleaffolder** [comment]
@ganlanyuan Thank you so much for looking into this. That commit does fix the issue documented. Really appreciate it!! 🥇

**Comment by OvalMedia** [comment]
I am using the minified version from a fresh download. I have the same issue. Item count less or equal to the number given in the responsive configuration breaks the slider.
