### ISSUE TITLE
rewind / loop only works forwards

### ISSUE THREAD

**Issue by mAAdhaTTah** [ganlanyuan/tiny-slider#141]
When setting rewind or loop to true, and clicking "previous", I would expect the slider to loop / rewind to the last slide in the slider. Instead, nothing happens. Thus, I can only loop or rewind when clicking forward in the slider but not backwards.

**Comment by ganlanyuan** [comment]
Hi, you can go "previous" with `loop`. 
For `rewind`, it will go to the first slide after reach the last. Beside that, `rewind` is same as `non-loop`.

**Comment by mAAdhaTTah** [comment]
My apologies, I was testing both and thought they had the same behavior but wasn't sure. You definitely can't click previous on the first slide with `rewind` and end up on the last slide.

**Comment by ganlanyuan** [comment]
That's true for "rewind", you can not click the previous button at the first slide.
You can use "loop" instead.

**Comment by mAAdhaTTah** [comment]
I'm going to go w/ "loop" for now, but is that expected / intended for "rewind"? Seems surprising to me.

**Comment by ganlanyuan** [comment]
Hum, seems you're right. I will trying to fix it recently.
Thanks for your feedback

**Comment by ganlanyuan** [comment]
Should be fixed in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/060f1be94c28a2d79573e8291d597944d1937d8b).

**Comment by ganlanyuan** [comment]
Fixed in v2.5.2
