### ISSUE TITLE
[disabled] for customized controls (arrows) is not working.

### ISSUE THREAD

**Issue by keem1201** [ganlanyuan/tiny-slider#142]
Here are my codes:

For HTML code:

`
<div class="tiny-slider-wrapper">
	
	<div class="tiny-slider-customized-controls tiny-slider-inner">
	
		<div class="tiny-slider-item">
			<div class="bg-primary flex-vertical-align" style="height: 150px; text-align: center; color: #FFF; font-size: 20px;">01</div>
		</div>
		
		<div class="tiny-slider-item">
			<div class="bg-danger flex-vertical-align" style="height: 150px; text-align: center; color: #FFF; font-size: 20px;">02</div>
		</div>
		
		<div class="tiny-slider-item">
			<div class="bg-warning flex-vertical-align" style="height: 150px; text-align: center; color: #FFF; font-size: 20px;">03</div>
		</div>
		
		<div class="tiny-slider-item">
			<div class="bg-success flex-vertical-align" style="height: 150px; text-align: center; color: #FFF; font-size: 20px;">04</div>
		</div>
		
		<div class="tiny-slider-item">
			<div class="bg-info flex-vertical-align" style="height: 150px; text-align: center; color: #FFF; font-size: 20px;">05</div>
		</div>
		
		<div class="tiny-slider-item">
			<div class="bg-primary flex-vertical-align" style="height: 150px; text-align: center; color: #FFF; font-size: 20px;">06</div>
		</div>
		
		<div class="tiny-slider-item">
			<div class="bg-danger flex-vertical-align" style="height: 150px; text-align: center; color: #FFF; font-size: 20px;">07</div>
		</div>
		
		<div class="tiny-slider-item">
			<div class="bg-warning flex-vertical-align" style="height: 150px; text-align: center; color: #FFF; font-size: 20px;">08</div>
		</div>
		
		<div class="tiny-slider-item">
			<div class="bg-success flex-vertical-align" style="height: 150px; text-align: center; color: #FFF; font-size: 20px;">09</div>
		</div>
		
		<div class="tiny-slider-item">
			<div class="bg-info flex-vertical-align" style="height: 150px; text-align: center; color: #FFF; font-size: 20px;">10</div>
		</div>
		
		<div class="tiny-slider-item">
			<div class="bg-primary flex-vertical-align" style="height: 150px; text-align: center; color: #FFF; font-size: 20px;">11</div>
		</div>
		
		<div class="tiny-slider-item">
			<div class="bg-danger flex-vertical-align" style="height: 150px; text-align: center; color: #FFF; font-size: 20px;">12</div>
		</div>
		
		<div class="tiny-slider-item">
			<div class="bg-warning flex-vertical-align" style="height: 150px; text-align: center; color: #FFF; font-size: 20px;">13</div>
		</div>
		
		<div class="tiny-slider-item">
			<div class="bg-success flex-vertical-align" style="height: 150px; text-align: center; color: #FFF; font-size: 20px;">14</div>
		</div>
		
		<div class="tiny-slider-item">
			<div class="bg-info flex-vertical-align" style="height: 150px; text-align: center; color: #FFF; font-size: 20px;">15</div>
		</div>
		
	</div>

	<ul class="controls customized-arrows">
		<li class="prev">
			<i class="fa fa-angle-left"></i>
		</li>
		<li class="next">
			<i class="fa fa-angle-right"></i>
		</li>
	</ul>

</div>
`
For the Js code:

```
var slider = tns({
	container: '.tiny-slider-customized-controls',
	items: 4,
	slideBy: 'page',
	autoplay: false,
	controlsContainer: ".customized-arrows",
	loop: false,
});
```

And for the css code: 

```
ul.controls.customized-arrows { background-color: #EEE; text-align: center; margin-top: 15px; }
ul.controls.customized-arrows li { display: inline-block; }
.controls.customized-arrows [aria-controls] { font-size: 30px; margin: 0 5px; line-height: 1; -moz-transition: color 0.3s ease-out; -webkit-transition: color 0.3s ease-out; transition: color 0.3s ease-out; }
.controls.customized-arrows [aria-controls]:hover { cursor: pointer; color: red; }
.controls.customized-arrows [disabled]{color: inherit; opacity: 0.4; cursor:not-allowed!important}
```

The [disabled] for customized controls (arrows) is not working. Please help.

Thanks in advance.

**Comment by ganlanyuan** [comment]
Hey, since the customized controls are `<li>`s, we can not use `[disabled]` here, instead, `[aria-disabled]` will be added.
