### ISSUE TITLE
ItemsPerDot option?

### ISSUE THREAD

**Issue by antoniojl** [ganlanyuan/tiny-slider#143]
__Feature request__:  When slideBy and/or items are set, it would be good to have an option to only show the same number of dots as there are 'pages' of items to slide by, as opposed to one dot per item. Is this possible?

**Comment by ganlanyuan** [comment]
There is an option `navAsThumbnails` did what you want.

**Comment by ganlanyuan** [comment]
Ah, that's for customized dots,
I will update it to make it works for native dots as well

**Comment by ganlanyuan** [comment]
Updated, will be delivered in next release.

**Comment by antoniojl** [comment]
Amazing, thank you!

**Comment by ganlanyuan** [comment]
Added in v2.5.2
