### ISSUE TITLE
Destroy in conjunction with window resizing throws error

### ISSUE THREAD

**Issue by dcress** [ganlanyuan/tiny-slider#144]
__Issue description__:  When using the `destroy` method in conjunction with resizing the browser window (as in disabling the slider when the browser reaches mobile/tablet size) tiny-slider throws the error: 

`Uncaught TypeError: Cannot read property 'clientWidth' of null`

__Demo link/slider setting__: 
```
this.songsCarousel = tns({
    container: '.js-songs-carousel',
    items: 8,
    slideBy: 'page',
    autoplay: false,
    loop: false,
    lazyload: true,
    gutter: 24,
    nav: false
});
```

<img width="513" alt="screen shot 2018-02-02 at 11 19 58 am" src="https://user-images.githubusercontent.com/2212763/35746047-08a5715c-080b-11e8-8973-f3b4927d98fa.png">

_Tiny-slider version_:   2.5.1
_Browser name && version_:  Chrome (and all other browser tested)
_OS name && version_:   iOS

**Comment by dcress** [comment]
Submitted a PR to fix this: https://github.com/ganlanyuan/tiny-slider/pull/145

**Comment by ganlanyuan** [comment]
Hey @dcress ,
I think this is a critical case: resizing the browser while destroying the slider. Technically this is an issue, but end users usually won't do this.
Thanks for your feedback

**Comment by dcress** [comment]
Thanks for your reply @ganlanyuan! 

I agree that it's an edge-case, but I'd say that it's not _that_ uncommon (I do this on almost all carousel sliders for mobile, since natural scroll is a better UX there). 

Also, the fix wouldn't cause an issue for non edge case users, it would only make this edge-case work. It never hurts to check that something is valid before trying to grab a property from it.

**Comment by ganlanyuan** [comment]
I see,
Then you can use `disable` option on mobile instead.

**Comment by dcress** [comment]
@ganlanyuan The issue with using `disable` is that it would require me to launch the slider on mobile, always. For performance reasons, i don't want to do this, also -- since disable leaves the markup and preserves the padding/gutter of the slider-items, that forces me to rely on the slider to properly position my items, even when on mobile. So disable doesn't get me there. 

I would also need to override the style in your css file to set `overflow: hidden` to `overflow: scroll` to enable the content to scroll as it should on mobile. That means that i'd be referencing your JS generated elements/classes within my stylesheet, which isn't best-practice. 

In my humble opinion, destroy should ideally work in any situation, with the ability to re-init the function at any time and without breaking other JS on the page. Is there a reason you're opposed to the conditionals that i've added in my PR? Just trying to understand! 

Thanks so much for your time and plugin!

**Comment by ganlanyuan** [comment]
I see.

Actually after destroy the slider, you can re-init it again with no issue.
The problem here is when you resize the window, the `destroy` process didn't finish, a resize event still bound to `window`, so maybe a better solution is remove the resize event earlier.

**Comment by dcress** [comment]
@ganlanyuan, im running the destroy process inside of the resize event -- that's how I'm determining if we should or shouldn't destroy the carousel. I feel that this is a pretty common use case for this. 

```
PageResources.prototype._manageCarouselsOnResize = function() {
	var self = this;

	window.addEventListener("resize", function () {
		if (!self.songsCarousel) {
			self._initSongsCarousel();
			self._initPatchesCarousel();
		} else if (self._isMobileSize()) {
			self.songsCarousel.destroy();
			self.patchesCarousel.destroy();
			self.songsCarousel = false;
			self.patchesCarousel = false;
		}
	});
}
```

**Comment by ganlanyuan** [comment]
Hey, could you try with [this commit](https://github.com/ganlanyuan/tiny-slider/commit/f6c01bf85d70d4393c79866f8729308eff1a1f6d)?

This doesn't really fix the problem:
```javascript
if (outerWrapper) vpOuter = outerWrapper.clientWidth;
```
Here if the `outerWrapper` is null, the `vpOuter` just remain unchanged, all the steps afterward will be wrong.

**Comment by dcress** [comment]
@ganlanyuan I will! I'll let you know asap if that works. Thanks!

**Comment by dcress** [comment]
@ganlanyuan That's still throwing an error for me.

**Comment by dcress** [comment]
Also, re: https://github.com/ganlanyuan/tiny-slider/issues/144#issuecomment-363128359 -- That conditional wasn't intended to be the end-all fix, but just a temp measure to fix that in the production code. I think that restructuring the destroy method would fix the root cause of the issue.

**Comment by ganlanyuan** [comment]
[This commit](https://github.com/ganlanyuan/tiny-slider/commit/e04d0e0c78821ca0fc2d4462cf176626e510d755) will probably fix the issue while your code may require some updates as well:
```javascript
PageResources.prototype._manageCarouselsOnResize = function() {
  var self = this;

  window.addEventListener("resize", function () {
    if (!self._isMobileSize() && !self.songsCarousel) {
      self._initSongsCarousel();
      self._initPatchesCarousel();
    } else if (self._isMobileSize() && self.songsCarousel) {
      self.songsCarousel.destroy();
      self.patchesCarousel.destroy();
      self.songsCarousel = false;
      self.patchesCarousel = false;
    }
  });
}
```

Please let me know if this works for you.
Thanks

**Comment by dcress** [comment]
@ganlanyuan Awesome. I'll give it a shot! Thanks SO much for working with me on this!

**Comment by ganlanyuan** [comment]
Added in v2.6.0
