### ISSUE TITLE
on "gallery" does not work "loop: false"

### ISSUE THREAD

**Issue by Slllava** [ganlanyuan/tiny-slider#146]
__Issue description__:  on "gallery" does not work "loop: false"

__Demo link/slider setting__:   https://codepen.io/Slllava/pen/WMwXow

_Tiny-slider version_:   2.5.2
_Browser name && version_:  Google Chrome 63
_OS name && version_:   mac os sierra

**Comment by ganlanyuan** [comment]
Hey, it's true and that's expected.

**Comment by ganlanyuan** [comment]
For `gallery` mode, a slide can't be transforming out while at the same time transforming in. So at least 3 times of `items` displayed on one page are required for this to work.
While I can detect if the total slide number is enough and then decide if the slider can set `loop: false`, but that won't guarantee the `loop` will always be `false` when user set it to.

**Comment by lbineau** [comment]
If you set `animateIn: 'fadeIn'` and `animateOut: 'fadeOut'` it shouldn't need to duplicate the slides for example.
Is there a way to force the loop: false for "gallery" mode? are only set it to false if not provided by the user?
(I have some trouble with duplicated slides a reactive frameworks)

**Comment by ganlanyuan** [comment]
Fixed in v2.7.0
