### ISSUE TITLE
Sliders inside tab content where in aria-hidden is true is broken

### ISSUE THREAD

**Issue by rmlevangelio** [ganlanyuan/tiny-slider#148]
Hi, thanks for your great slider. I tried to initialize sliders on the first load of my page and there are sliders on different tab content. As I toggle other tabs and slide the slider on mobile view, it get stucked and my browser freezes. `autoplay` is `false`.

```
var sliderOptions = {
    container: '',
    items: 1,
    autoplay: false,
    nav: false,
    slideBy: 1,
    gutter: 10,
    edgePadding: 20,
    controls: false,
    animateIn: true,
    lazyload: true,
    mouseDrag: true,
    responsive: {
      760: {
        disable: true
      }
    }
  };
```

_Tiny-slider version_:   Latest
_Browser name && version_:   Chrome latest
_OS name && version_:   Yosemite

**Comment by ganlanyuan** [comment]
Could you make a demo if possible?

**Comment by rmlevangelio** [comment]
@ganlanyuan This one: https://jsfiddle.net/v0vmLvtf/1/

So when you view it greater than 760, the slider is disabled. Then drag down the window to mobile view (because it's the common UX on how to view mobile). You can see the slider still works but when I open a new tab and drag one item, it's not working anymore.

**Comment by rmlevangelio** [comment]
As I continue to test, it only exists with the mousedrag function. When I turn on the navigation and display the slider on hidden tab, then click prev/next button. it works. So the problem is on the mousedrag function where in you need to reselect the current index shown. Any possible ideas how to solve this one?  @ganlanyuan  Thanks again for your amazing slider

**Comment by rmlevangelio** [comment]
An error was printed:
<img width="525" alt="screen shot 2018-02-07 at 1 42 34 pm" src="https://user-images.githubusercontent.com/7041900/35900423-e13e82ce-0c0c-11e8-8ea7-879f549dd5a5.png">

**Comment by ganlanyuan** [comment]
Just figured out what's going wrong here.
The sliders are inside `display: none` blocks which makes the viewport of the sliders `0`. [This commit](https://github.com/ganlanyuan/tiny-slider/commit/3e5a2399bb9d1352195f98e93df995fe7bd946de) should fix this issue.

**Comment by ganlanyuan** [comment]
Added in v2.6.0

**Comment by rmlevangelio** [comment]
This is great. Thanks @ganlanyuan solid work

**Comment by ali-hellani** [comment]
using the latest version of tns. it doesn't work. still the height 0. 
isn't there a way to refresh the slider while switching between tabs
