### ISSUE TITLE
Strict mode Read-Only Properties console error.

### ISSUE THREAD

**Issue by harrypujols** [ganlanyuan/tiny-slider#149]
__Issue description__:  
Console error: "Assignment to read-only properties is not allowed in strict mode"

__Demo link/slider setting__:   
Using Webpack/Babel

_Tiny-slider version_:   
2.4.0

_Browser name && version_:  
MS Edge

_OS name && version_:   
Windows 10

**Comment by harrypujols** [comment]
Closing this ticket. Possible duplicate of https://github.com/ganlanyuan/tiny-slider/issues/123

**Comment by ganlanyuan** [comment]
Hey @harrypujols , 
Is there any special setting for the edge browser?
I still couldn't reproduce this issue.
