### ISSUE TITLE
Request to add `autoWidth` feature

### ISSUE THREAD

**Issue by vonscriptor** [ganlanyuan/tiny-slider#150]
__Issue description__:  The slides appear to always have a fixed width which is not desired. This causes the slides to overlap or have whitespace.

__Demo link/slider setting__:   https://codepen.io/VonScriptor/pen/oEYMmE

_Tiny-slider version_:   2.5.2
_Browser name && version_:  Chrome 63..., Firefox 58
_OS name && version_:   macOS 10.12.6

**Comment by vonscriptor** [comment]
Desired behavior: https://owlcarousel2.github.io/OwlCarousel2/demos/autowidth.html

**Comment by ganlanyuan** [comment]
This feature is not available right now.
Will consider add it later.

**Comment by kyooriouskoala** [comment]
Looking to use this feature too! Hope you can add this in as soon as possible. Thank you!

**Comment by notrealdev** [comment]
+1 billion

**Comment by mattmattvanvoorst** [comment]
+1

**Comment by ganlanyuan** [comment]
Almost there.
You can start test it with the latest commit.
`edgePadding` (maybe `lazyload` too) is still not available now.

**Comment by ganlanyuan** [comment]
It's not released yet, so not in v2.7.4.
Also you need to set "autoWidth: true".

**Comment by ganlanyuan** [comment]
`edgePadding` and `lazyLoad` are available in the latest commit.

**Comment by ganlanyuan** [comment]
Added in v2.8.0

**Comment by vonscriptor** [comment]
Much appreciated! CodePen example updated to show the new autoWidth feature working.
