### ISSUE TITLE
Can i initialize with data attribute setting?

### ISSUE THREAD

**Issue by notrealdev** [ganlanyuan/tiny-slider#154]
Hi, like slick carousel, it is possible to execute this with a Tiny slider
```html
<div class="my-slider" data-tiny-slider='{"loop": false, "items": 3}'>
  <div></div>
  <div></div>
  <div></div>
</div>
```

```js
var slider = tns({
    container: '.my-slider'
});
```

**Comment by ganlanyuan** [comment]
Hey, it's not available right now.
But you can do it with:
```javascript
var sliderContainer = document.querySelector('.my-slider'),
    opt = JSON.parse(sliderContainer.getAttribute('data-tiny-slider'));

opt.container = sliderContainer;

var slider = tns(opt);
```

**Comment by notrealdev** [comment]
It working, thank you !!!

**Comment by notrealdev** [comment]
Hi, the `arrowKeys` option seems does not work properly, it always shows when the option set is `false`
Can you check it?
Tiny slider v2.5.2

**Comment by ganlanyuan** [comment]
What's the type of the value?
String or Boolean

**Comment by ganlanyuan** [comment]
Oh, yes.
`controls` is for prev/next buttons.
`arrowKeys` bind the prev/next button functions to arrow keys on the keyboard.
