### ISSUE TITLE
Insert options dynamically

### ISSUE THREAD

**Issue by andercard** [ganlanyuan/tiny-slider#155]
__Issue description__:  
Hello, very good bookstore, I have a question, how could I insert an option dynamically, I want to deactivate the touch in a specific box in the slick library, I used it in this way

__Demo link/slider setting__:   

function toggleSlider(element,status) {

  var mc = new Hammer(element);
  // listen to events...
  mc.on("swipe", function(ev) {
      sliderGeneral.slick('slickSetOption',{'draggable': status})
      sliderGeneral.slick('slickSetOption',{'swipe': status})
  });
}
var contenedorMapa = document.getElementById('contenedor-mapa');
toggleSlider(contenedorMapa,false)
// activar slider con mouse y swipe
var contenedorVideo = document.getElementById('contenedor-video');
toggleSlider(contenedorVideo,true)

_Tiny-slider version_:   
_Browser name && version_:  
_OS name && version_:

**Comment by ganlanyuan** [comment]
Updating options dynamically isn't available right now.

**Comment by iamrobert** [comment]
We wanted to work with plyr.io to add video. So we worked around this by adding to the slide a class "video-item" to stop it sliding when people clicked buttons on the video slide:

```javascript
Array.prototype.slice
      .call(document.querySelectorAll(".video-slide"))
      .forEach(function(slide) {
        slide.addEventListener("touchstart", function(ev) {
          ev.stopPropagation();
        });

        slide.addEventListener("mousedown", function(ev) {
          ev.stopPropagation();
        });
      });
```
Full Code here:
https://gist.github.com/iamrobert/9c0191720bd6b07d9bf70cb3b1ef62d5

**Comment by ganlanyuan** [comment]
@iamrobert Actually tiny-slider is able to distinguish "click", "swipe" and "drag". If you encounter any problem with this, welcome to fire an issue.
