### ISSUE TITLE
[Request] "Freescroll" on mouse scroll

### ISSUE THREAD

**Issue by nicholas-c** [ganlanyuan/tiny-slider#156]
I'm using this slider in the vertical axis, and have had to do some hacky stuff. The requirements are that...

1) The vertical content area is scrollable via the mousewheel
2) Is a "carousel" and has pagedot controls
3) Jumps from slide to slide (continues scrolling if slide is bigger than the viewport)

Let me know if this is currently possible, or would be a feature in the future!

**Comment by ganlanyuan** [comment]
The mouse wheel scrolling function need to be added, others are available now.
Have a look at [this demo](http://ganlanyuan.github.io/tiny-slider/tests/index.html#vertical_wrapper).

**Comment by ganlanyuan** [comment]
Hey, sorry for the late response.
> 1. The vertical content area is scrollable via the mousewheel

Did you mean move the slider from slide to slide when scroll with mouse wheel?

**Comment by pedro-rivera** [comment]
@ganlanyuan any updates on change slides on mouse scroll?

**Comment by frink** [comment]
@ganlanyuan I'd assume that he meant scroll-jacking as you suggested.

**I'm also looking for the same interaction...**
Scrolljacking functionality is very helpful when using general purpose sliders for off brand use cases like in one page sites and apps. The arguments against scroll-jacking are mostly related to accessibility. I don't know if ARIA support has been addressed or not. But if ARIA is addressed then there is no reason to avoid scrolljacking as an option. Most people expect it on sliders these days...

**Now that being said, there is an issue when nesting sliders...**
Here, it becomes important that the right element's scrolling gets focus. Different browsers still have different percolation models for scroll events forcing us to jump through more hoops than we should have to. I've tried to build sliders a couple of times that handle this edge case. If you've solved the nested solution for touch then scrolling will probably perform similarly. I haven't tried to address this issue in 3 years so a lot may have changed that simplifies things...

**Comment by godzik** [comment]
> The mouse wheel scrolling function need to be added, others are available now.
> Have a look at [this demo](http://ganlanyuan.github.io/tiny-slider/tests/index.html#vertical_wrapper).

@ganlanyuan Good day sir, link is dead. Could you provide an example what should be added to have this feature please? Ty in advance.

**Comment by roycruse** [comment]
Anyone landing here looking for mousewheel support to get a side scolling tiny-slider to scroll with the mousewheel - im using this and it works very well.

`<script>
let canScroll = true;
document.addEventListener('wheel', (event) => {
  if (!canScroll) {
    return; 
  }

  canScroll = false;
  setTimeout(() => {
    canScroll = true;
  }, 250);
  
  scrollDir = event.deltaY > 1 ? 1 : -1;

  if(scrollDir>0) {
    slider.goTo('next');
  }else{
    slider.goTo('prev');
  }
});
</script>`

**Comment by melcarthus** [comment]
> Anyone landing here looking for mousewheel support to get a side scolling tiny-slider to scroll with the mousewheel - im using this and it works very well.
> 
> ```
> <script>
> let canScroll = true;
> document.addEventListener('wheel', (event) => {
>   if (!canScroll) {
>     return; 
>   }
> 
>   canScroll = false;
>   setTimeout(() => {
>     canScroll = true;
>   }, 250);
>   
>   scrollDir = event.deltaY > 1 ? 1 : -1;
> 
>   if(scrollDir>0) {
>     slider.goTo('next');
>   }else{
>     slider.goTo('prev');
>   }
> });
> </script>
> ```

Your script is not finished, you have not defined ```scrollDir```.

**Comment by sander-spruit** [comment]
This function doesn't work properly on touchpads and registers 'ghost' scrolling.
