### ISSUE TITLE
The div of the class 'tns-controls' makes the previous and next buttons less flexible

### ISSUE THREAD

**Issue by nandes2062** [ganlanyuan/tiny-slider#160]
__Issue description__:  
The previous and next buttons should be more flexible for CSS manipulation, this would be solved if these buttons were outside the div of the class 'tns-controls'

_Tiny-slider version_:   v2.6.0
_Browser name && version_:  All
_OS name && version_:   All

**Comment by ganlanyuan** [comment]
Hey, you could use `controlsContainer` to customize the prev/next buttons.

**Comment by nandes2062** [comment]
Thank you very much, I did not see that option, with the creation of the nodes it is resolved :)
