### ISSUE TITLE
Multi sliders with the same class name

### ISSUE THREAD

**Issue by elziny** [ganlanyuan/tiny-slider#161]
When I put multi div with the same slider container class, it works for the first div only.
Not all DIVS becomes sliders.

**Comment by ganlanyuan** [comment]
Same as #103

**Comment by kanaksinh-zwt** [comment]
*u can use like this*
----------------
const tnsCarousel = document.querySelectorAll('.tns-slider');

tnsCarousel.forEach(slider => {
                const tnsSlider = tns({
                    container: slider,                   
                });
            });
------------------------------
> When I put multi div with the same slider container class, it works for the first div only.
> Not all DIVS becomes sliders.
