### ISSUE TITLE
Mobile swiping enhancements (vertical lock and performance)

### ISSUE THREAD

**Issue by danny7i** [ganlanyuan/tiny-slider#162]
__Issue description__:  
There are a couple of issues when you swipe left or right on mobile:

1. the page can scroll vertically because people don't usually make accurate horizontal gestures, however if it is not intended it can hurt user experience. 
2. the animation sometimes feels a bit janky as well, even on powerful phones. 

It would be nice to have the swiping experience on mobile closer to or on par with Slick, especially that they did with vertical locking once the user start swiping left or right, and the smooth animation.

See: http://kenwheeler.github.io/slick/

Fantastic work so far but with these improvements it would be a killer! Thank you very much.

**Comment by ganlanyuan** [comment]
I was struggling with these two actually:
a. move freely while the slider may unexpectedly move left or right when you scroll the page within the slider
b. vertical locking while it feels not so smooth
I finally chose b while slick you mentioned chose a.



> vertical locking once the user start swiping left or right

Does it against [smooth scrolling](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md)?

**Comment by khryshyn** [comment]
Swiping doesn't work properly - it is very slowly, sometimes items aren't scrolled at all.
Please check it on the demo pages using the Ipad

**Comment by ganlanyuan** [comment]
> sometimes items aren't scrolled at all

This is probably because the slider didn't finish its transform while you swipe it again 😃

**Comment by khryshyn** [comment]
The issue with a poor user experience that was reported by danny7i also reproduced with my touch devices. We'll really appreciate if you fix that problem. Thanks

**Comment by ganlanyuan** [comment]
Add a new option `swipeAngle` in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/bae12e1ea3bfcbe45cbc72851b76ec2be3af1cc9).
You now can set `swipeAngle: false` to achieve this.
Please let me know if this helps. Thanks

**Comment by khryshyn** [comment]
ok, thanks, let us check!

**Comment by khryshyn** [comment]
Thanks a lot! Swipe is working more predictable now, but vertical lock is still the ux problem for users. While you swiping the carousel the website still able to change the scroll position.

**Comment by ganlanyuan** [comment]
Hey, I will not add this since it against [smooth scroll](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md)

**Comment by darith27** [comment]
@ganlanyuan how would I enable vertical swiping instead of horizontal swiping? I tried `90` for swipeAngle but it's still accepting horizontal swiping gestures.

**Comment by fidelguevera** [comment]
@ganlanyuan Why you're not using 3d transforms? that could improve overall sliding experience.

**Comment by ganlanyuan** [comment]
Can you give some examples?

**Comment by fidelguevera** [comment]
now you use only transform X,Y
transform: translateX(-40%);
but if you will use:
transform: translate3d(-40%, 0,  0);
it will enable GPU and the sliding itself will be much smoother, as now it struggling a bit and it's really visible.

**Comment by ganlanyuan** [comment]
I see, thanks
will update this in the next release

**Comment by ganlanyuan** [comment]
@entwicklerRepo Switched to 3d transform in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/3480c5a7d043c015e070b2f0778130b50c182558), will be available in next release.

**Comment by ganlanyuan** [comment]
Just add an option `preventScrollOnTouch` with two available values: "auto", "force".
With "force", page scrolling will always be blocked.
With "auto", the slider will first check the swipe direction, then decide to block the page scrolling or not.
