### ISSUE TITLE
Wrong index in indexChanged event

### ISSUE THREAD

**Issue by makedonec88** [ganlanyuan/tiny-slider#163]
__Issue description__:  
When slide have changed, `indexChanged` event returning wrong `index`.
I'm expecting to have indexes from 0 or 1 to N, but instead getting some random values, 

![demo](https://media.giphy.com/media/KXs7uv5mySrttvP2Al/giphy.gif)

__Demo link/slider setting__:   
https://codepen.io/makedonec88/pen/MQZLmL
_Tiny-slider version_:   2.6.0

**Comment by ganlanyuan** [comment]
Hey, the output is actually correct.
Since the default options for `loop` is `true`, so there are some cloned slides before the first slide displayed on the screen.

**Comment by jayden2** [comment]
although I remember getting around this by using data attributes.
It would be nice to have a displayIndex, currentSlide or something along those lines.

**Comment by ganlanyuan** [comment]
index - cloneCount = visual index

**Comment by Suruat** [comment]
@ganlanyuan Why don't make this math go inside of the plugin and return already operational index that represents expected way of things?

**Comment by Suruat** [comment]
How is implementing `index - cloneCount = visual index` math inside slider codebase will produce situation you've described?

**Comment by ganlanyuan** [comment]
So did you mean add one more variable: `visualIndex` to present the current visual index?

**Comment by tomsnep** [comment]
Would indeed be nice to have a visualIndex to make a slide indicator 
e.g: 02/07

**Comment by ganlanyuan** [comment]
`displayIndex` added. (https://github.com/ganlanyuan/tiny-slider/issues/304#issuecomment-432386766)
Will be available in next release.
