### ISSUE TITLE
 Error with mouse drag option with forms

### ISSUE THREAD

**Issue by andercard** [ganlanyuan/tiny-slider#164]
__Issue description__:  

Hi, I have an error when I activate the mouse drag option, it does not let me focus the inputs of the form

__Demo link/slider setting__:  
 
https://imgur.com/a/M7jSu

_Tiny-slider version_:   
_Browser name && version_:  
_OS name && version_:

**Comment by ganlanyuan** [comment]
I need some time to carefully distinguish clicks from drags.
For now you can just disable the mouse drag option.

**Comment by andercard** [comment]
thank you very much friend

**Comment by ganlanyuan** [comment]
The issue should be fixed in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/b73e0fdc10eba4da571e046b49f51bf804d7a4fe).
Please let me know if it works for you.
Thanks

**Comment by andercard** [comment]
Yes, this solves the problem thanks

**Comment by ganlanyuan** [comment]
Fix added in v2.7.0

**Comment by cyocun** [comment]
hi!

I am using the latest 2.9.1.
It seems that the same problem has recurred.

It happens occasionally.
After touch, or mouse drag almost reproduces.

Can you make it correspond?
