### ISSUE TITLE
Event that can be fired right after Slider initialization

### ISSUE THREAD

**Issue by khryshyn** [ganlanyuan/tiny-slider#166]
Would be nice to have Event that can be fired right after Slider initialization
Current onInit callback invoking to earlier. At this stage, we can't get the information regarding the current carousel state, items, events, etc...

version:  2.6

**Comment by ganlanyuan** [comment]
Hey, I explained why `initialized` event won't work [here](https://github.com/ganlanyuan/tiny-slider/tree/v1.6.0#custom-events).
BTY, the `onInit` function will be fired right after the initialization. https://github.com/ganlanyuan/tiny-slider/blob/99c93e934356a41d5248a6c6c0cf85cbc8974a6c/src/tiny-slider.js#L937

**Comment by maschmiede** [comment]
I jumped over this ticket because I've needed that as well. Here is what I've done:

```
let sliderPromise = new Promise(function(sliderResolve) {
    const slider = tns({
        container: '.slider',
        autoplay: true,
        // ...
    });
    sliderResolve(slider.getInfo().container);
});

sliderPromise.then(function(sliderContainer){
    // .. code after the slider has been built up
});
```

**Comment by feodoraxis** [comment]
I was able to resolve it this way:
```
const slider = tns({
  container: "#slider",
  onInit: (e) => {
    //Your code after init
  },
  //...
})
```
