### ISSUE TITLE
runAutoHeight 

### ISSUE THREAD

**Issue by katzsimon** [ganlanyuan/tiny-slider#167]
Seems like the variable "items" is a number in a string in the runAutoHeight() function
And so "l = index + items" is concatenating as a string instead of adding the numbers together and causing the function to crash

adding parseInt(items) seems to fix it

function runAutoHeight () {
    if (autoHeight && !disable) {
      // get all images inside visible slide items
      var images = [];
      for (var i = index, l = index + items; i < l; i++) {

_Tiny-slider version_: 2.6  
_Browser name && version_:  Firefox 58
_OS name && version_:   Windows 10

Awesome work on the slider!

**Comment by ganlanyuan** [comment]
May I know your slider options?
Both `index` and `items` should be numbers.

**Comment by katzsimon** [comment]
Ah you are right.

How I was building and encoding my options the number got converted into text on my side. Forced it into an integer before passing it in and all works 

Thanks

**Comment by ganlanyuan** [comment]
Glad to see you resolve it!
