### ISSUE TITLE
Adjust height when something get changed within the slide

### ISSUE THREAD

**Issue by entwicklerRepo** [ganlanyuan/tiny-slider#168]
__Issue description__:  is it possible that slide height could be adjusted if something changed within the slide, as now when auto-height is set it changes the height only for next slide or if screen size has changed.

__Demo link/slider setting__:   

_Tiny-slider version_:   2.6.0
_Browser name && version_:  All Modern Browsers
_OS name && version_:   Windows/MacOSX

**Comment by thomasflad** [comment]
That would be awesome! Or is there a function to trigger the height calculation manually?

**Comment by ganlanyuan** [comment]
I will look into it shortly

**Comment by ganlanyuan** [comment]
Added a method `updateSliderHeight` in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/d9f69664228eb7642d3115289d46b743b81b0e57).
You can use it like this:
```javascript
var slider = tns({your: options});

slider.updateSliderHeight();
```

**Comment by fidelguevera** [comment]
@ganlanyuan Hm not sure that this is what I expected, I don't want to fire additional function as I have different actions within the slider so it means I should fire this function every time I click something, which is a bit weird. Is there a way just to listen for inner changed and update it automatically? O I'm not fully getting how this function works now?

**Comment by ganlanyuan** [comment]
What kinds of changes you want to listen to?

**Comment by fidelguevera** [comment]
@ganlanyuan height of tns-slide-active if it changes it should update the height of tns-inner

**Comment by ganlanyuan** [comment]
There is no easy way to listen to this.
Maybe [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) can watch this but it has to be related to childList, attributes or characterData changes.
