### ISSUE TITLE
Swiping when previous swipe animation not finished doesn't work

### ISSUE THREAD

**Issue by cyrilchapon** [ganlanyuan/tiny-slider#171]
Trying to "swipe" (mobile or mice) when previous swipe animation has not finished leads to a "blocked" experience.

To reproduce
- mousedown
- mousemove
- mouseup
- (fastly) re-mousedown (animation not ended)
- keep button down and mousemove. Nothing happens.

**Comment by cyrilchapon** [comment]
While understandable, this is a strong UX issue :/

**Comment by ganlanyuan** [comment]
I will trying to find a solution for this shortly.
Thanks

**Comment by cyrilchapon** [comment]
I didn't read anything from the code, but is that css transitions ?

**Comment by ganlanyuan** [comment]
Yes, css

**Comment by cyrilchapon** [comment]
Any update on this ? :)

**Comment by ganlanyuan** [comment]
Fixed in v2.7.0
