### ISSUE TITLE
EdgePadding plus LazyLoading options breaks slider

### ISSUE THREAD

**Issue by sjgstarz** [ganlanyuan/tiny-slider#172]
__Issue description__:  I am receiving 'cannot call querySelectorAll of undefined' error currently under the conditions of setting the edgePadding and lazyload options.  Looks like when edge padding and lazy loading are enabled at the same time the index is set to -1 and the slideItems at index -1 returns undefined.  This was originally spotted in #106.

__Demo link/slider setting__:   edgePadding, lazyload

_Tiny-slider version_:   2.6.0
_Browser name && version_: All 
_OS name && version_:   Windows

**Comment by ganlanyuan** [comment]
I do have a [demo](http://ganlanyuan.github.io/tiny-slider/tests/index.html#lazyload_wrapper) for this case and seems it is fine.
Can you make a test page for this?

**Comment by dsl-src** [comment]
@ganlanyuan 
This occurs when the slides is less than the set value in the ```items: //some count ``` and set value ```lazyload: true```.
**And this is a common occurrence.**

To fix this issue you need to add this code:
```js
if (slideItems[i]) {
 // other code
}
```
between this code https://github.com/ganlanyuan/tiny-slider/blob/master/src/tiny-slider.js#L1496 and this https://github.com/ganlanyuan/tiny-slider/blob/master/src/tiny-slider.js#L1497

**Comment by ganlanyuan** [comment]
https://codepen.io/ganlanyuan/pen/WyOmyJ?editors=1111
Check out this demo which uses tiny-slider 2.6.
I still didn't see any issue here.

**Comment by dsl-src** [comment]
Forgot to say what to add value ``` loop: false ```

**Comment by ganlanyuan** [comment]
https://codepen.io/ganlanyuan/pen/WyOmyJ?editors=1111
It still fine after set `loop: false`.

**Comment by dsl-src** [comment]
<img width="1627" alt="2018-06-15 17 58 06" src="https://user-images.githubusercontent.com/11549097/41475082-6c19e262-70c6-11e8-8ba1-b1a90c0080cf.png">

**Comment by dsl-src** [comment]
Can you please update ``` tag ``` with these new fixes ?

**Comment by dsl-src** [comment]
@ganlanyuan 
This error still continues to appear if you add more ``` edgePadding : //some value ```

**Comment by ganlanyuan** [comment]
Sorry I didn't consider `edgePadding` factor, should be fixed in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/b5267fe8892797dadf7d949c1ebd37f2b46b7595).
Please let me know if it works for you.

**Comment by dsl-src** [comment]
@ganlanyuan 
This helped, but with the resize, this error appears again. Add a simple check that this is an element and it will solve all the problems.

**Comment by ganlanyuan** [comment]
@dsl-src thanks for your feedback and pull requests, but I don't want to do the check for each instance due to performance.
The the issue related to resize event is cause by `getIndexMax()`. I just committed a [`fix`](https://github.com/ganlanyuan/tiny-slider/commit/651f948d997e25a637a6742618034794360be57f) for it. Could you check if the issue still occurs?

**Comment by dsl-src** [comment]
@ganlanyuan 
This issue fixed.
Could you make a new tag(the new version that I could update)?

**Comment by ganlanyuan** [comment]
v2.7.3 was published
