### ISSUE TITLE
Responsive target

### ISSUE THREAD

**Issue by claudiorivetti** [ganlanyuan/tiny-slider#173]
__Issue description__:  This is a feature request. I have noticed that the responsive option is referred to the width of the window and not to the with of the slider container. However, in my case the slider is in between two side bars that can appear/disappear base on the window with. For some width intervals, this makes the slider to become larger while the window gets smaller.

Request: Would it be possible to have a "responsiveTarget" option (default to "window") where to set the element whose width is observed for responsiveness?

__Demo link/slider setting__:  

_Tiny-slider version_:   2.6.0
_Browser name && version_:  All
_OS name && version_:   windows

**Comment by ganlanyuan** [comment]
There is an issue related to this, please check out #100

**Comment by ganlanyuan** [comment]
If the slider need to watch the changes of the container rather than the window, a plugin would be added to this task. Because there is no `container queries` supports right now in the browsers and the slider is only rely on `media queries`.
