### ISSUE TITLE
2 slides needed, but inspector shows 10 created after slider is initialized

### ISSUE THREAD

**Issue by tylik1** [ganlanyuan/tiny-slider#175]
Not sure why 5 clones are needed for each slide. It seems an overkill to me. 
I've noticed this only happens when loop is set to true, but still the amount of clones looks like a lot

http://ganlanyuan.github.io/tiny-slider/tests/index.html
v2.6.0 
Chrome latest
Mac OS

**Comment by ganlanyuan** [comment]
Yes, 5 times of `items` are needed for the transforms.
I will update it to make less clones if slides are more than `items` later.

**Comment by ganlanyuan** [comment]
Fixed in v2.7.0
