### ISSUE TITLE
Possible to randomize slide order?

### ISSUE THREAD

**Issue by briangoodman** [ganlanyuan/tiny-slider#177]
__Issue description__:  Is it possible to randomize the slide order?  If you, what is the best way to accomplish the randomization?

__Demo link/slider setting__:   

_Tiny-slider version_:   current
_Browser name && version_:  any
_OS name && version_:   not relevant

**Comment by ganlanyuan** [comment]
This is probably not related to the slider.
Right now the slider only works upon static content.
