### ISSUE TITLE
No CSS on buttons

### ISSUE THREAD

**Issue by VisheshJaiswal** [ganlanyuan/tiny-slider#178]
__Issue description__:  I try to create a simple carousel, the buttons looks base. at first i thought the CSS has not loaded correctly.

__Demo link/slider setting__:   https://codepen.io/codeSparrow/pen/bvQJNM

_Tiny-slider version_:   2.6.0
_Browser name && version_:  Chrome 65.0.3325.181
_OS name && version_:   win 10

**Comment by ganlanyuan** [comment]
No default styles for the buttons.
You'll add your own styles any way.
