### ISSUE TITLE
Resize for vertical slider

### ISSUE THREAD

**Issue by rdoc101** [ganlanyuan/tiny-slider#179]
__Issue description__:  resizeTasks() is not fired  in the onResize method upon a vertical only window resize. For a vertical aligned slider this messes up the vertical offset.

**Comment by ganlanyuan** [comment]
What exactly is the issue you're encountering?

Right now the [responsive options](https://github.com/ganlanyuan/tiny-slider#responsive-options) are only related to window width, so it doesn't make sense to check the window height changes. But if you want set the responsive options related to window height, I will consider add an option.

**Comment by rdoc101** [comment]
Not so much about responsive options, but about what happens on a window resize. With respect to a vertical slider, after the window resizes vertically the vertical offset is not recalculated and so the visible slide sits vertically out of line.

**Comment by viktorlarsson** [comment]
@ganlanyuan 
I would actually need to change the axis when it heads down to mobile from vertical to horizontal. is that possible?

**Comment by ganlanyuan** [comment]
@rdoc101 Just added a [fix](https://github.com/ganlanyuan/tiny-slider/commit/942fdfd7f0a6a3215aff70243b53e4094ec60eb8)
@viktorlarsson You may need to destroy it and rebuild again

**Comment by ganlanyuan** [comment]
@rdoc101 fixed in v2.7.0
