### ISSUE TITLE
Error if number of items is under the amount set in parameter

### ISSUE THREAD

**Issue by arlg** [ganlanyuan/tiny-slider#181]
__Issue description__:  
Hi, first, thanks for this awesome plugin :)
I encountered a bug today using it. Let's say i have a slider with 3 items. If i set up a slider with an items at 4, i have an error : 

![capture d ecran 2018-04-12 a 16 48 35](https://user-images.githubusercontent.com/1463222/38685282-d244b350-3e71-11e8-810a-d0e175d76095.png)

This is happening when my client doesn't have enough slides to fill the slider. 
It would be nice to have a test saying that if the number of items requested is higher than the slider items present inside the webpage, the max would be set between the two. 

__Demo link/slider setting__:   

    `const agendaSlider = tns({
            container: '.agenda-slider',
            items: 1,
            slideBy: 1,
            autoplay: false,
            responsive: {
                "450": {
                    items: 2
                },
                "790": {
                    items: 3
                },
                "990": {
                    items: 4
                }
            }
        });`

I managed to make it work locally with this code : 

    `const maxItems = Math.min( 4, document.querySelectorAll('.agenda .slider-item').length );
     const agendaSlider = tns({
            container: '.agenda-slider',
            items: 1,
            slideBy: 1,
            autoplay: false,
            responsive: {
                "450": {
                    items: 2
                },
                "790": {
                    items: maxItems - 1
                },
                "990": {
                    items: maxItems
                }
            }
        });
`

_Tiny-slider version_:   Latest
_Browser name && version_: All 
_OS name && version_:   All

**Comment by ganlanyuan** [comment]
Hi, 
I couldn't reproduce this issue.
https://codepen.io/ganlanyuan/pen/ZojpEj

**Comment by arlg** [comment]
Actually can't reproduce on my end. Thank you
