### ISSUE TITLE
add custom event(s) for breakpoints

### ISSUE THREAD

**Issue by iamricky** [ganlanyuan/tiny-slider#183]
__Issue description__:
I've noticed that tiny-slider rebuilds at each breakpoint listed in my `responsive` object. Assuming that this doesn't exist already, would it be possible to add a custom event to announce the beginning and end of rebuilds, e.g. `rebuildStart` and `rebuildFinish`.

I could open a PR myself, if pointed in the right direction.

__Demo link/slider setting__: 
(top-level config object)
```
{
  arrowKeys: true,
  controls: ["", ""],
  container: ".js__slider",
  controlsContainer: ".js__controls",
  navContainer: ".js__nav",
  items: 1,
  loop: false,
  speed: 900
}
```

(responsive config object)
```
{
  768: {
    edgePadding: 18,
    gutter: 25,
    fixedWidth: 681,
    items: 1
  },
  1280: {
    edgePadding: 33,
    gutter: 40,
    fixedWidth: 1134,
    items: 1
  },
}
```

_Tiny-slider version_:   `"tiny-slider": "~2.6.0"`
_Browser name && version_:  Google Chrome Version 65.0.3325.181
_OS name && version_: macOS Sierra 10.12.6

**Comment by ganlanyuan** [comment]
May I know the purpose of the events of breakpoints?
When the window size change to another breakpoint, some properties will change and some will not. It's based on the responsive options. There is no rebuild except for `freezable` or `disable` options.
But you can always check the `indexChange`s or transition start or end during the resizing.

**Comment by norin89** [comment]
+1

It might be useful with custom controls. E.g. I'd like to check if all slides fits in one view - if so hide the controls. Now to achieve that I have to add event listener on resize myself Instead of add event on Slider `update` or something like that - which also have it's own `resize` event listener.

**Comment by ganlanyuan** [comment]
Events `newBreakpointStart` and `newBreakpointEnd` added in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/5504949201e09031a2963d13a4bdaeb64e190de8).

**Comment by ganlanyuan** [comment]
Added in v2.7.4

**Comment by missmatsuko** [comment]
@ganlanyuan I found this feature when I was looking for a similar issue. The new events aren't documented in the readme.

**Comment by ganlanyuan** [comment]
Thanks for reminding me.
I will update the document once I get a chance.

**Comment by missmatsuko** [comment]
@ganlanyuan Great. Let me know if you need help! I was also thinking it would be nice if the features table in the readme were an actual table instead of an image (for accessibility, copy/pasting).

**Comment by ganlanyuan** [comment]
Sounds good
