### ISSUE TITLE
Controls rendering location

### ISSUE THREAD

**Issue by mabar** [ganlanyuan/tiny-slider#185]
Is it possible to configure where are controls rendered? I would like render controls around slider, so it would instead of
```
<controls></controls>
<slider></slider>
```
render 
```
<left-control></left-control>
<slider></slider>
<right-control></right-control>
```

**Comment by ganlanyuan** [comment]
Not possible for now, but may consider add options `prevButton`, `nextButton` so you could put them wherever you like.
