### ISSUE TITLE
It doesn't work. See fiddle.

### ISSUE THREAD

**Issue by trusktr** [ganlanyuan/tiny-slider#187]
https://jsfiddle.net/at41da6k/1/

**Comment by Raabye** [comment]
It does work, add more slides(div) to your slider, or set tns({items: **3**}) to tns({items: **2**} or less.
No controllers will be shown if the number of slides and items-settings are the same. As in your case 3 slides with items set to 3.

**Comment by ganlanyuan** [comment]
I agree `items` is a little confusing.
How about `itemsPerPage`, `itemsVisible`?

**Comment by vinogradov** [comment]
I don't know. It was my first impression. Now `items` is totally fine for me personally 😀  Maybe it's worth just adding a comment to the README example, something like `items: 3 // items per page. You have to have more than 3 items to get slider working`
