### ISSUE TITLE
Loop: false doesn't work with mode: 'gallery'

### ISSUE THREAD

**Issue by lindseybradford** [ganlanyuan/tiny-slider#188]
__Issue description__:  

Loop: false doesn't work with Fade (mode: 'gallery'). Is there a combination of config settings that will allow fade transitions _and_ prevent loop behavior?

The cloning for loop behavior is undesirable when you have videos within slides—you then have multiple videos with the same IDs and other data attributes and controlling them programmatically becomes tricky, for one thing.

Also, thanks for building tiny slider!

__Demo link/slider setting__:   
 
```
var slider = tns({
   mode: 'gallery',
   loop: false
});
```
https://www.dropbox.com/s/c6ox8d1ormlvyvu/Screenshot%202018-04-20%2013.31.08.png?dl=0

_Tiny-slider version_:   tiny-slider 2.0

_Browser name && version_:  Chrome 65

_OS name && version_:   El Capitan

**Comment by ganlanyuan** [comment]
Same with #146 
Will consider NOT clone slides if they're enough for the functionality.
