### ISSUE TITLE
MouseDrag on a slide with a link element opens the target of the link

### ISSUE THREAD

**Issue by AnupamKhurana** [ganlanyuan/tiny-slider#189]
__Issue description__:  Need help in resolving this issue. When I use mouseDrag for a link in the slide or if the entire slide is a link, the target page opens when mouseUp fires. Ideally, the deired behaviour is that after the mouseDrag, the iser click mouse on the slide/link inside it to go to the target url.

__Demo link/slider setting__:   

_Tiny-slider version_:   2.6.0
_Browser name && version_:  all
_OS name && version_:   all

**Comment by ganlanyuan** [comment]
Can you try with the [mouse-drag demos](http://ganlanyuan.github.io/tiny-slider/tests/index.html#mouse-drag_wrapper)?
They work as expected as I tested.

**Comment by norin89** [comment]
+1

I found exactly the same behaviour in my project. I will try to investigate and reproduce the issue as it doesn't seem to happen on mouse-drag demo.

**Comment by ganlanyuan** [comment]
@norin89 Okay, let me know when this is done. thanks

**Comment by norin89** [comment]
@ganlanyuan I wanted to reproduce the issue but now it works fine w/o any change in my project. I got no clue what's going on.

**Comment by ganlanyuan** [comment]
Okay, thanks for letting me know. Will close for now.
Feel free to reopen it when you find this happens again.

**Comment by RobinDev** [comment]
Same problem when using gallery plugin like maginific pop up or baguetteBox : 
https://codepen.io/anon/pen/OaMLew

If i switch tiny-slider per owl-caroussel, this issue disappear.

**Comment by rtvt** [comment]
+ same problem. Want to use slider for products carousel. have a link on product image and title, when I mouseup link get triggered and go to href.

**Comment by Rotmistrz** [comment]
Okay, now the slider doesn't open the link but is blocking itself and it's not possible to drag it when has links as elements... Huge bug! It's starting to drag the whole carousel HTML object (like in drag & drop) instead of move the carousel's items...
