### ISSUE TITLE
Go to first & last

### ISSUE THREAD

**Issue by rolandtoth** [ganlanyuan/tiny-slider#19]
I cannot find a method to programmatically go to the first or last item. I would like to add custom buttons to slide to the first or last item. Is there a way to do this, or is such feature planned (slideTo() or similar)?

**Comment by ganlanyuan** [comment]
Hey, there is no such feature right now.
But I will consider to add it maybe one or two weeks later.

**Comment by rolandtoth** [comment]
Thanks - in the meantime I figured out that I could trigger the first and last items of the nav buttons as a workaround (though haven't tried).

**Comment by ganlanyuan** [comment]
Okay

**Comment by ganlanyuan** [comment]
Hey, 
The feature is added in [v1.1.0](https://github.com/ganlanyuan/tiny-slider/tree/v1.1.0), details please refer to [here](https://github.com/ganlanyuan/tiny-slider#goto).
Please let me know if this is what you expected.
Thanks

**Comment by rolandtoth** [comment]
Looks great, thanks! I can't try it atm but will soon.

**Comment by ganlanyuan** [comment]
A new release [v1.1.1](https://github.com/ganlanyuan/tiny-slider/releases/tag/v1.1.1) fixed a `goTo('prev'/'next')` issue when option `slideBy` is set to "page".

**Comment by ganlanyuan** [comment]
I will close it for now.
If you have further issues, feel free to open it again.
Thanks

**Comment by rolandtoth** [comment]
Just tried it and all the examples in the readme are working fine here, thanks again!

**Comment by ganlanyuan** [comment]
Okay, thanks for the feedback!
