### ISSUE TITLE
Slides have extra offset in Microsoft Edge browser

### ISSUE THREAD

**Issue by vinogradov** [ganlanyuan/tiny-slider#190]
__Issue description__:  
![image](https://user-images.githubusercontent.com/439939/39248986-997baeec-48ae-11e8-83eb-3108d373929d.png)

__Demo link/slider setting__:   
https://jsfiddle.net/vrkk0m7z/1/
![image](https://user-images.githubusercontent.com/439939/39249014-ae5c97fe-48ae-11e8-9d4b-bcb593232329.png)
settings:
```
{
  items: 1,
  slideBy: 'page'
}
```

_Tiny-slider version_:   2.6.0
_Browser name && version_:  Microsoft EdgeHTML 15.15063
_OS name && version_:   Windows 10

**Comment by ganlanyuan** [comment]
I guess Edge has some issue render percentage width. 
I will search more to see if there is a solution.
Thanks for letting me know.

**Comment by ganlanyuan** [comment]
https://codepen.io/ganlanyuan/pen/ERboVM
As I tested, MS Edge browsers have issue rendering the elements when `%` widths are used on both parent and child elements.

**Comment by ganlanyuan** [comment]
This issue should be fixed start from [this commit](https://github.com/ganlanyuan/tiny-slider/commit/7f149dcbae9612cc79f13500f28d9966cbc85d7f). 
Could you check it out?

**Comment by vinogradov** [comment]
Works now! Thank you so much!

**Comment by ganlanyuan** [comment]
This fixed was included in v2.7.4
