### ISSUE TITLE
Angular 2 compatibility - ngFor

### ISSUE THREAD

**Issue by LandenW** [ganlanyuan/tiny-slider#192]
Hi! Nice light weight slider. I have been messing with it it an angular 2 project. I was hoping to populate the slides using an *ngFor in the html mark up to loop through a given array but it doesn't seem to be working, is this supported? If not, it may be a nice future feature. I can post an example if need be. Thank you!

**Comment by ganlanyuan** [comment]
Hi, the slider only works on static contents.
So make sure the markup is finalized when you call the slider.

**Comment by LandenW** [comment]
Okay, thanks!

**Comment by ganlanyuan** [comment]
You're welcome
