### ISSUE TITLE
Can't seem to destroy sliders?

### ISSUE THREAD

**Issue by youradds** [ganlanyuan/tiny-slider#193]
I can't work out what I'm doing wrong here:

```
                        window.VARS.slider_ids.push(link_id);
                        window.VARS.slider[link_id] = tns({
                            container: '.my-slider-'+link_id,
                            items: items,
                            slideBy: 'page',
                            autoplay: true,
                            nav: false,
                            controls: false
                        });
```

This creates the slider fine. Then further in my code, I have a "resize" hook that checks the width of the BLOCK the slider is in (not the page width, as we show in columns so this isn't helpful). The problem I'm having is rebuilding the slider again:

```
            if (window.VARS.slider_ids) {
                window.VARS.slider_ids.forEach(function(link_id, i){
                    console.dir(window.VARS.slider[link_id]);
                    window.VARS.slider[link_id].destroy();
                    //window.VARS.slider[link_id].rebuild();
                });
            }

```
In the debug I see:

> {…}​destroy: null​events: null​getInfo: null​goTo: null​isOn: false​pause: null​play: null​rebuild: function rebuild()​updateSliderHeight: function ie()​__proto__: Object { … } categories.js:528:21

It seems like "destroy" is null for some reason - yet "rebuild" etc have functions? The only reason I noticed this is because I get an error:

> TypeError: window.VARS.slider[link_id].destroy is not a function

My main end game is that I need to change the number of columns for the slider based on the block width (of where its contained). This works when initalizing:

```
                        var items;
                        var block_width = document.getElementById("listing"+link_id).clientWidth;
                        if (block_width > 400 && block_width < 800) {
                            items = 2;
                        } else {
                            items = 3;
                        }
```

But I have no way of changing this when the browser is resized (or they go from "grid" to "list" view)

Any ideas?

Thanks!

**Comment by ganlanyuan** [comment]
May I know which version of tiny-slider you're using?

**Comment by youradds** [comment]
@ganlanyuan  I would assume its 2.6.0. For some reason my main tiny-slider.js file is minified, so I don't have the comments that would give it away :/ I ended up having to do a bit of a work around:


```
require(['tiny-slider'], function(slider){
        //alert("done")

        var items;
        var block_width = document.getElementById("listing"+link_id).clientWidth;
        var gutter = 10;
        if (block_width < 600) {
            items = 1;
            gutter = 0;
        } else if (block_width >= 601 && block_width < 900) {
            items = 2;
        } else {
            items = 3;
        }

        //console.log("Using .my-slider-" +link_id);
        //window.VARS.slider_ids.push(link_id);
        window.VARS.slider = tns({
            container: '.my-slider-'+link_id,
            items: items,
            slideBy: 'page',
            //autoplay: true,
            autoplay: false,
            nav: false,
            controls: false,
            gutter: gutter
        });
});
```


I then destroyed it using:

`window.VARS.slider.destroy();`

I then destroyed and re-init'ed it when they resized the screen (so I would work out the correct number of cols to use)

For some reason it didn't like having them inside an array with multiple instances?

**Comment by ganlanyuan** [comment]
I created a demo: https://codepen.io/ganlanyuan/pen/KemRxz?editors=1111
And It works as expected.
But I really recommend use [`responsive` option](https://github.com/ganlanyuan/tiny-slider#responsive-options) in this case.

**Comment by youradds** [comment]
Weird - not sure why mine didn't work then! I did try the responsive option, but it didn't work for me (the biggest part being that its not fixed sizes - the block it could be in is fluid, so I've got to show the correct number of slides based on the amount of space that exists on that block - not the overall page width :) 

Thanks for looking into it though

**Comment by ganlanyuan** [comment]
Okay.
If you're okay to make a demo, I can check what's wrong there.

**Comment by youradds** [comment]
Thanks. Unfortunately I'm a bit bogged down with other stuff at the moment, so won't have time to do that for a while :(

**Comment by ganlanyuan** [comment]
Okay, I see. Will close for now.
Feel free to reopen it if needed.

**Comment by grippado** [comment]
Hi @ganlanyuan and @youradds, i thinks this thread is old, but in recent usage, i have same issue, using multiples instances in page, and my resolution is create an array, like @ganlanyuan propose, the plus, is empty array previous created, before reuse sliders in the same page, in my case, I call sliders on tabs switchs, and in each tab, i have a different number os sliders!!

####  Mount array of sliders, based in number os itens selected (this implemented on vue data)
```javascript
tnsSlider: [],
defaultConfigSlider: {
    fixedWidth: 230,
    swipeAngle: false,
    mouseDrag: true,
    speed: 400,
    navPosition: 'bottom',
    controls: true,
    loop: false
}
```
####  Mount array of sliders, based in number os itens selected (this implemented on vue hook methods)
```javascript
async clearSliders() {
    if(this.tnsSlider.length > 0) {
        this.tnsSlider.forEach(slider => {
            slider.destroy()
        })
    }
},
async clearVidz() {
    await this.clearSliders()
        .then(() => {
            this.vidzSelectd = []
            this.tnsSlider = []
        })
},
async selectTab(filter) {
    await this.clearVidz()
        .then(() => {
            this.vidz.map((vid) => {
                if(vid.Livro == filter) {
                    this.vidzSelectd.push(vid)
               }
            })
        })
        .then(() => {
            this.vidzSelectdComponents = [...new Set(this.vidzSelectd.map((item) => item.CourseLabel))]
        })
        .then(() => {
            for (let i = 0; this.vidzSelectdComponents.length > i; i++) {
                this.tnsSlider.push(tns({
                     container: `.grade-list-list.index${i}`,
                     ...this.defaultConfigSlider
                }))
            }
        })
    },
}
```

and this solve all my problems =)
