### ISSUE TITLE
Autoplay stopped after nav button being clicked

### ISSUE THREAD

**Issue by Loompeek** [ganlanyuan/tiny-slider#195]
__Issue description__:  
Hello, first of all - thank you for this really nice library.

I checked the source code and realized that stopping autoplay after user interaction is intentional.
So I tried to use _play_ function to start the timer but apparently this does not work. You can see the code below.
The problem may be the fact that you have click events attached to those buttons already.

__Demo link/slider setting__:   
var slider = tns({
                container: '.tiny-slider',
                controls: false,
                autoplay: true,
                autoplayTimeout: 2500,
                autoplayButtonOutput: false
            });
            var elem = document.querySelector('.tns-nav');
            var buttons = elem.querySelectorAll('button');
            buttons.forEach(function(but) {
                but.addEventListener('click', function(e) {
                    slider.play();
                });
            });

_Tiny-slider version_:   2.6.0
_Browser name && version_:  Google Chrome 66.0.3359.170
_OS name && version_:   Windows 7

**Comment by Loompeek** [comment]
Okay, to make it work the way I need - I did some nasty thing like this:

var play_again = function(){setTimeout(slider.play, 1)}
            slider.events.on('indexChanged', play_again);

**Comment by ganlanyuan** [comment]
Yes, that's expected.
When a user clicks the controls/nav, I suppose he/she wants to manually check the slides, so I stop the autoplay. On the contrary, if the autoplay continues after the user clicks the controls/nav, he/she may find the slide he/she is watching suddenly slide away, I guess that's not he/she really wants.

**Comment by ganlanyuan** [comment]
Close for now.
Feel free to reopen it if you think differently.

**Comment by dominik-wbz** [comment]
It would be nice to have this as an option?

**Comment by Ivan-Korolenko** [comment]
This behavior should definitely be optional. Slider can stop while the user is hovering on it (if you want to avoid the described UX case), but it should not be permanent in any case.

The way slider works with autoplay and buttons right now is not right at all. It should not be default and **only** option.

**Comment by Ivan-Korolenko** [comment]
Here's an easy workaround for this issue. 

Just copy/paste it after slider initialization:
```

var buttons = document.querySelectorAll('.tns-nav button')
	buttons.forEach(function() {
		this.addEventListener('click', function(e) {
			slider.play()
		})
	})
```

**Comment by Tamakiwan** [comment]
I feel like this behavior is not consistent. While the slider stops once the user interacts with the buttons, if the option `mouseDrag` is turned on, and the user interacts with the slider that way, it doesn't stop.

Wouldn't it be better to make the "stop after interacting" behavior optional and have it affect every interaction case?

**Comment by pjrundle** [comment]
Agree with others that this behaviour should ideally be optional.

**Comment by bydex** [comment]
sliderBlock.addEventListener("mouseleave", function () {
    slider.play();
});

**Comment by olddface** [comment]
this work fine thanks!!..

**Comment by olddface** [comment]
> sliderBlock.addEventListener("mouseleave", function () { slider.play(); });

this work thanks!!
