### ISSUE TITLE
items are not enough to show on 1 page

### ISSUE THREAD

**Issue by TomasKatz** [ganlanyuan/tiny-slider#196]
__Issue description__:  

When using less then 3 items I get the following error:
items are not enough to show on 1 page

Tried setting "items" property to 1/2, didn't work

Is there any workaround.

__Demo link/slider setting__:   

_Tiny-slider version_:   
tiny-slider
@version 0.0.0
_Browser name && version_:  
Chrome
_OS name && version_:

**Comment by ganlanyuan** [comment]
May I have your slider settings? Or a demo page?

**Comment by TomasKatz** [comment]
Sorry! I was using you very very outdated example on your website. here:

https://www.cssscript.com/tiny-content-slider-with-pure-javascript/#comment-775

PLEASE! update your site to show a relevant version to prevent mis-understanding

**Comment by ganlanyuan** [comment]
`items` means how many slides will show on page, so it must be integer.
Again, please let me know your settings. Otherwise, I can't help with this issue.
