### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by TomasKatz** [ganlanyuan/tiny-slider#197]
__Issue description__:  
After installing tiny-slider using: npm install --save tiny-slider .
In my angular 5 component I do the following:
<pre>
import  {tns} from '../../../../node_modules/tiny-slider/src/tiny-slider.module.js';
</pre>
also tried the normal way:
<pre>
import  {tns} from 'tiny-slider/src/tiny-slider.module.js';
</pre>

And then running: npm run build (using webpack)
I get a compile error:
<pre>
Could not find a declaration file for module '../../../../node_modules/tiny-slider/src/tiny-slider.module.js'. 'C:/Projects/PersonalBranches/TomasK/Digital/SelfServiceWeb/node_modules/tiny-slider/src/tiny-slider.module.js' implicitly has an 'any' type.
  Try `npm install @types/../../../../node_modules/tiny-slider/src/tiny-slider.module.js` if it exists or add a new declaration (.d.ts) file containing `declare module '../../../../node_modules/tiny-slider/src/tiny-slider.module.js';`
</pre>

__Demo link/slider setting__:   

_Tiny-slider version_:   

Format: ES MODULE
Version: 2.6.0

_Browser name && version_:  
_OS name && version_:

**Comment by ganlanyuan** [comment]
Probably the path issue.
Could you try absolute path or check if the current path is currect?
