### ISSUE TITLE
[Firefox] TypeError: window.getComputedStyle(...) is null inside an iframe with display: none

### ISSUE THREAD

**Issue by O-Ami** [ganlanyuan/tiny-slider#199]
__Issue description__:  TypeError: window.getComputedStyle(...) is null inside an iframe with display: none on Firefox

__Demo link/slider setting__:   N/A

_Tiny-slider version_:   2.6.0
_Browser name && version_: Firefox 60.0.1 
_OS name && version_:  MacOS Sierra ver10.12.6

**Issue - tiny-slider.js: Ln179**
```
position = window.getComputedStyle ? window.getComputedStyle(div).position : div.currentStyle['position'];
```

Here `window.getComputedStyle(div)` returns null on Firefox when it's being used inside an iframe with `display:none`, and then the subsequent call for `position` will throw an error.

**Fix**
```
var computedStyle = window.getComputedStyle && window.getComputedStyle(element)
position = computedStyle ? computedStyle.position : div.currentStyle['position'];
```

***Related Firefox bug report***
https://bugzilla.mozilla.org/show_bug.cgi?id=548397

Console error: `TypeError: window.getComputedStyle(...) is null`

**Comment by ganlanyuan** [comment]
That's true.
Tiny-slider can't get the viewport width within the iframe when it's `display: none`. 
Maybe you can use `opacity: 0` or `visibility: hidden`.
