### ISSUE TITLE
Slider creates too many slides

### ISSUE THREAD

**Issue by m0rphee** [ganlanyuan/tiny-slider#200]
__Issue description__:  
I'm trying to integrate a slider on a website I'm creating. I have 6 slides full width that should loop.
Here is my HTML structure : 

`<div class="my-slider">

    <div id="slide1" class="slider-item">
        <div class="slider-container-text">
            <div class="slider-text">
                <div class="slider-text-title">
                    FIND YOUR NEXT ADVENTURE
                    <div class="slider-text-double-underline">
                    <div class="underline-one"></div>
                    <div class="underline-two"></div>
                </div>
                </div>
                <div class="slider-text-button">› CAMP & HIKE COLLECTION</div>
            </div>
        </div>
    </div>
  
    <div id="slide2" class="slider-item">
      <div class="slider-container-text">
          <div class="slider-text">
                <div class="slider-text-title">
                    REACH FOR THE SUMMIT
                    <div class="slider-text-double-underline">
                    <div class="underline-one"></div>
                    <div class="underline-two"></div>
                </div>
                </div>
                <div class="slider-text-button">› CLIMB COLLECTION</div>
            </div>
        </div>
    </div>
  
    <div id="slide3" class="slider-item">
        <div class="slider-container-text">
            <div class="slider-text">
                <div class="slider-text-title">
                   JUST RIDE AWAY
                    <div class="slider-text-double-underline">
                    <div class="underline-one"></div>
                    <div class="underline-two"></div>
                </div>
                </div>
                <div class="slider-text-button">› CYCLE COLLECTION</div>
            </div>
        </div>
    </div>
  
   <div id="slide4" class="slider-item">
        <div class="slider-container-text">
            <div class="slider-text">
                <div class="slider-text-title">
                   SLIDE THOSE CURVES
                    <div class="slider-text-double-underline">
                    <div class="underline-one"></div>
                    <div class="underline-two"></div>
                </div>
                </div>
                <div class="slider-text-button">› PADDLE COLLECTION</div>
            </div>
        </div>
    </div>
  
    <div id="slide5" class="slider-item">
        <div class="slider-container-text">
            <div class="slider-text">
                <div class="slider-text-title">
                   GO THE DISTANCE
                    <div class="slider-text-double-underline">
                    <div class="underline-one"></div>
                    <div class="underline-two"></div>
                </div>
                </div>
                <div class="slider-text-button">› RUN COLLECTION</div>
            </div>
        </div>
    </div>
  
    <div id="slide6" class="slider-item">
        <div class="slider-container-text">
            <div class="slider-text">
                <div class="slider-text-title">
                   GET OFF THE GROUND
                    <div class="slider-text-double-underline">
                    <div class="underline-one"></div>
                    <div class="underline-two"></div>
                </div>
                </div>
                <div class="slider-text-button">› SNOW COLLECTION</div>
            </div>
        </div>
    </div>

</div>`

Here is the JS : 

// START SLIDER
var slider = tns({
     container: '.my-slider',
     mode:'gallery',
     items: 1,
     slideBy: 'page',
     autoplay: true
});
 
  console.log("SLIDE COUNT = " + slider.getInfo().slideCount);
  console.log("SLIDE COUNT NEW = " + slider.getInfo().slideCountNew);

in the console, the first log of slideCount shows 6 which is right.
The slideCountNew shows 18, which is the number of slides I end up with... I just don't understand.
When you reach the 7th slide, and click on the dots to navigate, you don't go back to the images either, it's like it's an entirely new slider with empty screens. Please help?

__Demo link/slider setting__:   http://www.pixel-salad.com/website/crossing-outdoor/

_Tiny-slider version_:   2.6.0
_Browser name && version_:  Opera 53.0
_OS name && version_:   Windows 7

**Comment by ganlanyuan** [comment]
I'm working on a new release which will greatly reduce the clone slides, also bring `loop: false` to `gallery` mode.
This release will be available soon after some small issues been fixed.

**Comment by ganlanyuan** [comment]
Should be fixed in v2.7.0
