### ISSUE TITLE
Broken clone computation

### ISSUE THREAD

**Issue by pascalporedda** [ganlanyuan/tiny-slider#201]
The slider does not seem to work (at all) in its basic form, proven by the provided JSFiddle.

Verify here:  https://jsfiddle.net/Lsgbjke2/1/

Has to do with the following commit 10 days ago: https://github.com/ganlanyuan/tiny-slider/commit/2f57e8fb3390de450afc94fe4d73cc03633e04d7

When disabling the loop, it is working fine as the clone computation is resulting in -Infinity.

Tiny-slider version: 2.7.0
Browser name && version: Google Chrome ( 67.0.3396.62)  
OS name && version: MacOS 10.13.4

**Comment by ganlanyuan** [comment]
Fixed in v2.7.1
