### ISSUE TITLE
Z.scrollLeft is not a function

### ISSUE THREAD

**Issue by danny7i** [ganlanyuan/tiny-slider#202]
__Issue description__:  

We are getting some js errors from our bug tracker for this error:

`node_modules/tiny-slider/src/tiny-slider.module.js:2042`

![image](https://user-images.githubusercontent.com/1275768/41161217-052a7d92-6b2a-11e8-9250-3aa46528bb98.png)

It looks like this function will only be executed in IE but our users having this issue are mostly on Safari.

_Tiny-slider version_:   2.6.0
_Browser name && version_:   
	
9 occurrences: Mobile Safari (iOS 11.3, 10.3)
1 occurrences: Chrome Mobile iOS 66 (iOS 11.3)

**Comment by ganlanyuan** [comment]
@danny7i Thanks. 
`scrollLeft()` should be `scrollLeft`, just fix this.
But I couldn't reproduce this issue on iOS10/11.
Could you let me know your slider options?

**Comment by danny7i** [comment]
Sure, it's something like this


{
					container: /*a <ul/>*/,
					mouseDrag: true,
					controls: false,
					autoplay: false,
					autoplayButton: false,
					autoplayHoverPause: true,
					autoplayResetOnVisibility: true,
					navContainer: /*another <ul/>*/,
}

**Comment by ganlanyuan** [comment]
Still couldn't reproduce this issue.
Could you update to the latest version and check it again?

**Comment by danny7i** [comment]
@ganlanyuan Updated and the issue seems to have gone. Thanks
