### ISSUE TITLE
Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by danny7i** [ganlanyuan/tiny-slider#203]
__Issue description__:  

When directly accessing localStorage object in Safari where the user has opted to disable all cookies, they will get this error `The operation is insecure.`

![image](https://user-images.githubusercontent.com/1275768/41162183-0f265944-6b2d-11e8-830e-c3a4c2894af1.png)

Or if they are on Chrome they will get `Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

This is related to #134, but unlike it this happens under different conditions (cookies disabled).

A potential solution would be to wrap ANY reference to window.localStorage inside a try...catch block, as merely reading from it will also trigger the error.

_Tiny-slider version_:   2.6.0
_Browser name && version_: Safari (desktop and mobile), Chrome (mostly Mobile)  and Amazon Silk
_OS name && version_:   iOS, Android

**Comment by ganlanyuan** [comment]
This was fixed in v2.7.0+
