### ISSUE TITLE
The value of absIndexMin in getVisibleNavIndex is not correctly calculated.

### ISSUE THREAD

**Issue by VladimirSchneider** [ganlanyuan/tiny-slider#204]
__Issue description__:  
The value of absIndexMin in getVisibleNavIndex is not correctly calculated.

__Demo link/slider setting__:   
http://crazycoolsite.com/mga/reviews.html

```javascript
tns({
  container: '.reviews-slider__slides',
  items: 2,
  gutter: 50,
  controls: false,
  navContainer: '.reviews-slider .slider-nav'
});
```

_Tiny-slider version_:   last version
_Browser name && version_:  all browsers
_OS name && version_:   Mac OS

**Comment by ganlanyuan** [comment]
May I know the details?

**Comment by VladimirSchneider** [comment]
Yes. On the page in the working slider there should be three items of navigation, and the slider makes two items of navigation. Try the buttons left and right and pay attention to the navigation items. The first and second are good, but the third navigation disabled. Then the cycle begins from the first.

**Comment by ganlanyuan** [comment]
Hi, that's right.
As I checked, you have 3 items originally. The dots work as "slide by page". So "3 slides" = "2 pages". That's why only 2 dots will show.

**Comment by VladimirSchneider** [comment]
Okay, Thanks for the answer. Pay attention to the navigation elements. It's wrong behavior. The second element has two slides. Can I fix this?

**Comment by ganlanyuan** [comment]
You can try loop: false

**Comment by ganlanyuan** [comment]
You can use "navAsThumbnails: true" and no need to set "loop: false"

**Comment by VladimirSchneider** [comment]
Many thanks!
