### ISSUE TITLE
Slider getting width of 600%

### ISSUE THREAD

**Issue by Danyx1980** [ganlanyuan/tiny-slider#205]
__Issue description__:  When initializing a Tiny Slider the div gets a style of width: 600% applied to it. 

__Demo link/slider setting__:   ```
slider = tns({
                    container: '#cumpleanos',
                    autoplay: true,
                    slideBy: 'page',
                    autoplayTimeout: 3500,
                    speed: 750,
                    autoplayButton: false,
                    nav: false,
                    autoplayButtonOutput: false,
                    controls: false
                });
```

_Tiny-slider version_:   latest
_Browser name && version_:  
_OS name && version_:

**Comment by ganlanyuan** [comment]
That's expected.

**Comment by Danyx1980** [comment]
Is there a way to make it so it doesn't break the DOM? I currently have 2 sliders on my page, one seems to be working fine with some CSS applied to it but the second one is still expanding even with the same classes applied to it.

**Comment by ganlanyuan** [comment]
I didn't get the idea.
Could you make a demo?
