### ISSUE TITLE
Incorrect active bullet in nav in gallery mode

### ISSUE THREAD

**Issue by malvese** [ganlanyuan/tiny-slider#206]
__Issue description__:  When I use `gallery` mode, the first slide is at the last position. Other slides are then in the right order but shifted: slide 2 is first, slide 3 is second, etc. I didn't set `
startIndex`, so that is not the issue.

<img width="388" alt="gallery" src="https://user-images.githubusercontent.com/193492/41414300-f00af962-6fe5-11e8-9cde-4f8d4d053946.png">

Before I upgraded to this latest version I used an older one (probably 2.2.4, sorry I'm not sure exactly) and didn't have this issue.
`carousel` mode doesn't have the issue.

_Tiny-slider version_:   2.7.1
_Browser name && version_:  Chrome 66
_OS name && version_:   macOS High Sierra 10.13.4

**Comment by ganlanyuan** [comment]
https://codepen.io/ganlanyuan/pen/BVdmxZ?editors=1111
I made a demo for this and it seems doesn't have this issue.

**Comment by malvese** [comment]
I'm sorry, the description was imprecise:
- My slider has a single visible slide (`items: 1`)
- The slides are indeed in the correct order, no issue here, what is wrong is the bullets order in the nav. 

Here's a Pen with my settings and CSS to make the active bullet visible:
https://codepen.io/malvese/pen/XYaqrL?editors=1111

I both my demo and yours the active bullet is shifted by one.

**Comment by ganlanyuan** [comment]
Fixed in v2.7.2

**Comment by cj** [comment]
@ganlanyuan in 2.7.2 I'm still running into this issue when I run `#rebuild`.

**Comment by ganlanyuan** [comment]
@cj Could you make a demo?

**Comment by cj** [comment]
@ganlanyuan sure, no problem.  I just used @malvese one, changed it to 2.7.2 and added rebuild. https://codepen.io/cj/pen/KeoKrV?editors=1111 it's actually re-rending the controls too.

**Comment by ganlanyuan** [comment]
You should `destory()` it before rebuild
