### ISSUE TITLE
Slider creates extra elements

### ISSUE THREAD

**Issue by RaulVS14** [ganlanyuan/tiny-slider#207]
__Issue description__:  
When there aren't enough elements, some elements are repeated
__Demo link/slider setting__:   
https://codepen.io/anon/pen/JZypYO
_Tiny-slider version_:   tiny-slider 2.0
_Browser name && version_:  Chrome Version 67.0.3396.79
_OS name && version_:  Linux Ubuntu 16.04

**Comment by ganlanyuan** [comment]
The default `loop` option is set to `true` which needs more slides to make a loop.
You can set `loop: false` if you don't want this.
