### ISSUE TITLE
edgepadding with fixedwidth

### ISSUE THREAD

**Issue by jorgepcbraz** [ganlanyuan/tiny-slider#210]
I am having a problem with fixedWidth and edgepadding options.
The padding is only applied after a window resize event.

This is also happening on the demo page also (see example Fixedwidth-edgepadding, http://ganlanyuan.github.io/tiny-slider/tests/index.html).

**Comment by ganlanyuan** [comment]
Thanks, fixed in v2.7.3

**Comment by jorgepcbraz** [comment]
wow @ganlanyuan this was a fast reply.
thank you.

**Comment by ganlanyuan** [comment]
You're welcome
