### ISSUE TITLE
Nav item scroll with Slide?

### ISSUE THREAD

**Issue by notrealdev** [ganlanyuan/tiny-slider#212]
Hi, this slide have option Nav_Item scroll with Slide like http://kenwheeler.github.io/slick/
with `Slider Syncing` feature?
I have many thumbnail image,i want the active thumbnail always show the first, what i have to do to get it?

My code: https://codepen.io/notrealdev/pen/dKdQNJ

**Comment by ganlanyuan** [comment]
You probably need 2 sliders: one for the slider itself, one for the thumbnails.
And then the two can share the same prev/next buttons to make them sync.

**Comment by ganlanyuan** [comment]
There are `dragStart`, `dragMove` and `dragEnd` events, although it's not in the document. (I will update this soon) So you can sync the `index` of the two sliders on `dragEnd`.
