### ISSUE TITLE
Slider not initialized: Error Can't find .sarafan-tns-nav

### ISSUE THREAD

**Issue by v-lukoyanov** [ganlanyuan/tiny-slider#213]
__Issue description__:  
If there are options:
```javascript
{
// ....
controlsContainer: '.sarafan-tns-controls',
navContainer: ".sarafan-tns-nav"
}
```
then slider throws this error: Can't find .sarafan-tns-nav 
OR Can't find .sarafan-tns-controls

If I try to hide this options then slider works very bad, and buttons(NEXT AND PREV) become not active or wrong work.

__Demo link/slider setting__:   
```javascript
var slider = tns({
            mode: 'gallery',
            container: '.my-container',
            // fixedWidth: 140,
            slideBy: 'page', // TODO test it
            gutter: 0,
            edgePadding: 0,
            controlsText: ['', ''],
            // autoplay: true,
            autoHeight: true,
            loop: true,
            items: ( offersArr.length < 4 ) ? offersArr.length : 4, // default number of items
            responsive: {
                0:{
                    items: 1
                },
                350:{
                    items: ( offersArr.length < 2 ) ? offersArr.length : 2
                },
                600:{
                    items: ( offersArr.length < 3 ) ? offersArr.length : 3
                },
                760:{
                    items: ( offersArr.length < 4 ) ? offersArr.length : 4
                }
            },
            controlsContainer: '.sarafan-tns-controls',
            navContainer: ".sarafan-tns-nav"
        });
```

_Tiny-slider version_:   2.7.3
_Browser name && version_:  Chrome latest
_OS name && version_:   Ubuntu latest stable

**Comment by ganlanyuan** [comment]
The first issue probably is: .sarafan-tns-controls and/or .sarafan-tns-nav don't exist when the slider runs.

**Comment by v-lukoyanov** [comment]
@ganlanyuan 
I already tried to make so.
But there are any problems.
Script does not know quantity of points(dots).
Info from documentation not clear for me how to make this two blocks ( .sarafan-tns-controls and .sarafan-tns-nav). In result div's remain with empty inner HTML.

**Comment by ganlanyuan** [comment]
https://codepen.io/ganlanyuan/pen/mKLvJd
Hi, I can make it with your options.

**Comment by ganlanyuan** [comment]
These two options are for customizing controls and nav, so you should put your own code inside.

**Comment by v-lukoyanov** [comment]
Yeah, works. Thank you vary much!
