### ISSUE TITLE
null is not an object (evaluating 'W.tC') / Cannot read property 'tC' of null

### ISSUE THREAD

**Issue by danny7i** [ganlanyuan/tiny-slider#215]
__Issue description__:   

In Chrome/Safari, sometimes users will get error when evaluating this line:

![image](https://user-images.githubusercontent.com/1275768/41839447-2d7545fa-785b-11e8-8f25-72f6421647f1.png)

It most likely happened under the same conditions as #203, where the users have opted to disable all cookies/localStorage. I could be wrong, but it does look like a small number of users are getting this error, about the same proportion of users who got hit by #203. 

_Tiny-slider version_:   2.7.2
_Browser name && version_: Chrome/Safari (mobile and desktop) 
_OS name && version_:   iOS, Android, MAC OSX

**Comment by ganlanyuan** [comment]
Should be fixed in v2.7.4

**Comment by danny7i** [comment]
Hi, I will have a look. Thanks!

**Comment by ganlanyuan** [comment]
Feel free to reopen it if the issue appears again
