### ISSUE TITLE
Fractional number of slides

### ISSUE THREAD

**Issue by norin89** [ganlanyuan/tiny-slider#217]
__Issue description__:  
**It's a feature request.** It would be nice to be able to display fractional number of slides - for example 2.5 slide per view. It's good indicator to show that there're more slides to scroll. `edgePadding` or `fixedWidth` for slides can do similar job but not exactly what could be achieved with fractional number of slides.

It partially works out of the box but there are some quirks and few `console.error`s.

__Demo link/slider setting__:   
https://jsfiddle.net/norin89/jhfL82ey/1/

_Tiny-slider version_:  2.7.3
_Browser name && version_:  any
_OS name && version_:  any

**Comment by ganlanyuan** [comment]
It's impossible for me since `index` can't be floating-point number.
But you can use 2 extra div and a little styles to achieve this:
https://jsfiddle.net/ganlanyuan/n149j3ms/6/

**Comment by norin89** [comment]
I achieved it similar way. The problem is that I have multiple sliders on my page and only some needs fractional number of slides. That requires pretty much additional CSS as percentage side padding requires different values depending on slides count.

Correct me if I'm wrong but with fractional number of slides the index for each slide would still be integer. Isn't that only some issue with rounding the number down? E.g. if we have 3.5 slide per view it would return index 4.5 for the first item of next screen. If we round that down it would return 4, which is ID for element that was partially visible on first screen.

**Comment by ganlanyuan** [comment]
This feature was added in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/da5fb99c78b7fe579becd0b904db5718223ebfd0).

**Comment by norin89** [comment]
@ganlanyuan oh wow! That's awesome :)

**Comment by ganlanyuan** [comment]
Added in v2.8.0

**Comment by paulmz** [comment]
I know this conversation is WAY old, but how is this implemented? I've been using Tiny Slider for many, many years and the only way I've been able to show a partial slide is to set responsive items as something like: {0:{items:2.2},675:{items:3.2},1125:{items:4.2},1575:{items:5.2}.

![Image](https://github.com/user-attachments/assets/a79a43f4-87a8-4a25-a0a4-1b67a51cc964)

It works at the start of the slideshow but when getting to the end there are is space after the last slide.

![Image](https://github.com/user-attachments/assets/964287fa-f83a-41bd-8fc1-600e51c4021d)

Am I going about this the right way?
