### ISSUE TITLE
issue with prevButton / nextButton when freezable: true

### ISSUE THREAD

**Issue by vrealjohn** [ganlanyuan/tiny-slider#218]
__Issue description__:  When you set values for prevButton + nextButton, controls: true, controlsContainer: false, and leave freezable: true I get an exception at the following line:

```if (!controls) { hideElement(controlsContainer); }```

It appears that freeze changes the values of the controls variable to false, even though I set it to true on initialization, which makes sense if this is used to hide the controls.  Since controls is now false it then attempts to hide a non-existent controlsContainer.  I expect this should be something along the lines of ```if (!controls && controlsContainer)``` to ensure a container exists before trying to hide it.

Love the lib, thanks for creating it!

_Tiny-slider version_:   2.7.3

**Comment by ganlanyuan** [comment]
Did you mean something like this?
https://codepen.io/ganlanyuan/pen/eKLqQN

**Comment by vrealjohn** [comment]
Ahhh, I think my issue was using controls: true while also specifying prevButton / nextButton is problematic.  controls: false seemed to have solved that, thank you!  closing.
