### ISSUE TITLE
Touch is not working with gallery mode

### ISSUE THREAD

**Issue by lbineau** [ganlanyuan/tiny-slider#219]
__Issue description__:  
Touch for mobile isn't working when the carousel is set to mode: 'gallery'

__Demo link/slider setting__:   

_Tiny-slider version_:  2.7.3
_Browser name && version_: safari and Chrome simulato but I guess any touch device
_OS name && version_: Tested on iOS 11 / Mac OS X but I guess any touch device

**Comment by ganlanyuan** [comment]
That's right. `touch/drag` is blocked in `gallery` mode.
It's not finalized how the slider will respond to `touch/drag` actions for `gallery`, so it may take some time to add this feature.

**Comment by ganlanyuan** [comment]
Hi, `touch/mouseDrag` was added back in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/dacae808427783a650c101ee34714950608ceddf).

**Comment by willianjusten** [comment]
Hey, do you know when this fix will get released? Thanks =)

**Comment by ganlanyuan** [comment]
Probably end of this week or early next week.

**Comment by DonthaSuman** [comment]
I'm using the latest version **2.7.4**, having problems with swiping on touch devices. Nav and dots seem to work, but when I swipe it doesn't work (also does not lazy load images, or update dots/active state). Tested on IOS11 / iPhone6 / Safari / all mobiles / chrome. Please have a look at it asap.

**Comment by ganlanyuan** [comment]
Hey @DonthaSuman , swipe for `gallery` mode is not been released yet.
If you have issues with v2.7.4, please open another ticket.

**Comment by ganlanyuan** [comment]
This issue should be fixed in v2.8.0
