### ISSUE TITLE
Does 'initialized' custom event work?

### ISSUE THREAD

**Issue by WhereJuly** [ganlanyuan/tiny-slider#22]
Hello William,

Thanks for the great code and functionality :)

Some questions here. I try to use the `initialized` event but it does not fire. At the same time `indexChanged` event fires fine.

Can you kindly check what could be the issue? Here is my code:

``` javascript
        var slider3 = tns({
            container: document.querySelector('.slider-feedback'),
            axis: 'vertical',
            speed: 1600,
            items: 3,
            slideBy: 1,
            autoplay: true,
            gutter: 20,
            controlsContainer: document.querySelector('.wj-tns-controls.controls-feedback'),
            navContainer: document.querySelector('.wj-tns-thumbnails'),
        });

        // Attach the handler
        slider3.events.on('initialized', clearHiddenAttrib);

        // 
        function clearHiddenAttrib() {
            console.info('Clear hidden attribute function worked...');
        }
```

As I run this no `initialized` event fires.

If it matters:
- I use tns-slider.js just concatenating into my RequireJS Optimizer bundle.
- I use other 2 instances of tns slider on the same page calling them like this:
``` javascript
var slider = tns({
            container: document.querySelector('.slider-one'),
           // other settings
})
var slider2 = tns({
            container: document.querySelector('.slider-schedule-prices'),
            // other settings
})
```

Thanks for the help.

Regards,
Val

**Comment by ganlanyuan** [comment]
Hi,
That's expected. Because when you can `tns(...)`, it's initialized already. It will not fire again.
A work around for this is to watch the initial event before the initiation.
```
tns().events.on('initialized', function(info) {
  console.log(info.container.id);
});

var slider3 = tns({
  container: document.querySelector('.slider-feedback'),
  axis: 'vertical',
  speed: 1600,
  items: 3,
  slideBy: 1,
  autoplay: true,
  gutter: 20,
  controlsContainer: document.querySelector('.wj-tns-controls.controls-feedback'),
  navContainer: document.querySelector('.wj-tns-thumbnails'),
});
```

**Comment by WhereJuly** [comment]
Clear now. Thank you.
Another specific question as follows. I have several `tns` sliders in my page. I attach the hadler for e.g. `transitionEnd` like this:
``` javascript
    slider3.events.on('transitionEnd', clearHiddenAttrib);
```
... and I assume the handler to be called on `slider3` instance's `transitionEnd` event only.

However the event handler is called on all `transitionEnd` events emitted by all the instances of `tns`. What could be the right way of doing things with `tns` in this case? Like filter out the name of the required slider within the handler?
Thanks.

**Comment by ganlanyuan** [comment]
Yes, I noticed this issue. Will looking on it shortly.
For now you can do with the method you mentioned (Like filter out the name of the required slider within the handler?)
```javascript
slider3.events.on('transitionEnd', function(info) {
  if (info.container.id === 'base') {
    console.log(e.type, info.container.id);
  }
});
```

**Comment by ganlanyuan** [comment]
Hey,
Just submit a [new release](https://github.com/ganlanyuan/tiny-slider/tree/v1.2.0) to fix this issue. 
The `tns()` instances no longer sharing the same `event`. Also you can now use `onInit` fallback instead of `initialized` event, more on [here](https://github.com/ganlanyuan/tiny-slider#custom-events).
Please check it out and let me know if it works for you.

**Comment by ganlanyuan** [comment]
Close for now.

**Comment by WhereJuly** [comment]
Hi William. I tested a little. These two changes work fine. Quite a convinient addition. Thanks a lot.

**Comment by ganlanyuan** [comment]
Thanks for the feedback. Glad to see that.
