### ISSUE TITLE
Slider disappears on resize

### ISSUE THREAD

**Issue by amateur** [ganlanyuan/tiny-slider#228]
__Issue description__:  

Slider disappears while switching breakpoints if we use the `responsive` option.

__Demo link/slider setting__:   
[Demo](https://codepen.io/vuzhaka/pen/VBwxbe)

_Tiny-slider version_:  2.8.0 
_Browser name && version_:  Chrome 67.0.3396.99

**Comment by ganlanyuan** [comment]
Thanks!
Should be fixed in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/d6f64bc23cfc0b179f891f0e874aa7586260129d).

**Comment by ganlanyuan** [comment]
v2.8.1 was released
