### ISSUE TITLE
Custom controls, with no custom nav, gives "TypeError: undefined is not an object"

### ISSUE THREAD

**Issue by jsit** [ganlanyuan/tiny-slider#23]
A fairly simple CodePen:

http://codepen.io/jsit/pen/XMKzwr

```javascript
var slider = tns({
    container: document.querySelector('.slider'),
    controlsContainer: document.querySelector('.controls'),
});
```

```html
<div class="wrapper">
  <div class="slider">
    <img src="http://unsplash.it/600/200">
    <img src="http://unsplash.it/600/200">
    <img src="http://unsplash.it/600/200">
    <img src="http://unsplash.it/600/200">
  </div>
</div>

<!-- customized nav & dots -->
<div class="controls">
  <button>prev</button>
  <button>next</button>
</div>
<!-- Uncomment .thumbnails and it will work -->
<!--
<div class="thumbnails">
  <button></button>
  <button></button>
  <button></button>
  <button></button>
  <button>stop</button>
</div>
-->
```

Gives me the error "TypeError: undefined is not an object".

If I uncomment the `.thumbnails` div, it suddenly works.

It doesn't matter what the class is on the `.thumbnails` div, but it does require that there are at least as many child elements inside it as there are slides in the slider.

Also happens if you simply set `controls: false`.

**Comment by jsit** [comment]
Having a similar problem with `controlContainer`.

**Comment by jsit** [comment]
Sample CodePen: http://codepen.io/jsit/pen/XMKzwr

**Comment by ganlanyuan** [comment]
I will look into it tmr or next Monday

**Comment by ganlanyuan** [comment]
Hey,
Just fixed an issue on selecting `controlsContainer`, could you check it again?

BTY, seems using https://raw.githubusercontent.com/ganlanyuan/tiny-slider/master/dist/tiny-slider.js don't work for me on codepen, I made a copy with inline styles and scripts. 
http://codepen.io/ganlanyuan/pen/bqexjZ

**Comment by jsit** [comment]
Seems to work fine now, thanks!
