### ISSUE TITLE
goTo method off by minus one

### ISSUE THREAD

**Issue by matthewmcclatchie** [ganlanyuan/tiny-slider#230]
__Issue description__: 
Using the `goTo()` method attached to a custom element was selecting the wrong slide in the carousel. It was consistently displaying previous slide to the one selected.

If I clicked an element that fired `goTo(2)` for example, the carousel would display the slide at index `1` instead of index `2`.

My `package.json` file was set to `"tiny-slider": "^2.6.0"`. My build tool appeared to be downloading the most recent version of tiny-slider (2.8.1) whereas my local version was using 2.6.0. We noticed the issue pretty much exactly after version 2.8.0 was released.

When I removed the `^` from my package.json, in order to force the download of version of `2.6.0`, the `goTo()` method starting working as expected.

Can't provide a link to demo as it's on a private development site at the moment, but can provide more details if required. 

__Demo link/slider setting__:  
```
this.carousel = tns({
  container: '.product__gallery-main',
  items: 1,
  autoplay: false,
  controlsContainer: ".product__gallery-controls",
  navContainer: ".product__gallery-thumbs-slider",
  navAsThumbnails: true,
  loop: false,
});
```

_Tiny-slider version_: ^2.6.0 - Issue was noticed around time version 2.8.0 was released
_Browser name && version_: Chrome 67 
_OS name && version_: Mac OS Sierra 10.12.6

**Comment by ganlanyuan** [comment]
The number in `goTo()` was 1 based from v2.8.0.
So `goTo(2)` should just display the second slide.
https://codepen.io/ganlanyuan/pen/bjVWRL

**Comment by matthewmcclatchie** [comment]
Thanks @ganlanyuan, I wasn't aware of this change and missed the note in the readme.

**Comment by ganlanyuan** [comment]
Sorry for the unexpected change.
I will do my best to keep the features consistent within the main version, but for `goTo()`, I just want to use natural index to avoid the complexity due to cloned slides.

**Comment by ganlanyuan** [comment]
Sorry again.
To keep the consistency and also match `startIndex`, I think the `index` in `goTo()` still need to be 0 based. I will fixed this issue in the next release.

**Comment by matthewmcclatchie** [comment]
Sounds good to me. I'll keep an eye out for the next release.

**Comment by ganlanyuan** [comment]
v2.8.2 was released
