### ISSUE TITLE
src/tiny-slider.module.js is missing

### ISSUE THREAD

**Issue by ashhitch** [ganlanyuan/tiny-slider#231]
__Issue description__:  
src/tiny-slider.module.js Is missing in v2.8.1 is this version, which is the file I was importing in my TypeScript project.

Is this suppose to be the case?

_Tiny-slider version_:  2.8.1

**Comment by ganlanyuan** [comment]
Yes.
Use `tiny-slider.js` instead, they are almost the same.
Sorry for the confusion.

**Comment by deyhle** [comment]
It should be a major release then, to be compliant with SemVer. This way, npm auto-updated tiny-slider and everything broke because of this breaking change.

**Comment by ganlanyuan** [comment]
@deyhle Right, sorry for the inconvenience.

**Comment by ganlanyuan** [comment]
The file was added back in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/bfdb9fd97f79b71404142792c9cf88a2182558b6).
