### ISSUE TITLE
Animation in/out classes are not added

### ISSUE THREAD

**Issue by oleggromov** [ganlanyuan/tiny-slider#232]
__Issue description__:  
Hey, I'm having an issue with animation classes not being added. Please take a look at the jsfiddle attached.

__Demo link/slider setting__:   
https://jsfiddle.net/0ng6ty1e/8/

_Tiny-slider version_:  2.8.1
_Browser name && version_:  Google Chrome / Version 67.0.3396.99 (Official Build) (64-bit)
_OS name && version_:   MacOS 10.13.5

**Comment by ganlanyuan** [comment]
Animation classes was designed for `gallery` only.
For `carousel`, you can add your styles using class `.tns-slide-active`.
I will update the README to make it clear.

**Comment by oleggromov** [comment]
Thanks, got it. What I really tried to achieve is to have custom _initial_ animation that happens after slider initialization. I don't expect `tiny-slider` to handle this for me but maybe there is a way of disabling the animation? That's why I tried to use these classes and found that they don't work.

**Comment by ganlanyuan** [comment]
For this, you can use `onInit()`:
```javascript
var slider = tns({
  your: options,
  onInit: function(info){
    info.slideItems[info.index].classList.add('in');
  }
});
```

**Comment by nickolasjadams** [comment]
@ganlanyuan 
> Animation classes was designed for gallery only.
> For carousel, you can add your styles using class .tns-slide-active.
> I will update the README to make it clear.tns-slide-active

Did this get updated in the documentation? I can't find a reference to it anywhere?
