### ISSUE TITLE
unnecessary dependencies in package.json

### ISSUE THREAD

**Issue by ukabuer** [ganlanyuan/tiny-slider#233]
__Issue description__:  
When using `npm` to install `tiny-slider` in my project, it's dependencies like `nodemon` were installed as well, but it seems tiny-slider can work without these packages...

I think changing `dependencies` to `devDependencies` might be better for `npm` users.

[package.json](https://github.com/ganlanyuan/tiny-slider/blob/3dff86a235e37c6d8d87e7219b538be44ca872be/package.json#L24)

__Demo link/slider setting__:   

_Tiny-slider version_:   v2.8.1
_Browser name && version_:  
_OS name && version_:

**Comment by ganlanyuan** [comment]
Thanks, will update this
