### ISSUE TITLE
Responsive option doesn't work

### ISSUE THREAD

**Issue by dra1n** [ganlanyuan/tiny-slider#234]
__Issue description__:  
Responsive option works incorrectly

__Demo link/slider setting__:   
https://jsfiddle.net/dra1n/w136t9Lk/

_Tiny-slider version_:
2.8.2

_Browser name && version_:
Any

_OS name && version_:
Any

Mainly because of this check inside `getOption`:

```
if (viewport >= bp) {
   if (item in responsive[bp]) { result = responsive[bp][item]; }
}
```
`for` `of` converts keys to string and `"320"` is greater than `"1024"`.

**Comment by ganlanyuan** [comment]
You demo works properly for me.

**Comment by dra1n** [comment]
For any resolution between 320px and 1024px it should take settings from `320` option, so we should see 1 item (for example on 640px ). At least that was the old behavior.
Here is 2.8.1, works correctly https://jsfiddle.net/dra1n/g3v4c5fz/

**Comment by dra1n** [comment]
@opr Yes, that's because lexical order is used here to compare numbers. "999" is greater than "320", but "1000" is not.

**Comment by martincapek** [comment]
I tested it out and you have to parseInt bp variable.

```
if (viewport >= parseInt(bp)) {
 if (item in responsive[bp]) { result = responsive[bp][item]; }
}
```

Then it works properly.

**Comment by ganlanyuan** [comment]
Thanks guys, should be fixed in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/41b1dfbe035c152c532d638581dc2d8f3f2370a7)

**Comment by ganlanyuan** [comment]
v2.8.3 was published, will close this
