### ISSUE TITLE
Is there a way to make autoheight transition before slide transition, not after?

### ISSUE THREAD

**Issue by alexr8** [ganlanyuan/tiny-slider#235]
__Issue description__:  
The autoheight animation happens after the slide has finished it's transition. In gallery mode this is particularly noticeable, as an image gets revealed, overlaying other content (potentially 'breaking' a design), before .tns-inner updates its height. 

Is there a way i can make it so that, when a slide transition is triggered, it either updates the height simultaneously, or updates height *before* the slide transitions?

_Tiny-slider version_:   2.0

**Comment by ganlanyuan** [comment]
I will look at this recently.

**Comment by ganlanyuan** [comment]
Updated in [this commit], will be shipped in next release.

**Comment by alexr8** [comment]
Amazing - quick turnaround! Thank you 👍

**Comment by GNikola** [comment]
Maybe also an option for autoHeight not to be affected by the speed duration

**Comment by ganlanyuan** [comment]
@GNikola You can always reset the duration with CSS.

**Comment by ganlanyuan** [comment]
v2.8.3 was published
