### ISSUE TITLE
Left margin on loop:false

### ISSUE THREAD

**Issue by floflock** [ganlanyuan/tiny-slider#236]
__Issue description__:  

This is my config:

```javascript
const slider = tns({
  container: '.my-slider',
  items: 1,
  controls: false,
  nav: false,
  loop: false,
  edgePadding: 20,
  slideBy: 'page',
  gutter: 10,
  responsive: {
    //480: {},
    840: {
      items: 3,
      edgePadding: 0,
    },
  },
})
```

If ```loop: false``` is set, the left margin still appears. I think, the very first slide should start without margin to the left side.

![image](https://user-images.githubusercontent.com/3831745/42938233-dd642afe-8b51-11e8-99f3-25004deacdbe.png)

![image](https://user-images.githubusercontent.com/3831745/42938213-cf45b03c-8b51-11e8-9b36-750c05850429.png)

_Tiny-slider version_:  2.8.2
_Browser name && version_:  Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
_OS name && version_:  macOS High Sierra 10.13.5

**Comment by ganlanyuan** [comment]
You could simply set `edgePadding: 0` regardless of `loop`.

**Comment by florianflock** [comment]
This is not exactly what I wanted, because you should see the edgePadding to the right side. It is useful for users to know, that another item is following in the slider.

**Comment by florianflock** [comment]
For the initial view, I only want the right edgePadding, after first slide, it should be left and right.

I know, sounds special, but I think this has logic because of indicating the first element after loading.

This should be the first view (UX indicates, that is the beginning of a slider):
![image](https://user-images.githubusercontent.com/3831745/42997976-e3a95ef8-8c18-11e8-9f26-3f004151513a.png)


This should be the view of a element in the middle:
![image](https://user-images.githubusercontent.com/3831745/42997928-b76490a6-8c18-11e8-88a0-c08dcfa48ff2.png)

**Comment by ganlanyuan** [comment]
It feels unexpected for me right now.
Let me consider this a little more.

**Comment by ganlanyuan** [comment]
Hi,
I tried 2 ways to achieve this, but they both have issues.
![test](https://s19.postimg.cc/yn58lpa2r/Artboard_2.png)

1. Move the slides to the left edge, then the padding on the right changes.
2. Remove the left padding of the slider wrapper, then the slides height changes.

Let me know if you have better ideas.
Thanks

**Comment by ganlanyuan** [comment]
But it does make sense for `autoWidth`, `fixedWidth` to use method 1.

**Comment by rameshguthulakkd** [comment]
Recently installed the tiny-slider v2.9.2, and having padding on the left side of the slide and the same padding is increasing 2 or 3 px for each slide and the last slide is almost starting from the middle of the screen. Please help me resolve this issue

**Comment by ridwanzal** [comment]
I have the same issue, on tiny-slider v2.9.4 when adjust the image height to auto, the tns-carousel doesn't calculate right, there is extra space left on the carousel container.

**Comment by petrtichy** [comment]
> For the initial view, I only want the right edgePadding, after first slide, it should be left and right.
> 
> I know, sounds special, but I think this has logic because of indicating the first element after loading.
> 
> This should be the first view (UX indicates, that is the beginning of a slider): ![image](https://user-images.githubusercontent.com/3831745/42997976-e3a95ef8-8c18-11e8-9f26-3f004151513a.png)
> 
> This should be the view of a element in the middle: ![image](https://user-images.githubusercontent.com/3831745/42997928-b76490a6-8c18-11e8-88a0-c08dcfa48ff2.png)

Based on: 
https://github.com/ganlanyuan/tiny-slider/issues/97#issuecomment-349088600
_Removed left edgePadding when loop: false from v2.3.8_ 

Setting `loop: false` does not remove the left edgePadding, but it definitely should as there are no slides before the first one. IMO should be the same if is set `rewind: true`.

`gutter: 24,
            edgePadding: 48,`

`#tns3-iw {
  margin: 0px 24px 0px 48px;
}` 

but it should be 

`#tns3-iw {
  margin: 0px 24px;
}`
