### ISSUE TITLE
no transition at end of loop

### ISSUE THREAD

**Issue by noideawhatimdoin** [ganlanyuan/tiny-slider#237]
Thanks for your slider! 

__Issue description__:
Using a slider with the loop setting enabled - click the next/prev buttons, the slider will eventually reset to the original position when it nears the end index - though when this happens it doesn't animate/transition. 

Steps: 
1. create defualt slider with loop enabled
2. click prev or next until the slider jumps without animating

(I can see that the event transitionStart isn't being triggered in this situation, only the indexChanged event is - if this helps).

__Demo link/slider setting__:   
https://codepen.io/noideawhatimdoing/pen/GBNQPa

_Tiny-slider version_:   
2.8.2
_Browser name && version_:  
Chome: Version 67.0.3396.99
Safari: Version 11.1.1 (11605.2.8)

_OS name && version_:   
OSX El capitan, version 10.11.6

**Comment by ganlanyuan** [comment]
Seems you didn't include tiny-slider.css in your demo.
Make sure you do that first.

**Comment by noideawhatimdoin** [comment]
Apologies - i've added it but the issue persists

**Comment by ganlanyuan** [comment]
Try to remove the style `.my-slider li { float: left; }` then the issue should be disappeared.

**Comment by noideawhatimdoin** [comment]
perfect - thank you very much for your help and quick response :)
