### ISSUE TITLE
Not Working in safari(5.1.7) in windows OS

### ISSUE THREAD

**Issue by jineshjp** [ganlanyuan/tiny-slider#24]
Tiny slider works awesome in all browser other than safari in windows OS. After first sliding the next sliding is not happening.

**Comment by ganlanyuan** [comment]
Hey, thanks for the report. 
I will check it next Monday.

**Comment by jineshjp** [comment]
Glad to consider the issue

**Comment by ganlanyuan** [comment]
Just add a new commit which should fix the issue.
Could you check it?
Thanks again for the reporting.

**Comment by jineshjp** [comment]
The problem is fixed.
 Thanks again to consider me
