### ISSUE TITLE
`.destroy()` does not remove `hidden` attribute from custom controls

### ISSUE THREAD

**Issue by Meekohi** [ganlanyuan/tiny-slider#240]
__Issue description__:

When using custom controls, if you initialize the slider and there is only one slide, the controls are given the `hidden` attribute (see `updateNavVisibility`). If you `.destroy()` the slider, this attribute is incorrectly left on the controls.

Probably wouldn't matter, but if later you reinitialize the slider (for example, swap out new images and turn it back on), the controls are now "stuck" with the `hidden` attribute.

_Tiny-slider version_:  2.8.2
_Browser name && version_: Chrome
_OS name && version_:   OSX

**Comment by Meekohi** [comment]
see https://jsfiddle.net/w136t9Lk/28/ for demo

**Comment by ganlanyuan** [comment]
Should be fixed in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/4fd289ad5ee7ce3f151b36fe8556399640215af6).

**Comment by Meekohi** [comment]
Yup I can confirm this fixes it. Thanks!
