### ISSUE TITLE
how to refresh the slider

### ISSUE THREAD

**Issue by ali-hellani** [ganlanyuan/tiny-slider#242]
using the latest version of tns **(2.8.2**) the viewport of the slider inside `display: none block` is `0`

so how to refresh the slider while switching between tabs or showing a modal ?!

**Comment by ali-hellani** [comment]
i have made a [pen ](https://codepen.io/ali-hellani/pen/KBXeOe) for my issue using the same plugins i use in my project

**Comment by ganlanyuan** [comment]
I see.
The problem here with vertical slider is that the children of hidden element has `0` heights.
I will see if there is any way to work around this.

**Comment by ganlanyuan** [comment]
You can hide the parent using `height:0; overflow: hidden` instead of `display: none` to work around this. 
To fix this from inside tiny-slider would be much more complicated.

**Comment by ali-hellani** [comment]
if you mean putting this code to override `display: none` for parent `tabs-panel`, it doesn't work
```
.tabs-panel:not(.is-active) {
  display: block;
  height: 0;
  overflow: hidden;
}
```

**Comment by ali-hellani** [comment]
i am still wondering why the plugin doesn't have yet a **Refresh** or **setPosition** methods like any other carousel or slider plugin

**Comment by ganlanyuan** [comment]
Check out [my forked demo](https://codepen.io/ganlanyuan/pen/NBaOea), it works well

**Comment by ganlanyuan** [comment]
Method `refresh` added to `tns` in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/aeafe2b3ed9039e89f333b026eb83f557f2c9395), you can use it in this way:
```javascript
tab.addEventListener('click', function(e){
  container.show(); // make the slider visible
  sliders[i].refresh(); // refresh the slider
});
```

**Comment by ganlanyuan** [comment]
New version v2.8.3 was published
