### ISSUE TITLE
JS error: container is null in `resetDuration`

### ISSUE THREAD

**Issue by Meekohi** [ganlanyuan/tiny-slider#243]
__Issue description__:  
Getting this error every now and again. We're doing a lot of screwing around right before/after initializing and destroying tiny-slider so it isn't a common use case, but might indicate some other issues:
```
Uncaught TypeError: Cannot read property 'style' of null
    at Hn (tiny-slider.js:2190)
    at tiny-slider.js:2226
```

I think what's going on here is that
`setTimeout(function() { resetDuration(container, ''); }, 10);` is getting set in `doContainerTransformSilent`, but the container doesn't exist when it gets calls 10ms later. Maybe a sanity check in `resetDuration` to check that `el` actually exists would be a quick fix? Alternatively maybe the container needs to be set aside?
```
var currentContainer = container; 
setTimeout(function() { resetDuration(currentContainer, ''); }, 10);
```

_Tiny-slider version_:   2.8.2
_Browser name && version_:  Chrome
_OS name && version_:   OSX

**Comment by ganlanyuan** [comment]
Do you think you can make a demo? 
If it's not good for you do make it public, you can try to replace `doContainerTransformSilent` with `doContainerTransform` to see if the issue still happens.
BTW, I don't think it's a good idea to check `container`'s existence only for this specific case.

**Comment by Meekohi** [comment]
No problem I can appreciate that, we'll work off a fork for this. Unfortunately it's tied up in a complicated system so isn't easy to extract a small demo, if I get some time I'll see what I can do.

**Comment by ganlanyuan** [comment]
Ok, thanks for your understanding.
