### ISSUE TITLE
Navigation feature request

### ISSUE THREAD

**Issue by monovita** [ganlanyuan/tiny-slider#244]
Thank you for all the wonderful work!

Would love to see a few features:

- Ability to display current slide as well as total count. ex (2 of 23)
- Numerical pager ex :(1 2 3 4)
- Ability to advance to next slide by clicking it
- Ability to bind prev/next functions with arrow keys

**Comment by ganlanyuan** [comment]
```javascript
var slider = ({…});

var info = slider.getInfo();
slider.events.on('transitionEnd', function(info){
  // info.navCurrent => current slide
});
```

Current slide: `info.navCurrent`.
Total count: `info.slideCount`.
Numerical pager: you can make `nav` (dots) as a pager.
Ability to advance to next slide by clicking it: just set `controls: true` and use the prev/next control buttons.
Ability to bind prev/next functions with arrow keys: set `arrowKeys: true`.

**Comment by monovita** [comment]
Thank you very much, how do I output info.navCurrent and info.slideCount to a specific class?

**Comment by ganlanyuan** [comment]
```javascript
var info = slider.getInfo(),
    current = document.querySelector('.your-class'),
    total = document.querySelector('.your-class-2');

total.textContent = info.slideCount;

slider.events.on('transitionEnd', function(info){
  current.textContent = info.navCurrent;
});

**Comment by monovita** [comment]
Much appreciated! While total works, current does not output.

**Comment by ganlanyuan** [comment]
Well, you can do current.textContent = info.navCurrent for initialization.

**Comment by monovita** [comment]
I have but I'm not having any luck with it, any help would be appreciated.

**Comment by monovita** [comment]
The closest result I'm getting is with:

`var info = slider.getInfo(),
    current = document.querySelector('.currentSlide'),
    total = document.querySelector('.totalSlides');

current.textContent = info.index;
total.textContent = info.slideCount;

slider.events.on('transitionEnd', function(info){
  current.textContent = info.index;
});`

with **loop: true**, count is proper say 1-3, but after advancing from last slide back to one it outputs 4 (ie first slide appears under number 4)

with **loop: false**, count begins with 0

I prefer loop, therefore how do I go about preventing the behavior of after first cycle slide one resets to 1 as opposed to the number of last slide.

Thank you

**Comment by ganlanyuan** [comment]
If you use `index`, you need to remove the amount of cloned slides before the initial slides. So you can do 
```javascript
current.textContent = info.index - info.cloneCount;
```

**Comment by bobmitro** [comment]
Insted 
`current.textContent = info.index;`
use
`current.textContent = slider.getInfo().displayIndex;`

As a result, slide numbers start at 1 and show their actual quantity.
