### ISSUE TITLE
how to get the prev and next buttons correctly

### ISSUE THREAD

**Issue by oldcastlehq** [ganlanyuan/tiny-slider#246]
Hi,

I'm trying to work out a way to have tiny-slider showing up the prev/next buttons like Owl does here:

![Owl-carrousel](https://i.imgur.com/7kv8rrp.png)

The icon itself is not the problem - in the example Owl is using font-awesome -, my issue is positioning the arrows correctly. 

Do you have a demo for that?

**Comment by ganlanyuan** [comment]
Hi, you can use CSS to achieve this.
[demo](https://codepen.io/ganlanyuan/pen/PBeOOY)

**Comment by oldcastlehq** [comment]
Perfect! Thank you.
