### ISSUE TITLE
Support for 'Babel-preset-env'

### ISSUE THREAD

**Issue by monopine** [ganlanyuan/tiny-slider#247]
__Issue description__:  
`babel-preset-es2015`, and `babel-preset-es2017` have been deprecated in favor of `babel-preset-env`. If you chose to use env instead of es2017, however you get an error on compile:

`ERROR in ./node_modules/tiny-slider/src/tiny-slider.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "es2017"`

Though deprecated, babel-es2015/es2017 still work, and thus I'm able to continue to build the project.

_Tiny-slider version_:   
2.8.3

_Browser name && version_:  
babel-preset-env: 1.6.1,
webpack: 4.12.0

**Comment by ganlanyuan** [comment]
Babel here is for only for local testing (translate `async` to `generator`), so it won't affect the library itself. But I also replaced `es2015`, `es2017` with `env` in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/dc82fb59bdee8cdcb1faf1977713dbf303203171).
