### ISSUE TITLE
Custom CSS class

### ISSUE THREAD

**Issue by ronpearl** [ganlanyuan/tiny-slider#249]
Just to point out, this is more of a suggestion than a bug...

I am currently playing with your slider (which is working great by the way as it is very versatile) and have implemented it on a page that contains multiple sliders along with different options within each. Currently, each slider has their own class or ID and they are working independently, however, I need to style a few of the navigation items differently. For example, the next/prev buttons and the pagination buttons. 

Is there a way someone could add a specific class name to the tns-outer divs so that I could target the slider nav items individually? In applications I have built before I would add something like this as an option when creating the slide, or even use the original class/id name and add an "outer-original-name" to this tns-outer div. I know I could add another div around the original one but that just creates another level of useless divs when we could utilize an already created div.

Tiny-slider version:   2.8.2

**Comment by ganlanyuan** [comment]
So should I put a class with the slider id to the outer wrapper?
For instance, if the slider id is "my-slider", the class name of the outer wrapper will be: "tns-outer my-slider-ow". ("ow" stands for "outer wrapper")

**Comment by ronpearl** [comment]
Thanks for responding! I think that would be very beneficial and will help target a specific slider when multiple sliders are on the page. That suggestion would be good because it uses the original ID and it makes sense

**Comment by ganlanyuan** [comment]
Released in v2.8.4

**Comment by kyooriouskoala** [comment]
Hi, I'm also looking to add custom classes to the outer wrapper `.tns-outer` since we are using BEM approach to style different type of carousels. Would be great if it can be more scalable in this manner than just having custom ID. Thanks!

**Comment by TanyaScales** [comment]
+1 for the ability to add a custom class to the `.tns-outer` wrapper
