### ISSUE TITLE
Axis Vertical - Not Working

### ISSUE THREAD

**Issue by gilnoycloudinary** [ganlanyuan/tiny-slider#251]
__Issue description__:  Vertical mode of slider is not working

__Demo link/slider setting__:   https://codepen.io/team/Cloudinary/pen/OwryNW/

_Tiny-slider version_:   2.84
_Browser name && version_: Chrome  
_OS name && version_:

**Comment by ganlanyuan** [comment]
Should be fixed by [this commit](https://github.com/ganlanyuan/tiny-slider/commit/2d9501e90dfe427a6c2b21261241eb8aae3f1afc).

**Comment by ganlanyuan** [comment]
v2.8.5 was released
