### ISSUE TITLE
Rewind: false doesn't work properly

### ISSUE THREAD

**Issue by alexko30** [ganlanyuan/tiny-slider#257]
__Issue description__:  Good afternoon. I have a problem with ```rewind: false```, it works like ```rewind: true``` , and rewind executes when I got sixth item of 8. Below is example. Slider starts with the first slide.

![rewind](https://user-images.githubusercontent.com/32678846/44256386-afa88200-a211-11e8-8940-f2f236f40f92.gif)

__Demo link/slider setting__:   
```
const slider = tns({
  container: ".projects-wrapper",
  mode: "carousel",
  axis: "horizontal",
  items: 4,
  speed: 800,
  mouseDrag: true,
  rewind: false,
  slideBy: 1,
  responsive: {
      50: {
        items: 1
      },
      540: {
        items: 2
      },
      700: {
        items: 3
      },
      1100: {
        items: 4
      }
    }
});
```

_Tiny-slider version_:   2.8.5
_Browser name && version_:  Chrome & 68.0.3440.106 (Official Build) (64-bit)
_OS name && version_:   macOS High Sierra & 10.13.6

**Comment by ganlanyuan** [comment]
Hey, the effect shown in the gif image is actually `loop`.
When reach the edge of the slider, both `loop` and `rewind` will go to the other edge but with different directions: `loop` will keep the current direction while `rewind` will go oppositely.

**Comment by alexko30** [comment]
Thanks, got it.
