### ISSUE TITLE
Resize bug when using responsive option with nav turned off

### ISSUE THREAD

**Issue by guschilds** [ganlanyuan/tiny-slider#26]
## Steps to reproduce

I am using the slider with these options:

```
return tns({
  container: carousel,
  items: 1,
  edgePadding: 20,
  responsive: {
    681: 2,
    1360: 4
  },
  slideBy: 'page',
  nav: false,
  loop: false
```

When I resize between breakpoints, the carousel item display breaks and errors like this are thrown in the console:

```
Uncaught TypeError: Cannot read property '1' of undefined
    at jt (tiny-slider.js:1896)
    at Tt (tiny-slider.js:1952)
    at tiny-slider.js:1967
```

## Proposed resolution

I've tracked it down to this code:

```
if (items !== itemsTem && !options.navContainer) {
  updateNavDisplay();
  updateNavStatus();
}
```

The problem is that `updateNavDisplay()` and `updateNavStatus()` are being called, even if `nav` is `false`. It can be fixed by changing it to:

```
if (items !== itemsTem && options.nav && !options.navContainer) {
  updateNavDisplay();
  updateNavStatus();
}
```

Note: I attempted to fork the repository and create a pull request, but was not able to run the Gulp tasks that turn `src` into `dist`. It seems this is because package.json doesn't list the packages used within the gulpfile, but I even ran `npm install` for all of them manually, and was still getting errors when running `gulp script`. Am I missing something or approaching this incorrectly?

Regardless, thanks for your work on this! It's the smallest carousel written in vanilla JS that accomplishes everything we need.

**Comment by ganlanyuan** [comment]
Hi @guschilds , thanks for reporting this.
I just added a [fixing](https://github.com/ganlanyuan/tiny-slider/tree/085fa0a884ac8f709aa72798846efbdb8b929f1e), could you check if it works for you?

By the way, I usually run this repo in a [docker image](https://github.com/ganlanyuan/tiny-slider/blob/master/docker-compose.yml), and the actual *package.json* used is not the one in the repo.

**Comment by ganlanyuan** [comment]
It's added in [a new release](https://github.com/ganlanyuan/tiny-slider/releases/tag/v1.3.1).

**Comment by guschilds** [comment]
@ganlanyuan,

Thank you for such a quick response. The fix does work for me.

And thanks for pointing out the docker image. I'm less experienced with Docker. A [CONTRIBUTING.md file](https://github.com/blog/1184-contributing-guidelines) may help others like myself with this in the future, but it's not a huge deal.
