### ISSUE TITLE
Slider drag is unresponsive

### ISSUE THREAD

**Issue by dineshkhadka** [ganlanyuan/tiny-slider#264]
__Issue description__:   The drag behavior on desktop is not very smooth. It sometime fails to drag items. Also the when dragging links it automatically opens it, unlike owl carousel where it only opened when clicked and not dragged

__Demo link/slider setting__:   
` var slider = tns({
                    container: '.slider-swiper',
                    slideBy: 'page',
                    mouseDrag: true,
                    autoplay: false,
                    nav: false,
                    controls: false,
                    responsive: {
                        640: {
                            // edgePadding: 20,
                            // gutter: 20,
                            items: 1
                        },
                        700: {
                            // gutter: 30,
                            items: 1
                        },
                        900: {
                            items: 3
                        }
                    }
                });`

_Tiny-slider version_:   
_Browser name && version_:  2.8.6
_OS name && version_:   Windows 10. chrome 69

**Comment by ganlanyuan** [comment]
For the dragging is not smooth or fails, it may related to `swipeAngle` option which requires the dragging direction is less than 15deg against the horizontal axis by default. You may set `swipeAngle` to `false` if you want.
Another factor is the dragging requires at least 5px away from the original mouse location.

For the opening link issue, could you set a demo page, so that I can check in detail? Since I couldn't see this issue when I test on my end.

**Comment by dineshkhadka** [comment]
Hello, sorry for the late reply. The first issue is fixed due to swipeAngle.
As for the second, the issue is that I have a gallery slider with links that trigger a popup when clicked. When I am dragging the slider the click event is triggered, owl carousel disables click event when the slider is being dragged. As shown in the gif below

![giphy](https://user-images.githubusercontent.com/4678264/45261907-7b983980-b42a-11e8-8d22-d339abc5847d.gif)

**Comment by ganlanyuan** [comment]
Could you make a demo page?

**Comment by ganlanyuan** [comment]
close due to inactivity
