### ISSUE TITLE
Freeze doesn't work with controlsContainer

### ISSUE THREAD

**Issue by pasik89** [ganlanyuan/tiny-slider#266]
Slider does't freeze when all elements are in viewport. You need to add controlsContainer to this line:

 `if (freeze) {
    controls = nav = touch = mouseDrag = arrowKeys = autoplay = autoplayHoverPause = autoplayResetOnVisibility = false;
  }`

with controlsContainer it's working:

` if (freeze) {
    controls = nav = touch = mouseDrag = arrowKeys = autoplay = autoplayHoverPause = autoplayResetOnVisibility = controlsContainer = false;
  }`

**Comment by ganlanyuan** [comment]
Could you make a demo or let me know your slider options?
I didn't see this issue happen on my end.
Thanks
