### ISSUE TITLE
testcafe-browser-provider-saucelabs marked as dependency?

### ISSUE THREAD

**Issue by DonGissel** [ganlanyuan/tiny-slider#27]
The package `testcafe-browser-provider-saucelabs` is marked as a dependency when installing the package through NPM, which makes the slider install a whole lot of code (like Babel, a browser and similar stuff) I'm pretty sure I won't need. The dependency graph for my project literally (figuratively) exploded.

Shouldn't it be marked in `devDependencies` instead, or am I missing something?

**Comment by ganlanyuan** [comment]
Thanks, it's updated
