### ISSUE TITLE
We should be able to import tiny-slider and avoid errors when window and document are undefined.

### ISSUE THREAD

**Issue by opr** [ganlanyuan/tiny-slider#279]
__Issue description__:  
I am rendering a react component on the server using ReactJS.NET but because window and document don't exist on the server, tinyslider runs into issues when trying to work. I propose that we build in logic to the slider to avoid errors when window and document are not defined. This will not affect functionality, it will just allow error-free rendering.

__Demo link/slider setting__:  n/a

_Tiny-slider version_:   n/a
_Browser name && version_:   n/a
_OS name && version_:   n/a

**Comment by opr** [comment]
After investigation I don't think this is possible because of dependencies also needing window and document.

**Comment by ricardobrandao** [comment]
I think that a big warning should be displayed in the README since this won't work with server-side rendered apps.

**Comment by opr** [comment]
> I think that a big warning should be displayed in the README since this won't work with server-side rendered apps.

Yes this is true, my solution was to wrap the calls to `tns` in something like this

```javascript
if(process.env.NODE_ENV !== 'server') { 
  tns({...});
}
```
