### ISSUE TITLE
Add event type to info object

### ISSUE THREAD

**Issue by Suruat** [ganlanyuan/tiny-slider#280]
Please, add information about what type of event is fired to the info object (that used in event callback) that would be always available on all kinds of events.

**Comment by ganlanyuan** [comment]
You can get the event by `info.event`

**Comment by Suruat** [comment]
@ganlanyuan I know, but 'type' property doesn't contain any information of what kind of event is fired

**Comment by ganlanyuan** [comment]
The `info.event` is the same as the original `event`. So if the `event.type` exists, you should be able to get it via `info.event.type`.

**Comment by Suruat** [comment]
I know that as well. My point - developers that use you plugin in some situations need to know what kind of event (**custom event too**) is firing. So every event, even if it have no original `event`, should contain useful information about itself (in my request it is `type`)

**Comment by ganlanyuan** [comment]
I see.
I just added a `eventName` parameter to the custom event function in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/06b774b403f734b51e79ccac00fa85905fd7e0af). 
You can use it this way:
```js
 slider.events.on('transitionEnd', function(info, event) {
  console.log(event);
});
```
Refer to https://github.com/ganlanyuan/tiny-slider#custom-events
