### ISSUE TITLE
standard import with browserify

### ISSUE THREAD

**Issue by p3pp8** [ganlanyuan/tiny-slider#281]
Hello, i'd like to use tinySlider with my browserify generated bundle, but:

```
import { tns } from "tiny-slider"
```
returns an undefined ```tns``` object.
Is it possible to do or i have to include the tinySlider js into my index.html?
Any help is really appreciated.

Cheers

**Comment by LotharVM** [comment]
Try this: 

```javascript
import { tns } from 'tiny-slider/src/tiny-slider'
```

**Comment by p3pp8** [comment]
@LotharVM Thanx for the answer, unfortunately now i've this error:

```ParseError: 'import' and 'export' may appear only with 'sourceType: module'```

There must be something wrong, i'm trying to spot it out... Any other help is really appreciated. 
Thanx again!

**Comment by p3pp8** [comment]
@LotharVM SOLVED just added babelify to the package.json of tiny-slider:

```
"browserify": {
      "transform": [
            ["babelify", {
                  "presets": ["@babel/preset-env"]
            }]
      ]
  }
```

Cheers!
