### ISSUE TITLE
how do we turn of the play/stop button?

### ISSUE THREAD

**Issue by trusktr** [ganlanyuan/tiny-slider#282]
I mean I know we can make it `display:none` with CSS, but I didn't see an option for it. If I set `controls` to `false`, I still see the play/stop button.

**Comment by openscript** [comment]
You can set `autoplayButtonOutput` to `false`. If no custom buttons are provided and autoplay is set to `true` tinyslider will output the play button markup.

**Comment by ganlanyuan** [comment]
That's right, thanks @openscript
