### ISSUE TITLE
Responsive items and fixedWidth properties

### ISSUE THREAD

**Issue by namerci** [ganlanyuan/tiny-slider#283]
__Issue description__:  When you open browser firstly on mobile breakpoint (< 768), and then resize it to tablet breakpoint (>=768), it didn't reload all settings. Width is incorrect. Instead of 2 elements, I see 3 elements. But when you open page firstly on tablet breakpoint, then resize to mobile (it works), then resize to tablet again, it works well.

__Demo link/slider setting__:   
```
        tns({
            container: this.carousel.nativeElement,
            nav: false,
            controls: false,
            mouseDrag: true,
            responsive: {
                0: {
                    fixedWidth: 216,
                    gutter: 15
                },
                768: {
                    fixedWidth: false,
                    items: 2,
                    gutter: 24
                }
            }
        });
```

_Tiny-slider version_:   2.8.6
_Browser name && version_:  Chrome, latest (69)
_OS name && version_:   Windows 10, latest

**Comment by ganlanyuan** [comment]
`fixedWidth` cann't be set to other values rather than positive number, so you can't set it to `true` or `false`. Refer to [here](https://github.com/ganlanyuan/tiny-slider#responsive-options)
