### ISSUE TITLE
Type Error: el is undefined

### ISSUE THREAD

**Issue by mrpsiho** [ganlanyuan/tiny-slider#285]
I have got "Type Error: el is undefined" (FF) / "Uncaught TypeError: Cannot read property 'addEventListener' of undefined" and "Uncaught TypeError: Cannot read property 'removeEventListener' of undefined" (Chrome) errors when using the slider instance with `fixedWidth` setting set to something other than false. Controls are on and custom. It happens when I click on next or prev links after a certain amount of times. Probably, the number of slides multiplied by three plus 1. So, if my slider outputs 3 slides, then on 10th click on either way etc.

And everything works just perfect if I removed `fixedWidth` setting, for instance.

_Tiny-slider version_:   2.8.6
_Browser name && version_:  FF/Chrome latest
_OS name && version_:   macOS 10.13.6

**Comment by ganlanyuan** [comment]
May I know the slider configuration?

**Comment by Muffinman** [comment]
I'm also seeing this with the below config. I have 4 slides, after all 4 have have animated then each subsequent slide generates the console error (and it doesn't change slides again after that point). I guess after the slides are being created/deleted the events are not being re-bound.

This only happens with `mode: gallery` as far as I can tell.

```js
tns({
  container: context.querySelector('.field--name-field-slides'),
  navContainer: context.querySelector('.slider-nav'),
  items: 1,
  mode: 'gallery',
  speed: 1000,
  animateIn:'tns-fadeIn',
  animateOut: 'tns-fadeOut',
  autoplay: true,
  controls: false,
  loop: true,
  autoplayButtonOutput: false,
  fixedWidth: 1800,
  viewportMax: 1800,
  responsive: {
    0: {
      fixedWidth: 760,
      viewportMax: 760,
    },
    760: {
      fixedWidth: 1800,
      viewportMax: 1800,
    }
  }
});
```
