### ISSUE TITLE
Inactive slide overflows to active slide

### ISSUE THREAD

**Issue by martincapek** [ganlanyuan/tiny-slider#286]
__Issue description__:  

When I have just 3 slides in slider on some resolution (1920 for example) slides overflows to active slide.

__Demo link/slider setting__:   
https://www.papousek-silhan.com/cs

```javascript
let homepageSlider = tns({
    container: '#psHomepageSlider',
    items: 1,
    slideBy: 'page',
    autoplay: false,
    autoplayButton: false,
    autoplayButtonOutput: false,
    nav: false,
    touch: true,
    mouseDrag: true,
    controls: false,
    autoplayTimeout: 9000,
    loop: false
  });
```

_Tiny-slider version_:   2.8.6
_Browser name && version_:  Chrome 69
_OS name && version_:   Mac OS 10.13.6

**Comment by ganlanyuan** [comment]
Due to the half-pixel issue, there maybe 1px overlapping. 
Try to set a `gutter` may fix this.

**Comment by martincapek** [comment]
It works. Thanks a lot for help.
