### ISSUE TITLE
Keep nav dot number stay the same

### ISSUE THREAD

**Issue by squarer** [ganlanyuan/tiny-slider#290]
__Issue description__:  
nav number changes while drag items, base on leftover item number.
expect behavior like: 
https://owlcarousel2.github.io/OwlCarousel2/demos/responsive.html
thanks!

__Demo link/slider setting__:   
https://codepen.io/squarer/pen/RYXZXZ?editors=1111

_Tiny-slider version_:   2.8.6
_Browser name && version_:  Chrome 69.0.3497
_OS name && version_:  macos high sierra 10.13.6

**Comment by ganlanyuan** [comment]
For better accessibility, the nav dots need to reflect current visible slides, that's why they keep changing.
You can also set `navAsThumbnails: true` to prevent this while at the same time all dots will be visible.

**Comment by squarer** [comment]
thanks for your response

**Comment by ganlanyuan** [comment]
FYI, I updated the accessibility related attributes, and now `nav` stay the same in v2.9.0
