### ISSUE TITLE
Add attraction & friction

### ISSUE THREAD

**Issue by panec** [ganlanyuan/tiny-slider#293]
__Feature Request description__:  

If it is possible please add support for a better / smooth control of sliding on the mobile devices. Currently it is a bit choppy and not as fluid as mobile users are used to. Flickity slider does this in a very nice way. Adding some more fluidity to the motion will be highly beneficial.
__Demo link/slider setting__:   
https://flickity.metafizzy.co/options.html#selectedattraction-friction

_Tiny-slider version_:   2.8.6
_Browser name && version_:  ALL 
_OS name && version_:  OSX

**Comment by ganlanyuan** [comment]
You can achieve this using customized CSS transitions or animations. For example, https://daneden.github.io/animate.css/
