### ISSUE TITLE
Last slide is visible for a short moment on init

### ISSUE THREAD

**Issue by michalwlodarczyk** [ganlanyuan/tiny-slider#295]
__Issue description__:  Tiny-slider adds cloned last slide to the DOM for `loop: true` and `rewind: false` in config. This causes ugly blink on page load, especially when used as main slider on the top of the site.

__Demo link/slider setting__:   http://jsfiddle.net/0eyk69jo/ <- try run jsfiddle few times and you will notice green slide no 4 on init

_Tiny-slider version_:   2.8.7
_Browser name && version_: the latest Chome/Safari/FF
_OS name && version_:   macOS Mojave

**Comment by michalwlodarczyk** [comment]
Yep, I know that, but there is too much time between cloning and adding transform. I've tried to remove some code and I've found out that I can fix my problem by disabling `raf` and `imageLoaded` here (https://github.com/ganlanyuan/tiny-slider/blob/master/src/tiny-slider.js#L730):
```
raf(function(){ imageLoaded(arrayFromNodeList(imgs), function() {
```
Maybe this will help :)

**Comment by ganlanyuan** [comment]
I see.
Since you set `autoHeight: true`, I have to make sure all images are loaded before the layout is set properly. Otherwise, the slider height may be calculated wrongly.
But I do see improvement needed here. Instead of check all the images, I just need to check the images in the visible slides.
Thanks

**Comment by ganlanyuan** [comment]
>But I do see improvement needed here. Instead of check all the images, I just need to check the images in the visible slides.

This is done in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/2b25ede61d5bd89b31e3b259ad9ec46c5abfc204).
