### ISSUE TITLE
How to disable the animation?

### ISSUE THREAD

**Issue by iamryanyu** [ganlanyuan/tiny-slider#296]
__Issue description__:  I would like know how I can disable the animation when sliding. I know there are some custom animations I can use, but I want to totally disable the animation. So with `autoplay`, when it goes to the next slide, the next slide just appears without any animation.

__Demo link/slider setting__:   n/a

_Tiny-slider version_:   2.8.7
_Browser name && version_: n/a 
_OS name && version_:   n/a

**Comment by ganlanyuan** [comment]
@michalwlodarczyk thanks
`speed: 0`
