### ISSUE TITLE
Encountered issue with events

### ISSUE THREAD

**Issue by LeFredd** [ganlanyuan/tiny-slider#297]
__Issue description__:  When `arrowKeys` is enable, if we click on control buttons then press arrow keys, the slider skip an index, perhaps theres an issue with adding/removing event listeners

edit: Another problem found: When `arrowKeys` is disabled, if we click on control buttons once time we can navigate with arrow keys

_Tiny-slider version_:   2.8.7
_Browser name && version_:  Chrome  Version 68.0.3440.106 (Build officiel) (64 bits)
_OS name && version_:   Ubuntu 16.04 LTS

**Comment by ganlanyuan** [comment]
These are expected.
1. `arrowKeys` is independent with the prev/next buttons, so clicking a control button and pressing arrow key are two steps. So press the right arrow after clicking the next button will be the same as click the right button twice.
2. When the control buttons are focused, the slider can be controlled by arrow keys. This is part of accessibility and has nothing to do with `arrowKeys`.
