### ISSUE TITLE
Swipe between slides not work correctly when autoplay is enabled

### ISSUE THREAD

**Issue by martin-badin** [ganlanyuan/tiny-slider#298]
__Issue description__:  Hello, when I use autoplay and dragging function simultaneously the interval for autoplay isn't reset when a user swipe between slides. See example. Please, reset the interval when a user swipe between slides.

__Demo link/slider setting__:   http://jsfiddle.net/p5wdjLn2/12/

_Browser name && version_:  Chrome 69.0.3497.100
_OS name && version_:   macOS Mojave 10.14

**Comment by Jack89ita** [comment]
I got the same problem and I was writing the same issue. Thank you for posting!

**Comment by martin-badin** [comment]
here is solution

for stop timer
```javascript
function onPanStart (e) {
    if (running) { onTransitionEnd(); }

+   if (autoplay && animating) { stopAutoplayTimer(); }

    panStart = true;
    if (carousel) {
      caf(rafIndex);
      rafIndex = 0;
    }
    ...
```

and for start timer
```javascript
function onPanEnd (e) {
    ...

    if (swipeAngle) { moveDirectionExpected = '?'; } // reset

+   if (autoplay && !animating) { setAutoplayTimer(); }
  }
```

please, implement this fix to master

**Comment by ganlanyuan** [comment]
@martin-badin So you want the interval for autoplay start right after the touch end?
I think @Jack89ita's solutions is good for this.

**Comment by ganlanyuan** [comment]
Added in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/825fa087f571d0d2a395d22e89b29c5ba85a96ab).

**Comment by martin-badin** [comment]
Thanks

**Comment by Jack89ita** [comment]
Hi @ganlanyuan thank you for fixing this, but how can i download this edited package?
thanks!

**Comment by ganlanyuan** [comment]
@Jack89ita This change is not published yet, so you won't be able to download via npm.
But you can still download it manually at the repository of this library.

**Comment by TitanFighter** [comment]
@Jack89ita 
`npm install https://github.com/ganlanyuan/tiny-slider#10b15514f114b3ea1053a639aa5b449939ca334a`
or
`npm install ganlanyuan/tiny-slider`

**Comment by Jack89ita** [comment]
@TitanFighter Thank you!

**Comment by davson584** [comment]
The bug is still showing when **autoplayHoverPause** is set as **true**

**Comment by saver174** [comment]
@martin-badin  The bug is still here

**version**
"tiny-slider": "^2.9.1",

**config**
var slider = tns({
	container: '.my-slider',
	items: 3,
	autoplay: true,
	mouseDrag: true,
	controls: false,
	nav: false,
	autoplayHoverPause: true,
	autoplayButtonOutput: false
});

When I drag and hold with mouse on slide item and get out of slider with cursor, animation resume (animation should not resume when drag is hold)
