### ISSUE TITLE
Need help with a small feature

### ISSUE THREAD

**Issue by imashishks** [ganlanyuan/tiny-slider#30]
First of all big fan of the slider.

Can any help me with a small feature I want to implement with the slides. I want to show a part of the left and right sides..with the main slide(the main slide takes the full screen for now..)  

Somewhat like the stagepadding option in the owl carasouel.
https://owlcarousel2.github.io/OwlCarousel2/demos/stagepadding.html

Will be grateful for the help

**Comment by nfoenki** [comment]
Hello,
did you try the 'edgePadding' option ?
Can see it in the test folder 
![edgepadding](https://cloud.githubusercontent.com/assets/1288490/24803650/23243c8a-1bac-11e7-9f5b-0c6fd7d7bf99.png)

**Comment by ganlanyuan** [comment]
Thanks @nfoenki ,
Yeah, you can use `edgePadding`.
[demo](http://ganlanyuan.github.io/tiny-slider/tests/#gutter)   
[example](https://github.com/ganlanyuan/tiny-slider/blob/master/examples.md#edge-padding)

**Comment by imashishks** [comment]
Thanks a lot both of guys..for responding so fast. edgePadding solved my issue. Much appreciated :)
