### ISSUE TITLE
Enhacement: by an offset parameter, when navAsThumbnails is enabled

### ISSUE THREAD

**Issue by yerzhant** [ganlanyuan/tiny-slider#305]
Is it possible to enhance the slider with an offset (responsible) parameter, so that when one clicks on a thumb it (slide) gets depicted at some offset from the left side of the viewport?

I.e. when I click on the images in the thumbs panel it is shown not on the left side of the viewport, but, say, on the center?
http://ganlanyuan.github.io/tiny-slider/tests/index.html#customize_wrapper

**Comment by yerzhant** [comment]
The url has changed:
http://ganlanyuan.github.io/tiny-slider/demo/#customize_wrapper

**Comment by ganlanyuan** [comment]
I think you can use option `edgePadding`, https://github.com/ganlanyuan/tiny-slider#options
