### ISSUE TITLE
add event click item

### ISSUE THREAD

**Issue by xavivzla** [ganlanyuan/tiny-slider#307]
I add the click event to the items, but I do not know how to get the id from the target

**Comment by martincapek** [comment]
@xavivzla Hi, can you show code example please?

**Comment by xavivzla** [comment]
@martincapek i need a handler. when i'm click in a item, let me show modal with a duplicate slider but with item clicked center in the new slider

**Comment by ganlanyuan** [comment]
@xavivzla I guess this is not related to this library, but basically you can get the item id by:
```javascript
item.addEventListener('click', function(e) {
  var target = e.target,
      id = target.id;
});
```
