### ISSUE TITLE
Nav buttons are not working properly in gallery mode

### ISSUE THREAD

**Issue by nfoenki** [ganlanyuan/tiny-slider#31]
How to reproduce :
set 'mode' option to '**gallery**'
click once on "prev", "next" or a nav button -> works as expected
click again on any of these buttons -> works not as expected : nothing happen

you can see it on the test page on the "animation" test

![screenshot](https://cloud.githubusercontent.com/assets/1288490/24803269/ff46a4c0-1baa-11e7-9425-7d0048134d06.png)

**Comment by ganlanyuan** [comment]
Thanks, I also noticed this issue recently, will look at it today.

**Comment by ganlanyuan** [comment]
Hi, this is fixed in [the latest release](https://github.com/ganlanyuan/tiny-slider/tree/v1.4.0).
Could you check if it works for you?
Thanks

**Comment by nfoenki** [comment]
it works !
great !
