### ISSUE TITLE
Place navigation controls at the bottom

### ISSUE THREAD

**Issue by frankackermann** [ganlanyuan/tiny-slider#314]
__Issue description__:  I have seen that it has been decided to put all control and navigation elements on top of the slider, due to accessibility (#4). This is totally fine, but in my case it is needed to have the navigation underneath. Since I could not find any option to place navigation controls at the bottom, I highly recommend to add an option for the position. This would make the slider more flexible without using the workaround with `navContainer` where one need to know how many elements are in the slider during markup generation. Also styling this additonal container causes more CSS code.

__Demo link/slider setting__:
```javascript
slider = tns({
	container: '.container-class',
	controls: false,
	items: 1,
	nav: true,
	navPos: 'bottom' // not supported yet
});
```

_Tiny-slider version_:   2.8.7

**Comment by ganlanyuan** [comment]
added options: `navPosition`, `controlsPosition` and `autoplayPosition` in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/20af11bd6aac90f4945240d9ba9ee1c13d48b565).
I will update the document later

**Comment by ganlanyuan** [comment]
Document updated

**Comment by ciampam9** [comment]
@ganlanyuan 👋 when could we expect a release with this functionality?

**Comment by ganlanyuan** [comment]
released 2.8.8

**Comment by frankackermann** [comment]
Very useful. Thanks a lot!

**Comment by LoickMEYER** [comment]
Hi, very nice, is it possible to add the "both" value to have the navs dots twice (above and under) it could be very useful for slides with huge height. Thanks !
