### ISSUE TITLE
Perpetually scrolling and looping infinitely

### ISSUE THREAD

**Issue by Cherry** [ganlanyuan/tiny-slider#318]
__Issue description__:  

I'm trying to create an infinite scrolling carousel that loops perpetually, and never bounces back to the beginning. I'm not finding a way to accomplish this, but it's possible I'm missing an option. The provided demo works somewhat, but it seems that after a while, it resets, and bounces back to the start of the slider. There's 6 items visible, and 7 in the HTML (in reality this is ~30 items, but 7 illustrates the point).

__Demo link/slider setting__:   
https://codepen.io/cherryjimbo/pen/qJgyyM

_Tiny-slider version_: 2.8.7
_Browser name && version_: Chrome 72.0.3590.0

**Comment by Cherry** [comment]
Thanks! I just updated my codepen at https://codepen.io/cherryjimbo/pen/qJgyyM and it appears to just scroll into infinite emptiness now. I didn't set `autoplayTimeout` to 0 as that prevented it from scrolling infinitely when doing so, but I did set the new `preventActionWhenRunning` option.

**Comment by ganlanyuan** [comment]
Actually I made a mistake, so it didn't work.
Just fixed it in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/9e150536887ec613c7dcc8afe3f39af727035548).

**Comment by Cherry** [comment]
The previously mentioned issue does now appear to be resolved, thanks!

It appears as if this broke what I was originally attempting to do, with a seamless slider that doesn't start/stop though. The previous options of
```
speed: 750,
autoplayTimeout: 750,
```
did work, but there appears to be a delay now.

New: https://codepen.io/cherryjimbo/pen/qJgyyM (prevents the bounce-back issue, but causes a delay between slides)
Old: https://codepen.io/cherryjimbo/pen/MPdqpb (slides seamlessly, but has the original bounce-back issue)

**Comment by ganlanyuan** [comment]
You should set 
```js
autoplayTimeout: 0,
```
The delay was `750` ms

**Comment by Cherry** [comment]
Ah, you're right. Sorry about that! Everything seems to work now - there's definitely a little "jerk" during the slide transition, but it works reasonably well. 😃

**Comment by Nvmcreation** [comment]
Hello

> **Issue description**:
> 
> I'm trying to create an infinite scrolling carousel that loops perpetually, and never bounces back to the beginning. I'm not finding a way to accomplish this, but it's possible I'm missing an option. The provided demo works somewhat, but it seems that after a while, it resets, and bounces back to the start of the slider. There's 6 items visible, and 7 in the HTML (in reality this is ~30 items, but 7 illustrates the point).
> 
> **Demo link/slider setting**:
> https://codepen.io/cherryjimbo/pen/qJgyyM
> 
> _Tiny-slider version_: 2.8.7
> _Browser name && version_: Chrome 72.0.3590.0

Hello o woul like to make this one but vertical?
