### ISSUE TITLE
Slider creates scroll area wayyyyy off the side of the page

### ISSUE THREAD

**Issue by raquelmsmith** [ganlanyuan/tiny-slider#321]
__Issue description__:  

First! Thanks for creating this awesome little slider. Super useful.

I've got it installed on https://www.wptasty.com/tasty-recipes and it looks great. But for some reason if you go down to the slider and then use your mouse to scroll to the right, a giant white space opens up on the right side. Sometimes it auto-corrects and goes back to the main part of the screen, but not always. And it's not super ideal to have this be scrollable.

I tried setting `overflow: hidden` on the `tns-slider` and the `slider-outer` but that didn't work. Any other suggestions?

Here's a GIF:

![slider-sliding](https://user-images.githubusercontent.com/18598166/47732248-0cb5b080-dc23-11e8-9dc7-66229cbd7cdf.gif) 

__Demo link/slider setting__:   

https://www.wptasty.com/tasty-recipes

_Tiny-slider version_:   2.0
_Browser name && version_:  Chrome Version 69.0.3497.100, Safari current
_OS name && version_:   MacOS 10.14

Thanks for the help!

**Comment by ganlanyuan** [comment]
@raquelmsmith Did you include tiny-slider.css?

**Comment by ganlanyuan** [comment]
Okay, now you can remove `display: flex` from .slider and its children.

**Comment by raquelmsmith** [comment]
OK, when I do that, though, my design no longer works. The slides on the side are supposed to be centered vertically:

![image](https://user-images.githubusercontent.com/18598166/47922459-5f39db80-de74-11e8-9374-8cdcc520475e.png)

Any ideas for how to go about that?

**Comment by ganlanyuan** [comment]
I see,
At least you can add `overflow-x: hidden` on <body> if it doesn't affect other elements.

**Comment by raquelmsmith** [comment]
Hm.. do you know why it doesn't work if I `overflow-x: hidden` on the slider container, or even a couple levels up? i don't really want to do it on `body` unless absolutely necessary.

**Comment by ganlanyuan** [comment]
I have no idea right now, but I will check later for other solutions.

**Comment by ganlanyuan** [comment]
It turns out that a Pinterest Save Button cause this issue.
![image](https://i.postimg.cc/dV9Sf7kS/Pasted-Image-11-9-18-11-29.png)
Right now the button is far away off the screen to the right side (with `left: 3963px`).

So if you set
```css
[data-pin-href] { left: 0 !important; }
```
Or any other way to make it in the viewport, this issue will disappear.

**Comment by raquelmsmith** [comment]
Ah! That fixed it! I just put a `data-pin-nopin` attribute on the images to preven tPinterest from adding the pin hover button to them. Problem fixed. Thanks so much for your help with this @ganlanyuan!
