### ISSUE TITLE
controlsContainer option is broken

### ISSUE THREAD

**Issue by zipper** [ganlanyuan/tiny-slider#325]
__Issue description__:  Specifying custom controls using `controlsContainer` has been broken since 2.8.7. There everything worked fine, but some commits in master breaks this feature.

__Demo link/slider setting__: I have something like this:
```javascript
var controls = document.getElementById('#foo');
var carousel = tns({
  controlsContainer: controls
});
```

where `#foo` looks like this (simplified):
```html
<p id="foo">
  <button class="...">prev</button>
  <button class="...">next</button>
  <span class="nav">..."</span>
</p>
```
Inside `.nav` there are pages, they still do work correctly. But prev and next buttons are broken. Buttons are not recognized and default buttons are created insted. In 2.8.7, this king of setup worked. I tried to specify buttons using `prevButton` and `nextButton`, but that worked neither. I believe it's broken since this commit https://github.com/ganlanyuan/tiny-slider/commit/bdf8bcdf22041a0001e16526ae6dbf68a1080a1b.

Since 2.8.7 there are few bugs fixed, that's why I have tried to use master version of plugin.

_Tiny-slider version_:   master
_Browser name && version_:  Chrome, whatever

**Comment by zipper** [comment]
Confirming it works. Thank you!

**Comment by ganlanyuan** [comment]
Thanks
