### ISSUE TITLE
Not looping when clicking prev/next quickly

### ISSUE THREAD

**Issue by robertdwolf** [ganlanyuan/tiny-slider#329]
When I click on the next control it goes to the next slide but if I do it faster than the set speed time it rewinds itself back to the start without it looping seamlessly. preventActionWhenRunning helps make it loop however it also prevents me from clicking through to the next slide as quickly.

https://codepen.io/robertwolf/pen/KrMXeQ

v2.8.8
Chrome 70.0.3538.77

**Comment by ganlanyuan** [comment]
That's totally expected

**Comment by robertdwolf** [comment]
I don't encounter the same behavior in owl carousel, could it be something with how this only clones one slide to each end rather than multiple copies?

**Comment by seanmavley** [comment]
@robertdwolf Experiencing same thing with the fast clicking. You happened to figure out why it behaves that way?

Any fix?

**Comment by statickidz** [comment]
To prevent this you can use this workaround:

```javascript

const isTouchDevice =
      document && 'ontouchstart' in document.documentElement;

const tinySliderConfig = {
  // ...
  preventActionWhenRunning: !isTouchDevice,
};
```
Basically it prevents to slide to next until animation is finished when you're clicking in the arrows, I prefer to disable it on mobile so you can feel the smoothness when you're dragging.
