### ISSUE TITLE
Bower dependency when using the npm package?

### ISSUE THREAD

**Issue by marcfalk** [ganlanyuan/tiny-slider#33]
Thanks for making this. Just what I needed. But..

If I do `npm install tiny-slider` the library is installed just fine. I import it in my JavaScript component with `import { tns } from 'tiny-slider/src/tiny-slider.module';`. When I build Webpack the path resolves just fine to the installed npm package. However, in the `tine-slider.module`-file there is a dependency on go-native - a library that does not exist as an npm package, and thus a library that is not listed in the package.json either. Hence, the reference in `tiny-slider.module` to `../../go-native*` (the go-native folder in node_modules) is not resolved correctly, which makes my Webpack build fail.

Am I doing something wrong?

**Comment by ganlanyuan** [comment]
Oh, yeah
`go-native` should be published to npm.
I will let you know when there is any update on this.

**Comment by ganlanyuan** [comment]
Hey, 
I add `go-native` as dependency in `package.json` in the latest commit. 
Could you check it?
