### ISSUE TITLE
nav and controls opriona are not working.

### ISSUE THREAD

**Issue by janusz-bb** [ganlanyuan/tiny-slider#330]
__Issue description__:  Nav and controls options are not working. I can't find an obvious way to disable both or one.

__Demo link/slider setting__:   https://liveweave.com/d1ESDj

_Tiny-slider version_:   2.8.8
_Browser name && version_:  Latest Firefox, Chrome, Edge
_OS name && version_:   Windows 10

**Comment by ganlanyuan** [comment]
You just need to set them to `false`:
```js
{
  controls: false,
  nav: false,
}

**Comment by janusz-bb** [comment]
I have, but both are still being displayed.

**Comment by ganlanyuan** [comment]
No, you should use `false`, not`'false'` which is a string.

**Comment by janusz-bb** [comment]
Stupid me. It's a boolen of course. Sorry.
