### ISSUE TITLE
JS injected CSS causes slider container overgrowth.

### ISSUE THREAD

**Issue by michal-kubicki** [ganlanyuan/tiny-slider#331]
If you insert an img into a slider and set `object-fit` to `cover;` its container will get en extra bottom "space". Looks like it's caused by this line in the tiny-slider.js:

`$ && (M || ht ? (Fi(zt, "#" + le + " > .tns-item", "font-size:" + h.getComputedStyle(rt[0]).fontSize + ";",`

__Demo link/slider setting__:   https://codepen.io/anon/pen/pQRKzz

_Tiny-slider version_: 2.8.8   
_Browser name && version_:  All major desktop and mobile browsers
_OS name && version_:   Windows / Android

**Comment by ganlanyuan** [comment]
Hey, I didn't see you set `object-fit: cover` anywhere in the demo

**Comment by michal-kubicki** [comment]
Sorry, looks like codepen lost it. https://codepen.io/anon/pen/pQRKzz

**Comment by ganlanyuan** [comment]
I think this issue is similar with `a > img` which create a little bit space beneath the `img`, so 
```css
.tns-item img {
  vertical-align: bottom;
  /* or display:block; */
}
```
will fix this issue.
