### ISSUE TITLE
Webpack output of 2.8.8 throws error in IE 10

### ISSUE THREAD

**Issue by backflip** [ganlanyuan/tiny-slider#332]
__Issue description__:  
When bundling the latest version with Webpack, IE 10 throws the following error:
`SCRIPT1047: In strict mode, function declarations cannot be nested inside a statement or block.`
![image](https://user-images.githubusercontent.com/654171/48468058-24786180-e7eb-11e8-9d1c-9edbb6df4745.png)

__Demo link/slider setting__:  
https://github.com/ganlanyuan/tiny-slider/compare/master...backflip:bugfix/ie-10

_Tiny-slider version_:  2.8.8
_Browser name && version_:  IE 10
_OS name && version_:  Windows 8

**Comment by webstar** [comment]
Yeah, I get the same thing. Also experience the same error on my old iPad2 in Safari with iOS 9.something.

I've been trying to find a way to disable the strict mode declaration for just this plugin, but unsuccessful so far.
