### ISSUE TITLE
Play should work when autoplay is false

### ISSUE THREAD

**Issue by xavier83ar** [ganlanyuan/tiny-slider#334]
__Issue description__:  
When autoplay is set to false, play () method does not work, it does nothing. I want to play the slider after another event occurs, not autoplay when the slider is initialized. So, I've called play () method then, but nothing happend, I've looked into the source code and I see that play () check if autoplay is true.
I think that autoplay is a feature different from the play/stop functions, and should not depends on each other.

I've also tried to initialize the slider with autoplay: true, and stop it inmediately, but doing that it adds an stop button that I don't want. If there is a way to remove that stop button, I could manage to do what I need, but despite of it, I think that play() should not check the value of autoplay.

_Tiny-slider version_:   2.8.8
_Browser name && version_:  all
_OS name && version_:   all

**Comment by ganlanyuan** [comment]
`autoplay` option is for the whole autoplay function, so if it's `false`, there will not be a autoplay functin at all.
You can set `autoplayButtonOutput: false` to prevent the stop button been generated.
