### ISSUE TITLE
lazyload not working

### ISSUE THREAD

**Issue by michal-kubicki** [ganlanyuan/tiny-slider#335]
__Issue description__:  Lazyload option has no effect. `autoplayTimeout` set to 8000.

`lazyload: enabled`
![lazyload enabled](https://i.imgur.com/tqNTLpv.jpg)

`lazyload:disabled`
![lazyload enabled](https://i.imgur.com/RZq9L01.jpg)

lazyload demo link (in your doc) is broken.

__Demo link/slider setting__:   http://devhub.be/tiny-slider/

_Tiny-slider version_:   2.8.8
_Browser name && version_:  Firefox, Chrome, Edge
_OS name && version_:   Windows 10

**Comment by ganlanyuan** [comment]
In your demo, seems you already set `src` to the img source.

**Comment by michal-kubicki** [comment]
Can you please provide a bit of doc about how to properly use lazyload?

**Comment by ganlanyuan** [comment]
You can use data-srcset instead of srcset
