### ISSUE TITLE
In strict mode code, functions can only be declared at top level or immediately within another function

### ISSUE THREAD

**Issue by gsmeira** [ganlanyuan/tiny-slider#336]
__Issue description__:  The slider is working fine, but when I try to build with webpack in production mode I'm getting this error bellow:

ERROR in 62.9c41c87ccfbd7a77606b.js from UglifyJs
In strict mode code, functions can only be declared at top level or immediately within another function. [./node_modules/tiny-slider/src/tiny-slider.js:758,0][62.9c41c87ccfbd7a77606b.js:6177,6]

Any ideas?

__Demo link/slider setting__:  -

_Tiny-slider version_: 2.8.8
_Browser name && version_:  -
_OS name && version_:  Ubuntu 18.04.1 LTS

**Comment by FlorianKoerner** [comment]
Created a merge request for this: #337

**Comment by santamaria7** [comment]
@FlorianKoerner  I just installed it via npm and the problem still exists.

**Comment by FlorianKoerner** [comment]
@santamaria7 The fix has not yet been published. Did you replace the line in packages.json with the pull request?

```
    "tiny-slider": "https://github.com/FlorianKoerner/tiny-slider.git",
```

**Comment by santamaria7** [comment]
@FlorianKoerner  Actually no. I'll make the changes now. Thanks for your quick feedback.

**Comment by ganlanyuan** [comment]
Please check if [this](https://github.com/ganlanyuan/tiny-slider/commit/2e7d88d4897da4085f9fd314f35c7ddb53e2d6ae) fix the issue.

**Comment by FlorianKoerner** [comment]
Should work, too.

**Comment by VadimZvf** [comment]
Same error
i use:
```
    "tiny-slider": "^2.8.8"
    "webpack": "^4.20.2"
    "uglifyjs-webpack-plugin": "^2.0.1",
```
npm versions 5.6.0 and 6.5.0

Solved the problem by adding external tiny-slider script.
