### ISSUE TITLE
ES6 modules in src

### ISSUE THREAD

**Issue by scabbiaza** [ganlanyuan/tiny-slider#338]
Hi! Non-standard syntax (ES6 imports) in `package.json:main`  is an antipattern. It may work well in modern browsers but it breaks other things: tests, SSR, etc. Yes, Babel can be configured to transpile `node_modules` but it leads to super slow builds so it discouraged as a go-to practice, especially  for libraries. Can you reconsider linking to `src` in `package.json:main` and distribute commonjs / es2015 instead?

https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages

> There are many issues with shipping uncompiled proposal syntax (this post was inspired by Dan's concern about this).

**Comment by ganlanyuan** [comment]
@scabbiaza Thanks, just updated in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/8e10b488c19f59ef9ba09eda7357a1b442970edb)
