### ISSUE TITLE
Custom navigation block - getInfo > index not correct

### ISSUE THREAD

**Issue by paulhuisman** [ganlanyuan/tiny-slider#339]
I am trying to add a custom navigation block with index / total items count indicator.

I'm using `slider.getInfo();`.

This returns `info.index`. However this is not always the correct index. For example, if my slider contains 2 items this will return info.index = 2 after initiating the slider.

My `startIndex` is 0.

Using version `2.8.8`.

**Comment by ganlanyuan** [comment]
You could use `displayIndex` instead. Refer to [here](https://github.com/ganlanyuan/tiny-slider#methods)
