### ISSUE TITLE
Lazyloading 1 too many slides

### ISSUE THREAD

**Issue by mollylentz** [ganlanyuan/tiny-slider#343]
__Issue description__:  Only truly visible in Internet Explorer - you will see the flash of 1 slide that should not be lazyloading but it does because the amount visible is being incorrectly calculated.

_Tiny-slider version_:   2.8.8
_Browser name && version_:  happening in all browsers

Easy fix -- in the "getVisibleSlideRange()" function, 
end = start + items; 
needs to be changed to: 
end = (start + items) -1;
start variable is set to "0", not "1" so the actual amount for end needs to remove one. Fixes the issue for me.

**Comment by ganlanyuan** [comment]
This function has been totally rewritten, please check the latest commit to see if the issue still happens.
