### ISSUE TITLE
Test page reporting Cannot GET /tests/tests.html

### ISSUE THREAD

**Issue by mac9416** [ganlanyuan/tiny-slider#358]
__Issue description__:  

After running `docker-compose up` and making changes per CONTRIBUTING.md, localhost:3000/tests/tests.html reports "Cannot GET /tests/tests.html".

I'm not sure what I should be seeing there. I'm unfamiliar with Docker, so I probably set something up incorrectly. Probably just need a tweak to CONTRIBUTING.md to clarify.

Thanks!

_Tiny-slider version_:   2.9.1
_Browser name && version_:  Chrome 71
_OS name && version_:   Windows 10

**Comment by przemkow** [comment]
I found the same problem, any hint on how to fix that?   

_Tiny-slider version_: 2.9.1
_Browser name && version_: Chrome 71
_OS name && version_: macOS 10.14.3

**Comment by hstruebe** [comment]
I'm having the same problem with Linux. 

_Tiny-slider version_: 2.9.1
_Browser name && version_: Chrome 71
_OS name && version_: ubuntu 18.10

**Comment by ganlanyuan** [comment]
Thanks @hstruebe 
Just merged
