### ISSUE TITLE
README section 'options' as table

### ISSUE THREAD

**Issue by S1SYPHOS** [ganlanyuan/tiny-slider#37]
As proposed, I want to rework the options section as table for easier understanding and quicker overview of all features & possibilities (thus making it an enhancement of some sort), like this:

| Option | Type | Description |
| --- | --- | --- |
| `fixedWidth` | Boolean | Default: `false`. Controls `width` attribute of the slides. |
| `items` | Integer | Default: `1`. Number of slides being displayed. |
| and so on ... |

If I run into any problems or if I can't figure out the purpose of individual options, I'll ask you here so I can instantly include your information.

Cheers,
S1SYPHOS

**Comment by S1SYPHOS** [comment]
Question 1:
What exactly does `controlsContainer`? I always get this: `TypeError: Ne.children is undefined`, doesn't matter if it's a `class` or `id` name, selector or whatever :face_with_head_bandage:

**Comment by ganlanyuan** [comment]
"controlsContainer" is the element which wraps previous button and next
button, for instance document.querySelector(".controls").  This option is
for customizing "controls".

**Comment by ganlanyuan** [comment]
Great, go ahead!

**Comment by S1SYPHOS** [comment]
Commit incoming in my fork, check it out and let me know any comments!

**Comment by ganlanyuan** [comment]
> Question 2:
When I go false on autoplay, there's no autoplay navigation. If it's true, but nav set to false, nothing changes. So what's the logic behind nav? People want to know I want to know!

`nav` buttons and `autoplay` button are both in `navContainer` Node. (I'm not sure if they should be in their own containers)   
When `nav` set to `false` while `autoplay` set to `true`, the `navContainer` will be generated with `autoplay` button in it but no `nav` buttons.

**Comment by ganlanyuan** [comment]
I just updated the README: options field, please let me know if there is anything unclear.

With the table, it's much more easier to understand now.
Thank you so much for helping with this!!!

**Comment by S1SYPHOS** [comment]
Not sure if that's maybe overly complicated, I'll think about it. For
the time being, I'm glad to help!
