### ISSUE TITLE
Reorder HTML elements

### ISSUE THREAD

**Issue by xyzajacf** [ganlanyuan/tiny-slider#393]
Hello,

Is it possible to re-order HTML elements, so the tns-ovh will be above tns-nav?
Currently, the structure is:

- tns-controls
- tns-nav
- tns-ovh

I would prefer to have elements in the following order:

- tns-ovh
- tns-controls
- tns-nav

I need to put tns-nav element below the slider. However, the current solution is only absolute positioning, which requires a bunch of CSS lines to make it work.
The more elegant solution will allow me to reorder elements in HTML markup.

**Comment by ganlanyuan** [comment]
There are [options](https://github.com/ganlanyuan/tiny-slider#options) for that.
You can set `navPosition: 'bottom'` and `controlsPosition: 'bottom'`.
