### ISSUE TITLE
Implement acessibility features

### ISSUE THREAD

**Issue by DouglasdeMoura** [ganlanyuan/tiny-slider#4]
Please check the page below:

https://www.w3.org/WAI/EO/Drafts/tutorials/sliders/

**Comment by ganlanyuan** [comment]
Will check this, thanks

**Comment by ganlanyuan** [comment]
Tiny-slider is still in progress right now, please give more ideas if possible.
Thanks

**Comment by epigeyre** [comment]
This series of articles offer a nice sum up of accessibility best practices for carousels: 

- [Part 1](http://mmckinnon.com/blog/2015/accessible-carousels-part-1)
- [Part 2](http://mmckinnon.com/blog/2015/accessible-carousels-part-2)
- [Part 3](http://mmckinnon.com/blog/2015/accessible-carousels-part-3)

I thought this might help your script even better!

**Comment by ganlanyuan** [comment]
Great, thanks

**Comment by ganlanyuan** [comment]
Hey,
Accessibility features added. Could you check?
Only for touch screen I can't figure out how to support. Any idea?

**Comment by epigeyre** [comment]
Thanks, I will check as soon as I can and get back to you!

**Comment by epigeyre** [comment]
Hello,

Sorry it's been so long! So I had time to check and here is my feeback:

- **aria-hidden** -> OK.
- **aria-controls** -> On the carousel pagination, if the number of items is set to more than one, the `aria-controls` value doesn't reflect this setting (it's selecting the next one instead of the `n + 2` if we set `items` value to `2`.
- **aria-selected** -> OK.
- **Content order** -> From an accessibility stand point, it makes more sense to have navigation and pagination above carousel.
- **Limiting tab selection** -> `tabindex="-1"` should be added to every inactive slide.
- **Navigation keyboard control** -> Add `tabindex="0"` to the Carousel navigation container and `tabindex="-1"` on both carousel navigation buttons.
- **aria-live** -> In my opinion it depends too much on the purpose of the carousel to be implemented in a global solution.

Hope this helps!

**Comment by ganlanyuan** [comment]
Thanks @epigeyre for your feedback.
I will check these when I have time.

**Comment by ganlanyuan** [comment]
> - **Content order** -> From an accessibility stand point, it makes more sense to have navigation and pagination above carousel.

Will update in next main version, since this change will cause a DOM change.

> - **Limiting tab selection** -> `tabindex="-1"` should be added to every inactive slide.
> - **Navigation keyboard control** -> Add `tabindex="0"` to the Carousel navigation container and `tabindex="-1"` on both carousel navigation buttons.

Done

**Comment by ganlanyuan** [comment]
> - **aria-controls** -> On the carousel pagination, if the number of items is set to more than one, the `aria-controls` value doesn't reflect this setting (it's selecting the next one instead of the `n + 2` if we set `items` value to `2`).

Will work on this maybe this weekend.

**Comment by ganlanyuan** [comment]
> - **Content order** -> From an accessibility stand point, it makes more sense to have navigation and pagination above carousel.

This will be done from v2.0

**Comment by Eric-Draven** [comment]
How to place navigation and pagination under carousel?

**Comment by epigeyre** [comment]
@Eric-Draven The best way is probably to use `position: relative` on your slider's wrapper and `position: absolute` on your navigation and pagination elements so that you can place them wherever you want.

**Comment by Eric-Draven** [comment]
Thank you, I know this, but it would be nice to be able to change through the options.

**Comment by OD-fraja** [comment]
@ganlanyuan @epigeyre Regarding tabindex="0" on the controls container what was the reason behind it? Is that really needed? We use a company to audit our site and they logged this as an issue that tabindex="0" causes and extra tab which is not needed.

**Comment by ganlanyuan** [comment]
@OD-fraja So that it can be focused (instead of prev, next button been focused) and user can control the slider using arrow keys.

**Comment by OD-fraja** [comment]
@ganlanyuan Aha I see, makes sense. I did not know that you could use arrow keys to control the slider. That makes sense now. Thanks for your prompt reply.

**Comment by ganlanyuan** [comment]
@OD-fraja You're welcome

**Comment by missmatsuko** [comment]
>> Limiting tab selection -> tabindex="-1" should be added to every inactive slide.
>> Navigation keyboard control -> Add tabindex="0" to the Carousel navigation container and tabindex="-1" on both carousel navigation buttons.

> Done

I'm just checking out the sliders on the demo page. I can see that the tabindex is set as described above, but I still can't seem to tab past a carousel without going through each slide. Is some JS that is programmatically focusing the inactive slides on tab?

**Comment by ganlanyuan** [comment]
@missmatsuko Hey, it's because of the `<a>` tag in each slide.

**Comment by missmatsuko** [comment]
@ganlanyuan Hmm, I see. I think the content inside the inactive slides really shouldn't be focusable, even if they have links in them.

**Comment by ganlanyuan** [comment]
You're right.
But it's too much for the slider to check all [the possible focusable child elements](https://gist.github.com/jamiewilson/c3043f8c818b6b0ccffd) of inactive slides and make them non-focusable.   
I will search for ways which just need to work on the slides themselves.

**Comment by nickblass** [comment]
The problem we're having with this, is that we are lazy loading the images so if we tab through and the images haven't loaded (which a user may do), then it shows an invalid image which is not ideal. I have went ahead and targeted our links and disabled the tab index just so this does not occur. However, I think it would provide a better UX if the tab index was only enabled for elements within the visible slide?

**Comment by camtin** [comment]
Hi, I think it might be reasonable to check for focusable child elements, and make them both tabindex -1.  A technique I've seen used is to store the element's previous tabindex value in a data attribute, and "restore" it from that attribute when it's visible again.  I'm going to open this up as a separate new issue and attempt to fix on my own fork.

**Comment by tombassrosenfeld** [comment]
@ganlanyuan @epigeyre the tabindex= -1 is causing issues if using navigation arrows outside of the nav container (setting custom prevButton and nextButton). Is there a way to only set tabindex= -1 if the nav is set to true?
