### ISSUE TITLE
Issue: when i used custome arrow

### ISSUE THREAD

**Issue by krishkajal** [ganlanyuan/tiny-slider#40]
Hi, 
I found one issue slider not working once you reached in last slide and again click on next after then slider doesn't work.

my code is: 
var slider = tns({
		    	container: document.querySelector('.slider'),
		    	items: 1,
		    	controlsText: ['', ''],
				loop: false,
				speed: 250,
				autoplay: false,

				controlsContainer: document.querySelector('.customize-tools .controls') 	    
	       }); 

can u please look this issue.

Thanks

**Comment by ganlanyuan** [comment]
Hi,
That's expected, cause you set "loop: false". You can fix it by either
removing "loop: false" (default is true) or adding "rewind: true" while
"loop" is not "true".
