### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by bobmitro** [ganlanyuan/tiny-slider#401]
Hello William,

Just want to say: Thank you for your great project and your work. 
The Tiny slider is really awesome, I use it in many projects and at this moment I do not see a better slider script: is fast, little resource-consuming and comes with many configuration options. 

Once again thank you and keep your great work.

**Comment by ganlanyuan** [comment]
@bobmitro Thank you for letting me know this! 
I feel so sorry that I couldn't check issues and PRs for almost one year while focusing on my work.
Will definitely continue to work on it for improvements.
