### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by soulessvadi** [ganlanyuan/tiny-slider#405]
__Issue description__:  slider not working at all

__Demo link/slider setting__:   
[https://z3ddota.com/](url)
var container = document.querySelector('.app-home-carousel');
	var homeslider = tns({
	    "container": container,
	    "mode": 'carousel',
	    "loop": true,
	    "item": 1,
	    "nav": false,
	    "controls": false,
		"swipeAngle": false,
		"speed": 1000,
		"autoplay": false,
		"autoplayHoverPause": true,
		"autoplayTimeout": 5500,
	});

_Tiny-slider version_:   2.0
_Browser name && version_:  Internet Explorer 11
_OS name && version_:  Windows 10

**Comment by robskrob** [comment]
@soulessvadi is there any reason why this issue was closed? I'm having issues as well with Internet Explorer (IE11) -- the slider is not rendering at all.

**Comment by shivani-bisht** [comment]
I'm also facing **slider not working at all** issue in IE 11.
Please open this issue.
Thanks

**Comment by camilla-westin** [comment]
Any fix for this? Have the same issue.

**Comment by loadbrain** [comment]
Hello,
maybe it helps...
I had also problems with IE 11.
My solution was to fix this function in tiny-slider.js:
`function getSlideMarginLeft(i) {
          return CALC ? CALC + '(' + i * 100 + '% / ' + slideCountNew + ')' : (i * 100) / slideCountNew + '%';
    }`

by either commenting out (did anyway work on all browser) or by this:
`function getSlideMarginLeft(i) {
      if (!tnsStorage['tnsApp']) {
        return CALC ? CALC + '(' + i * 100 + '% / ' + slideCountNew + ')' : (i * 100) / slideCountNew + '%';
      }
      //   return CALC ? CALC + '(' + i * 100 + '% / ' + slideCountNew + ')' : (i * 100) / slideCountNew + '%';
    }`
