### ISSUE TITLE
Please, provide EXACT markup examples of each of the demos ...

### ISSUE THREAD

**Issue by blaasvaer** [ganlanyuan/tiny-slider#418]
It's way to hard to guess what mark up to use in each of the demos. Like HOW do I use the customize version? What markup? I can see the first image and then a 'link' that says "stop" and when I click it it changes to "start". Fine, but nothing happens ... ?

**Comment by ganlanyuan** [comment]
Markup is very straightforward, simply: `div>div` or `ul>li` as instructed in the [Usage](https://github.com/ganlanyuan/tiny-slider#usage), you can even do `div>p`.
```
<div class="your-slider">
  <div>
    <!-- slide item -->
  </div>
  <div>
    <!-- slide item -->
  </div>
  <div>
    <!-- slide item -->
  </div>
  <div>
    <!-- slide item -->
  </div>
  <div>
    <!-- slide item -->
  </div>
</div>
```

Other than this, if you need customize `nav`, `controls` or other elements, simply add your markup outside `<div class="your-slider"></div>`, and refer it in your slider settings.
For lazyload images, refer to [Options](https://github.com/ganlanyuan/tiny-slider#options).

For the demos, you could always check the source code.
Let me know if this is still not clear to you.
