### ISSUE TITLE
Cange number of items with matchMedia

### ISSUE THREAD

**Issue by epigeyre** [ganlanyuan/tiny-slider#42]
**EDIT: Ok I feel stupid, there's a feature for that... problem solved!**

---
Hello,

I am trying to change the number of items depending on screen width with matchMedia but I can't make it work.

Here is my code for the matchMedia:

    var mqls = [
        window.matchMedia("(min-width: 650px)"),
	window.matchMedia("(min-width: 1200px)")
    ]

    function mediaqueryresponse(mql) {
	if (mqls[0].matches) { 
	    var nbItems = 2
	} else if (mqls[1].matches) {
	    var nbItems = 3
	} else {
	    var nbItems = 1
	}
    }

    for (var i=0; i<mqls.length; i++) {
        mediaqueryresponse(mqls[i]),
        mqls[i].addListener(mediaqueryresponse)
    }

But then I have no idea how to get it to work with tiny-slider. As there is a responsive feature, can we hook into the event listener directly?

**Comment by ganlanyuan** [comment]
Currently there is no way to pass different options to tiny-slider except
the "responsive" option.

>
