### ISSUE TITLE
Install Parse Error

### ISSUE THREAD

**Issue by galaktuz** [ganlanyuan/tiny-slider#423]
__Issue description__:  install error if module by npm 
If to install slider 

```
import { tns } from '../../node_modules/tiny-slider/src/tiny-slider';

var slider = tns({
    container: '.my-slider',
    items: 3,
    slideBy: 'page',
    autoplay: true
  });
```
error 
**import './helpers/Object.keys';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'**

__Demo link/slider setting__:   default

_Tiny-slider version_:   2.9.2
_Browser name && version_:  Google Chrome Version 72.0.3626.121 (Official Build) (64-bit)
_OS name && version_:   Windows 7

**Comment by ganlanyuan** [comment]
Thanks.
Fixed in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/d4e6e6f01958855ef127add0f395a38c99e9fd60).
