### ISSUE TITLE
Remove debug in prod code

### ISSUE THREAD

**Issue by MathRobin** [ganlanyuan/tiny-slider#424]
There is some debug code in minified code which is just here for debug

Code is here :
https://github.com/ganlanyuan/tiny-slider/blob/master/src/tiny-slider.js#L970

Shouldn't just be hidden by `.tns-visually-hidden` but really not present. Not necessary.

_Tiny-slider version_:   2.9.x

**Comment by ganlanyuan** [comment]
Live region is not for debugging actually.
It's for accessibility and in some case can also be visible.
But thanks for point out the typo
