### ISSUE TITLE
Issues when importing via Browserify

### ISSUE THREAD

**Issue by lalarco** [ganlanyuan/tiny-slider#43]
I guess this is the same problem as issue #20 but since it´s close and seems to work for webbpack I wrote it a new one for browserify. The fix in #39 was working but the #41 made it throw error message again as before: SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

**Comment by ganlanyuan** [comment]
Hey @lalarco , I found a solution [here](http://stackoverflow.com/questions/30386317/babelify-throws-parseerror-on-import-a-module-from-node-modules#30386405).

I did the following steps:
- `npm install -g browserify`  
`npm install --save-dev babelify`  
`npm install --save-dev babel-preset-es2015`  
- add the following code to package.json:
```
"browserify": {
  "transform": [
    "babelify"
  ]
},
```
- add a .babelrc file at root directory with the following code:
```
{
  "presets": ["es2015"]
}
```
- then do `browserify -t babelify js/main.js -o js/bundle.js`

And it works. The main.js file with its dependent files were bundled to bundle.js file and `tiny-slider` worked as expected.

You can view the code [here](https://github.com/ganlanyuan/tiny-slider-browserify-demo).  Please let me know if this works for you.
Thanks
