### ISSUE TITLE
Flickering effect on load

### ISSUE THREAD

**Issue by snnsnn** [ganlanyuan/tiny-slider#438]
All slides are visible from the point when page loads until the slider becomes active, which causes a flickering effect. Owl slider hides all slides until slider becomes active and shows only active slide then on. It is a css issue and I tried to come up with a solution in tiny-slider.scss but alas, couldn't figured out the right place to hide all slides and show active one only.

**Comment by deronjohnson** [comment]
One way you could solve this problem is by setting the opacity of your slider to `0` and then use tiny-slider's `onInit` function to add a css class to the slider that sets the opacity back to `1` once the slider is fully loaded.

**Comment by BrianBrainRocks** [comment]
@snnsnn After implementing fadeIn/fadeOut for my gallery I realized the conflict is between my opacity transition and `.tns-gallery > .tns-item` under [./src/tiny-slider.scss#L60](https://github.com/ganlanyuan/tiny-slider/blob/master/src/tiny-slider.scss#L60)
I fixed overriding the rule, like:
```
  /* Opacity causes animation conflict with Animate.css */
.tns-gallery > .tns-item {
  -webkit-transition: transform 0s;
  -moz-transition: transform 0s;
  transition: transform 0s;
}
```

**Comment by pySilver** [comment]
This is what I'm using:

```scss
// Prevent flickering during initialization
.your-slider-class {
  opacity: 0;

  &.tns-slider {
    opacity: 1;
  }
}
```

**Comment by hosseinhajimali** [comment]
thanks to @pySilver solution:
```
.your-slider-wrapper:not(.tns-slider){
    height: 100px;  // to keep height as short as loaded slider
    opacity: 0;
}
```
