### ISSUE TITLE
Tiny-Slider Images Cut off

### ISSUE THREAD

**Issue by vishy93** [ganlanyuan/tiny-slider#440]
__Issue description__:  

I cam across this plugin via OWLCarousel 2 where they recommend this plugin. However, I cannot get it to work, the images in the slide do not respect the boundary of the slideshow and cut off. How can I get it to work as I had with OWLCarousel2? whereby, the images are full width, scaled down to fit within width?

__Demo link/slider setting__:   [Owl Implementation](https://codepen.io/vishpatel93/pen/gzzpjY)/[tiny-slider Implementation](https://codepen.io/vishpatel93/pen/KOmOVK)

_Tiny-slider version_:  Latest
_Browser name && version_:  Chrome Latest

**Comment by marasi** [comment]
Hi, I am having the same issue. How do you solved?

**Comment by vishy93** [comment]
@marasi I forgot to add this css:

`img{
  display: block;
  max-width: 100%;
}
.tns-item img {
	display:block;
	width:100%;
}`
