### ISSUE TITLE
is it possible to have different modes on responsive?

### ISSUE THREAD

**Issue by Apu889** [ganlanyuan/tiny-slider#441]
__Issue description__:  
example `mode: 'gallery'` at initial and `mode: 'carousel'` when on `responsive` mode

_Tiny-slider version_:   2.9.1
_Browser name && version_:  Chrome 75
_OS name && version_:   MacOS Mojave v10.14.5

**Comment by ganlanyuan** [comment]
Changing `mode` is too complicated, I won't add this feature.
But you can do `destroy()` and then build it with new options.
