### ISSUE TITLE
number of the slide

### ISSUE THREAD

**Issue by AnthonySGeorge** [ganlanyuan/tiny-slider#448]
__Issue description__:  
Can you tell me how to show the number of the slide below the slider?

__Demo link/slider setting__:   

_Tiny-slider version_:   v2.9.1
_Browser name && version_:  n/a
_OS name && version_:   n/a

**Comment by ganlanyuan** [comment]
There is a `.tns-liveregion` element in the slider tells user which slide is currently active. 
You could remove class "tns-visually-hidden" or update CSS to make it visible.

**Comment by florianbouvot** [comment]
@ganlanyuan is there a way to translate `.tns-liveregion` content?

**Comment by DmitriyKurto** [comment]
@AnthonySGeorge and @ganlanyuan Also You can use [.getInfo()](https://github.com/ganlanyuan/tiny-slider#getinfo) and show the information you need where you need it.

**Comment by albanyacademy** [comment]
Would be nice for the "slide" part of the text to be a configurable keyword. E.g. Video 1 of 4, Hilarious Joke 0 of 0, etc.

As it stands I just need it removed so I guess getInfo() is my only option - modifying the content trips up getLiveRegionStr() and it never updates, as it's looking for an exact match on the innerHTML.

**Comment by entozoon** [comment]
`.tns-liveregion` is like, completely wrong. At least, for display purposes.
I've had success going down this route:
```js
slider.events.on("translationEnd", data => {
  let { controlsContainer, displayIndex, slideCount } = data;
  console.log(`${displayIndex} / ${slideCount}`;);
  // Create an element and inject this into the controlsContainer (or update it thereafter)
});
```
