### ISSUE TITLE
Are you kidding?

### ISSUE THREAD

**Issue by DimaGashko** [ganlanyuan/tiny-slider#463]
I think, you forgot something.. :)

![image](https://user-images.githubusercontent.com/20650419/65055423-ccb10680-d977-11e9-9763-4c2fb9a08215.png)

![image](https://user-images.githubusercontent.com/20650419/65055585-1f8abe00-d978-11e9-873e-de09c7ce71eb.png)

![image](https://user-images.githubusercontent.com/20650419/65055618-316c6100-d978-11e9-97d5-092e68dcec1d.png)

![image](https://user-images.githubusercontent.com/20650419/65056798-33cfba80-d97a-11e9-8214-bc9ba386e980.png)

**Comment by Kcharle** [comment]
@DimaGashko why not make a PR into the repo instead of making an issue with a salty title :)

**Comment by DimaGashko** [comment]
@Kcharle unfortunately, I don't have time enough for that

**Comment by ganlanyuan** [comment]
Oh, my bad.
Just fixed it in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/f6cbe5d8bcc56213daed8c07e94f40602341811d)
Thank you @DimaGashko
