### ISSUE TITLE
Nav not displayed on initial load if items = 1

### ISSUE THREAD

**Issue by davepenfold** [ganlanyuan/tiny-slider#47]
If the `items` property is set to `1` it seems that the nav is not displayed on initial load. If I have a Slider which displays 1 item at a time, I still want to see the nav. I think this might be a bug, I believe the following should be `items > 0` or `items >= 1` :

https://github.com/ganlanyuan/tiny-slider/blob/master/src/tiny-slider.js#L454

**Comment by ganlanyuan** [comment]
Thanks @davepenfold ,
This is fixed in the [the latest release](https://github.com/ganlanyuan/tiny-slider/tree/v1.5.4).
