### ISSUE TITLE
Best option to lazyload (start/stop) the entire slider when it is close to/far away from the viewport

### ISSUE THREAD

**Issue by JasonDuquain** [ganlanyuan/tiny-slider#476]
__Issue description__:  I am trying to use IntersectionObserver to only autoplay/start/play the slider when it is close to or inside the viewport. Once a user scrolls past it then the slider will disable/pause/stop. I am testing this with setTimeout and have tried the following:

1. using slider.disable

INITIAL SETTINGS:

var slider = tns({
    container: '.testimonial__flex',
    controlsContainer: document.querySelector('.customize-controls'),
    preventScrollOnTouch: 'auto',
    autoHeight: true,
    items: 1,
    slideBy: 'page',
    center: true,
    mouseDrag: true,
    arrowKeys: true,
    autoplay: true,
    autoplayTimeout: 10000,
    autoplayButton: false,
    autoplayButtonOutput: false,
    **disable: true**
});

setTimeout(() => {
	**slider.disable = false;**
	slider.play(); /* I have also tried without this but added just to try it  */
        **console.log(slider.disable) // outputs false but the slider never auto starts**
}, 20000);

2. using slider.play() and slider.pause() **I believe these are only related to when a user is hovering one of the slides but still wante to try it**

INITIAL SETTINGS:

var slider = tns({
    container: '.testimonial__flex',
    controlsContainer: document.querySelector('.customize-controls'),
    preventScrollOnTouch: 'auto',
    autoHeight: true,
    items: 1,
    slideBy: 'page',
    center: true,
    mouseDrag: true,
    arrowKeys: true,
    **autoplay: false,**
    autoplayTimeout: 10000,
    autoplayButton: false,
    autoplayButtonOutput: false,
    disable: false
});

setTimeout(() => {
	slider.autoplay = true; 
        slider.play(); **again I tried with and without this line**	
}, 20000);

3. I also tried a similar approach toggling slider.isOn from false to true with no luck

Any ideas and how to accomplish this would be greatly appreciated

_Tiny-slider version_:   2.9.1
_Browser name && version_:  Google Chrome 77.0.3865.90
_OS name && version_:   Windows 10 Professional

**Comment by frontendRubbish** [comment]
Hm,

don't ask me why, but it seems like the slider cannot be stopped when autoHeight is set to true... something like this should work:

var slider = tns({
container: '#slider',
preventScrollOnTouch: 'auto',
items: 1,
slideBy: 'page',
center: true,
mouseDrag: true,
arrowKeys: true,
autoplay: true,
autoplayTimeout: 1000,
autoplayButton: false,
autoplayButtonOutput: false
});

//Initially stop slider
slider.pause();

setTimeout(() => {
  console.log('go play');
  slider.play(); 
}, 7000);

**Comment by JasonDuquain** [comment]
Thank you! Sorry for the late reponse but that did it. And I don't think I would have ever figured that out. Right now no issues with autoHeight when testing at different breakpoints. Marking as closed.
