### ISSUE TITLE
[data-tns-role=nav] buttons

### ISSUE THREAD

**Issue by persianturtle** [ganlanyuan/tiny-slider#48]
I noticed an issue with the nav buttons when using 7 elements within a 4 item slider.  When clicking on the second nav button, the wrong button gets the aria-selected="true" attribute.

Here is a codepen to see the issue: https://codepen.io/anon/pen/OgxxdJ

To reproduce the bug (using a viewport >1200px wide):

1. click on the second nav button
2. notice that the button _after_ gets the aria-selected="true" attribute

Note:  This issue only exists the first time navigating the slider.  Clicking on the second nav button and then the first, and then the second again seems to work just fine since the second button nicely gets the aria-selected="true" attribute.

If you would like me to submit a PR for this, please let me know and I'll do my best.

**Comment by persianturtle** [comment]
Update:

The bug does not occur when the `rewind` property is set to `false`.

**Comment by ganlanyuan** [comment]
Hey @persianturtle , I will check this issue today.

**Comment by ganlanyuan** [comment]
The [latest release](https://github.com/ganlanyuan/tiny-slider/releases/tag/v1.5.6) fixed this issue, could you check?
Codepen: https://codepen.io/ganlanyuan/pen/VWMNmK

**Comment by persianturtle** [comment]
@ganlanyuan Works great.  Thank you!

**Comment by ganlanyuan** [comment]
You're welcome
