### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by cvaize** [ganlanyuan/tiny-slider#485]
![image](https://user-images.githubusercontent.com/26907947/67090948-c1ded100-f1c4-11e9-8e42-f227b1965bb7.png)
![image](https://user-images.githubusercontent.com/26907947/67090981-d91dbe80-f1c4-11e9-9ee3-8fbce45cf6db.png)
![image](https://user-images.githubusercontent.com/26907947/67090986-dfac3600-f1c4-11e9-8173-85d78a7fb591.png)
`import { tns } from 'tiny-slider/src/tiny-slider'

export default function () {
  const roadMap = tns({
    container: '#road-map',
    gutter: 43,
    items: 5,
    autoWidth: true,
    mouseDrag: true,
    loop: false,
    nav: false,
    controls: false,
  });
  const prev = document.getElementById('road-map-prev')
  const next = document.getElementById('road-map-next')
  const roadMapIW = document.getElementById('road-map-iw')
  const item = document.querySelectorAll('#road-map .tns-item')
  prev.addEventListener('click', () => {
    if(!prev.disabled){
      roadMap.goTo('prev')
    }
  })
  next.addEventListener('click', () => {
    if(!next.disabled){
      roadMap.goTo('next')
    }
  })
  roadMap.events.on('indexChanged', (v) => {
    let index = v.displayIndex - 1
    let fullWidth = 0
    let offsetWidth = 0
    item.forEach((value, index2) => {
      fullWidth += value.offsetWidth
      if(index2 < index){
        offsetWidth = fullWidth
      }
    })
    prev.disabled = (index === 0)
    next.disabled = (fullWidth - offsetWidth < roadMapIW.offsetWidth)
  });
}`

**Comment by FateXRebirth** [comment]
Adding preventScrollOnTouch: 'auto' to options when calling tns will fixed this issue.

**Comment by craigdg** [comment]
Can we re-open this? The above solution doesn't work in TypeScript.

**Comment by yizdesign** [comment]
`preventScrollOnTouch: 'force'` works for me

**Comment by HorstBrack** [comment]
preventScrollOnTouch: '<anything>' does not work with Typescript.
It will produce the error
`Argument of type '{ container: string; loop: false; swipeAngle: false; touch: true; mouseDrag: true;
  arrowKeys: false; speed: number; mode: "gallery"; nav: false; preventScrollOnTouch: string;
  controlsContainer: string; }' is not assignable to parameter of type 'TinySliderSettings'`
