### ISSUE TITLE
Auto height resizing

### ISSUE THREAD

**Issue by epigeyre** [ganlanyuan/tiny-slider#5]
I've been testing your script and it's really great (I like when there ar not too much functions)! The only thing missing is to be able to resize the container's height based on its content. Do you plan on implementing this function?

Thanks!

**Comment by ganlanyuan** [comment]
Thanks!
Yes, probably will add this function in future versions.

**Comment by epigeyre** [comment]
Sweet, thanks! Could you add an unminified version of your script so that I can learn from your code and try to implement the function by myself?

**Comment by ganlanyuan** [comment]
Sure!
I will let you know once it's added.

**Comment by epigeyre** [comment]
Awesome, thanks!

**Comment by ganlanyuan** [comment]
Hey,
The [uncompressed version](https://github.com/ganlanyuan/tiny-slider/blob/master/dist/tiny-slider.src.js) is added.

**Comment by epigeyre** [comment]
Wicked! Thanks a lot!!

**Comment by ganlanyuan** [comment]
Hey,
`autoHeight` function is added, please check [this commit](https://github.com/ganlanyuan/tiny-slider/commit/33d697fef844e50abf4fb88f942be81f57741fdf).

**Comment by epigeyre** [comment]
Awesome, thanks à lot!!

**Comment by ganlanyuan** [comment]
Hey,
Does the `autoHeight` works for you? If it's okay, I will close this issue.
Thanks

**Comment by epigeyre** [comment]
It's working perfectly! I've tested IE9+ and modern browsers, it's perfect. Thanks again, I really appreciate what you do for the web dev community!
