### ISSUE TITLE
Event listener not working with content added through AJAX

### ISSUE THREAD

**Issue by epigeyre** [ganlanyuan/tiny-slider#51]
Hello,

I am new to AJAX and trying to understand what's going on here. My slider is added to the DOM with an AJAX call so I'm trying to initialized the script after the content has been added. Right now I just append the script with the following code:

```
var code = "var slider = tns({items: 1, slideBy: 'page', container: document.getElementsByClassName('slider')[0], nav: true, arrowKeys: true, loop: false, rewind: true, touch: true});";
var script = document.createElement("script");
script.setAttribute("type", "text/javascript");
script.appendChild(document.createTextNode(code));
document.body.appendChild(script);
```

The problem is that everything is working except the click events. I've read a bit about event delegation but I am not sure how to implement it with Tiny Slider, could you point me in the right direction?

Thanks a lot!

**Comment by ganlanyuan** [comment]
Hey, could you make a sample page?

**Comment by epigeyre** [comment]
Thanks for your answer! I've set up a Codepen but can't reproduce the issue so I guess it has nothing to do with Tiny Slider, I'll have to digg deaper... You can close the issue. Thanks anyway for your quick answer!
