### ISSUE TITLE
control buttons doesn't work after swipe / at loop: false

### ISSUE THREAD

**Issue by octojoerg** [ganlanyuan/tiny-slider#52]
Hey, I found 2 problems with control buttons.

1. After swiping with fingers on mobile devices the contol buttons seem not to work. However, after page reload and without swiping control buttons work fine.

2. When loop is deactivated, control buttons doesn't work.

I use webpack.

What could be wrong?

**Comment by ganlanyuan** [comment]
Hey, 
Is it possible to make a sample page?
Which device and browser you're using?
Could you check [this page](http://ganlanyuan.github.io/tiny-slider/tests/) on that device to see if the same issue happens?

**Comment by octojoerg** [comment]
Hey,

I guess I found the problem in my environment. I used to calculate the float-number dynamically for `fixedWidth` intern in my javascript... so after I set a static number for `fixedWidth` it did work...

I tested your test page and everything works well, so I think the problem is the dynamic calculating.

**Comment by ganlanyuan** [comment]
It's good that you fond the issue. 
Yes, `fixedWidth` should not be changed after the initialization.
