### ISSUE TITLE
Experiencing issues on Chrome version 80.0.3987.87

### ISSUE THREAD

**Issue by MartijnPol** [ganlanyuan/tiny-slider#536]
__Issue description__:  
For the past couple of weeks I'm working on a website using the tiny slider package. To my suprise, it broke my lay-out this morning once updated to Chrome version 80.0.3987.87.

Did anyone else run into this issue?

_Tiny-slider version_: 2.9.2
_Browser name && version_:  Chrome version 80.0.3987.87
_OS name && version_:  Windows 10 OS Version 1909 (Build 18363.592)

**Comment by martinshumberto** [comment]
It happened to me too.

**Comment by martinshumberto** [comment]
Contact me, but it has no relation to chrome, but the problem happens to me in the production mode of my application in dev mode works normal.

**Comment by martinshumberto** [comment]
150/5000
It happened to me, but it has no relation to chrome, but the problem happens to me in the production mode of my application in the dev mode works normal.

**Comment by martinshumberto** [comment]
It happened to me, but it has no relation to chrome, but the problem happens to me in the production mode of my application in the dev mode works normal.

**Comment by chrishenke** [comment]
I am experiencing the same issue in Chrome 80.0.3987.87 and Firefox 72.0.2.

**Comment by martinshumberto** [comment]
Estou com mesmo problema, Opera 66.0.3515.72.
Mas acredito que não seja o navegador o problema, teve atualizações de alguns pacotes bem comuns, alguns que percebi  "nodesass", "sass-loader" e outros. Não tenho certeza se a relação existe.
Você atualizaram pacotes da aplicação recentemente?

**Comment by martinshumberto** [comment]
I'm having the same problem, Opera 66.0.3515.72.
But I believe that the browser is not the problem, there were updates to some very common packages, some that I noticed "nodesass", "sass-loader" and others. I'm not sure if the relationship exists.
Have you updated application packages recently?

**Comment by MartijnPol** [comment]
Thanks voor your reply @martinshumberto 

I didn't updated any packages recently and I honestly don't think the packages are the issue. When I open the same site on both Chrome 79 and Chrome 80, the layout is broken on Chrome 80 while version 79 displays it correctly.

**Comment by martinshumberto** [comment]
How strange, here on my Chrome 79 is not working. @MartijnPol

**Comment by martinshumberto** [comment]
I discovered that our problems are not the same, it was incompatibility between dependencies, I already solved it.
Good luck to you.

**Comment by chrishenke** [comment]
My issue was due to an implied min-width on children of an element with display: grid. I was able to set a min-width: 0 on the direct descendants of my grid container and now the slider is able to set it's width correctly.

Are you using flex or grid in your layout @MartijnPol? If you are this fix might work for you too.

**Comment by MartijnPol** [comment]
Wow @chrishenke, I was indeed using grid and this fixes my issue! Thank you! 👏 I still find it interesting that an update of Chrome lead to this problem in the first place but this seems to solve it for now. Thanks again!
