### ISSUE TITLE
Problem with Slider FullWidth

### ISSUE THREAD

**Issue by xdasty** [ganlanyuan/tiny-slider#549]
__Issue description__:  
Hi Guys, I want to make a Full Width Slider
but after a few slides, the slider stops.
I post the code

Updates
- if items: 2 -> it works
- if items: 1 -> does not work

__Demo link/slider setting__:   
https://codepen.io/xdasty/pen/XWbNJaj

_Tiny-slider version_:   2.9.2
_Browser name && version_:  
_OS name && version_:

**Comment by AndrewBogdanovTSS** [comment]
Possible duplicate of #545

**Comment by xdasty** [comment]
Hi the problem was different,
I solved it

Place the link of the working script
https://codepen.io/xdasty/pen/gOpRawy

**Comment by AndrewBogdanovTSS** [comment]
What was it?
