### ISSUE TITLE
Slider is not working in carousel mode

### ISSUE THREAD

**Issue by Nomta** [ganlanyuan/tiny-slider#55]
Hi,
Thanks for this plugin. 
I have used it three times on one page. Items of two sliders are linked by goTo. However one of these two does not work sometimes. It is in carousel mode. The second one is always faultless. It's in gallery. 

The site is: https://olga-sergeeva.com/
Tiny-slider version:   1.5.3

**Comment by ganlanyuan** [comment]
Hi, could you update to 1.6.0 and check it again?

**Comment by Nomta** [comment]
I did, but without success...

**Comment by ganlanyuan** [comment]
Okay, may I know you slider settings?

**Comment by Nomta** [comment]
Ok,
...
      container: container,
      items: 3,
      slideBy: 1,
      autoplay: false,
      autoHeight: false,
      rewind: false,
      loop: true,
      nav: false,
      controlsText: '<', '>',
      speed: 600

**Comment by ganlanyuan** [comment]
![screen shot 2017-08-09 at 11 51 51 am](https://user-images.githubusercontent.com/4998811/29130913-2ff5c060-7cf9-11e7-9955-6b0055bf8aae.png)
Did you mean this one?

**Comment by Nomta** [comment]
Yes...

**Comment by Nomta** [comment]
It has 25 items. However when there was 4 or 5, the result was the same. Its difference is that it is linked with another slider.

**Comment by ganlanyuan** [comment]
When the first time open the page, the slider seems didn't finish initialization, 
but after a refresh, it becomes active. 
Is there any special event or function related to it?

> it is linked with another slider

Could you give more details?

**Comment by Nomta** [comment]
`// preview is item of the first slider
Array.prototype.forEach.call(photoPreviews, function(preview, i) {
        preview.onclick = function() {
        // ...
                slider.goTo(i);
                fullSlider.container.classList.add('slider-show');
        };
});`

**Comment by Nomta** [comment]
I apologize for the inaccurate formatting. Preview is an item of the first slider and both of these sliders have the same index.

**Comment by ganlanyuan** [comment]
I will take a closer look recently.

**Comment by ganlanyuan** [comment]
Hi @Nomta ,
Sorry for the late reply.

I checked your code. Seems the content of the first slider is inserted dynamically. The slider function was called before the imgs are get loaded, thus cause an issue.
- Option 1: So make sure the content is loaded before run the slider (check [here](https://github.com/ganlanyuan/tiny-slider/tree/v1#3-call-tiny-slider-on-dom-ready)).
- Option 2: use v2.0+ which doesn't require the content be loaded before run the slider. But you may need update some styles.

**Comment by Nomta** [comment]
Thank you so much William! It's really awesome, I could not handle it!

**Comment by ganlanyuan** [comment]
You're welcome
