### ISSUE TITLE
How to make every slides having the height of the highest slide ?

### ISSUE THREAD

**Issue by pdoreau** [ganlanyuan/tiny-slider#551]
__Issue description__:  
With an option or css rule, how to make every slides having the height of the highest slide ? 

__Demo link/slider setting__:   
https://codepen.io/neko2/pen/jOPBGQq
The middle slide has the highest height. The goal is to make the others having the same.

_Tiny-slider version_:   
2.9.2

**Comment by thewrush** [comment]
You can add flex to your slider parent and each child will get flex 1 by default which sets the height to all be equal.
`
.my-slider {
  display: flex;
}
`

**Comment by pdoreau** [comment]
Indeed @thewrush thanks. I tried the same but was wrong adding `heigth: 100%` on the children at the same time.

**Comment by donnyburnside** [comment]
The `display: flex;` rule does not work in Edge. In fact, it prevents any slide from rendering at all.

You can do this using the pen above. Just add the `display: flex` rule to `.my-slider` and see for yourself. You can even open Dev Tools, remove the above CSS rule and the slides will return.

Edge stats (on Windows 10):
![image](https://user-images.githubusercontent.com/10113877/76971619-52ad0a80-6925-11ea-984a-98a2bf6b2267.png)
