### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by rejas** [ganlanyuan/tiny-slider#557]
Hi thanks for your great slider. 
Just wanted to know if you are planning a new release in the near future, since I am very interested in getting https://github.com/ganlanyuan/tiny-slider/commit/d4e6e6f01958855ef127add0f395a38c99e9fd60 into my projects (and dont want to use the master branch in my package.json) 
Is there anything I can help you with to get a new release out the door?

**Comment by ganlanyuan** [comment]
Just published a new release
Thank you
