### ISSUE TITLE
Broken builds: Starting in v2.0.0 go-native is not listed as dependency in package.json

### ISSUE THREAD

**Issue by dallinskinner** [ganlanyuan/tiny-slider#56]
Starting in v2.0.0 go-native is not listed as dependency in package.json but is still being imported in tiny-slider.module.js.

As a result, when trying to use it in a webpack environment it fails to build.

**Comment by ganlanyuan** [comment]
Hi, thanks
go-native was added back in [v2.1.0](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.1.0).
