### ISSUE TITLE
Navigation breaks after browser resize (sometimes)

### ISSUE THREAD

**Issue by skrichten** [ganlanyuan/tiny-slider#57]
Sometimes when resizing the browser, the navigation will stop working.  Sometimes I am getting this on iPad when flipping from portrait to landscape, for example.

**Asking a question or submit a bug?**  
- [ ] Question
- [x] Bug

**How can others reproduce the issue?**  
Link or Code example:
Slider options:
slideBy: 'page', nav: false, loop: false,
 items: 1

Also, my slider currently only has 2 items in it.

Tiny-slider version:   
OS:   Windows, iOS
Browser:   Chrome, Safari

**Comment by ganlanyuan** [comment]
Hi @skrichten 
May I know which version of tiny-slider are you using?
And browser versions if possible?

**Comment by skrichten** [comment]
Tiny slider version is 1.6

Chrome:   60.0.3112.90 (Official Build) (64-bit) on Windows 10.

**Comment by ganlanyuan** [comment]
Hi, 
Could you check if [v1.6.1](https://github.com/ganlanyuan/tiny-slider/releases/tag/v1.6.1) fix the issue? (Note: both js and CSS need to be updated)

**Comment by skrichten** [comment]
Seems to be working now.  Thanks!
