### ISSUE TITLE
Please release on npm! Last release is one year old.

### ISSUE THREAD

**Issue by zevero** [ganlanyuan/tiny-slider#588]
__Issue description__:  
tiny-slider.module.js has missing *.js extensions.
This was already fixed 10 months ago, but never released!

_Tiny-slider version_:   2.9.2

**Comment by jurnet** [comment]
Please Upgrade on NPM, you do  great job. Thanks

**Comment by SvenBudak** [comment]
yes please do it! :D

**Comment by nghiepit** [comment]
+

**Comment by nghiepit** [comment]
+1

**Comment by S1SYPHOS** [comment]
DO IT
DO IT
DO IT

:fox_face:

**Comment by ganlanyuan** [comment]
Just published a new release.
Please check!
