### ISSUE TITLE
"responsive" not working in v1.6.1

### ISSUE THREAD

**Issue by mkoehler2911** [ganlanyuan/tiny-slider#59]
**Asking a question or submit a bug?**  
- [x] Question
- [ ] Bug

I needed the responsive function to change my slider behavior in different browser sizes but this still won't work. Any troubles while using `picture` elements? 
Hope you might help me, thanks!

**How can others reproduce the issue?**  
Live link or Code example:
HTML:
 
>             <ul class="slider">
                    <li>
                        <div class="image-wrapper">
                            <picture>
                                
                                <source media="(max-width: 767px)" srcset="assets/images/team/team1.jpg 1x, assets/images/team/team1.jpg 1.5x">
                                <source media="(max-width: 1023px)" srcset="assets/images/team/team1.jpg 1x, assets/images/team/team1.jpg 1.5x">
                                <source media="(max-width: 1279px)" srcset="assets/images/team/team1.jpg 1x, assets/images/team/team1.jpg 1.5x">
                                <source srcset="assets/images/team/team1.jpg 1x, assets/images/team/team1.jpg 1.5x">
                                
                                <img src="assets/images/team/team1.jpg" />
                            </picture>
                        </div>
                        <h4>Title</h4>
                    </li>
                    <li>
                        <div class="image-wrapper">
                            <picture>
                                
                                <source media="(max-width: 767px)" srcset="assets/images/team/team2.jpg 1x, assets/images/team/team2.jpg 1.5x">
                                <source media="(max-width: 1023px)" srcset="assets/images/team/team2.jpg 1x, assets/images/team/team2.jpg 1.5x">
                                <source media="(max-width: 1279px)" srcset="assets/images/team/team2.jpg 1x, assets/images/team/team2.jpg 1.5x">
                                <source srcset="assets/images/team/team2.jpg 1x, assets/images/team/team2.jpg 1.5x">
                                
                                <img src="assets/images/team/team2.jpg" />
                            </picture>
                        </div>
                        <h4>Title</h4>
                    </li>
                    <li>
                        <div class="image-wrapper">
                            <picture>
                                
                                <source media="(max-width: 767px)" srcset="assets/images/team/team3.jpg 1x, assets/images/team/team3.jpg 1.5x">
                                <source media="(max-width: 1023px)" srcset="assets/images/team/team3.jpg 1x, assets/images/team/team3.jpg 1.5x">
                                <source media="(max-width: 1279px)" srcset="assets/images/team/team3.jpg 1x, assets/images/team/team3.jpg 1.5x">
                                <source srcset="assets/images/team/team3.jpg 1x, assets/images/team/team3.jpg 1.5x">
                                
                                <img src="assets/images/team/team3.jpg" />
                            </picture>
                        </div>
                        <h4>Title</h4>
                    </li>
                    <li>
                        <div class="image-wrapper">
                            <picture>
                                
                                <source media="(max-width: 767px)" srcset="assets/images/team/team4.jpg 1x, assets/images/team/team4.jpg 1.5x">
                                <source media="(max-width: 1023px)" srcset="assets/images/team/team4.jpg 1x, assets/images/team/team4.jpg 1.5x">
                                <source media="(max-width: 1279px)" srcset="assets/images/team/team4.jpg 1x, assets/images/team/team4.jpg 1.5x">
                                <source srcset="assets/images/team/team4.jpg 1x, assets/images/team/team4.jpg 1.5x">
                                
                                <img src="assets/images/team/team4.jpg" />
                            </picture>
                        </div>
                        <h4>Title</h4>
                    </li>
                </ul>

JS:
> tns({
            container: document.querySelectorAll('.slider')[0],
            arrowKeys: true,
            loop: true,
            items: 1,
            lazyload: true,
            gutter: 0,
            controlsText: [' ', ' '],
            responsive: {
                700: {
                    items: 2,
                    gutter: 27
                },
                768: {
                    items: 3,
                    gutter: 30
                },
                1024: {
                    items: 4,
                    gutter: 50
                }
            }
        });

Tiny-slider version:  v1.6.1 
Browser version: safari, chrome, opera, firefox (current versions)

**Comment by ganlanyuan** [comment]
hi @mkoehler2911 ,
The options other than `items` in the `responsive` field are only available from v2.1.0

**Comment by mkoehler2911** [comment]
hi @ganlanyuan,
I installed the 2.1.0 version and got following error: 

`tiny-slider.module.js:483 Uncaught ReferenceError: gutterStr is not defined`

**Comment by ganlanyuan** [comment]
I just fixed an issue and published v2.1.1.
Could you try it?

**Comment by mkoehler2911** [comment]
Thanks for that quick response!
Got next error: `Uncaught ReferenceError: prop is not defined at whichProperty (whichProperty.js:6)`

**Comment by ganlanyuan** [comment]
Same with #61, should be fixed in v2.1.2
