### ISSUE TITLE
Add custom class to prev/next buttons

### ISSUE THREAD

**Issue by octojoerg** [ganlanyuan/tiny-slider#593]
__Issue description__:  

Hello, what is the best way to add a specific class to prev and next buttons? Is there a build-in possibility or do I need some custom JS magic?

Thanks

**Comment by brianfryer** [comment]
Your best bet is to write your own HTML and use the `controlsContainer`, `prevButton`, and `nextButton` options.

**Comment by octojoerg** [comment]
Ok, thanks for the information. This was the way I already knew about, but was hoping to find an alternative solution.
