### ISSUE TITLE
The movement of dragging from the mobile is jerky

### ISSUE THREAD

**Issue by mattiapontonio** [ganlanyuan/tiny-slider#610]
This Is a issue present in many sliders.

This project use hardware accellerated transition and seems not has the issue.
https://github.com/nolimits4web/swiper

**Comment by duongancol** [comment]
We reported the same issue here https://github.com/ganlanyuan/tiny-slider/issues/525

**Comment by kennylawrence** [comment]
Ah great. I was about to submit a request as well just now but I see nothing will be done as the #525 is from January. I guess I will try to switch YET AGAIN to another slider, haha..  Thanks @mattiapontonio for the reference. 

Just to be sure though - the jerkyness only happens while your finger is on the screen, correct? As soon as you release it, the slider finishes it's movement smoothly?

**Comment by mattiapontonio** [comment]
@kennylawrence yes.
I don't wanna be cheap but Is a JavaScript issue. If You have to transit something Is better to use CSS transitions ever. This Is because browser calulates them in his repaint cycle in a better manner then the Dom changhes.
Idem for animation.
Se has same issues with animations done using setInterval or JavaScript.
Is not good.

**Comment by kennylawrence** [comment]
@mattiapontonio Looks like owlslider works fine for this behavior, so I'll go back to that one. I'm a store owner, not a very experienced front end developer.

**Comment by kennylawrence** [comment]
@mattiapontonio or swiper does look pretty nice too.. I'm becoming a slider setup expert
