### ISSUE TITLE
Touch dragging on mobile is laggy, not smooth

### ISSUE THREAD

**Issue by kennylawrence** [ganlanyuan/tiny-slider#618]
__Issue description__: When on a mobile device (tested with Pixel 3 Android 11 + Moto G7 Android 10) while your finger is touching the screen and dragging, the carousel framerate is very low, although if you release your finger while dragging, the animation becomes smooth again. Unfortunately I don't know how to debug this further.

__Demo link/slider setting__:   

_Tiny-slider version_:   2.9.3
_Browser name && version_:  Chrome 85.0.4183.120 (on the Android 11 Pixel 3)
_OS name && version_:    Android 10 & 11

**Comment by ivanmuller** [comment]
I had the same issue and the option `preventScrollOnTouch : 'force',` worked for me. It runs very smoth now.

**Comment by LautaroLobo12** [comment]
This sounds similar to #525 and #610.

**Comment by kennylawrence** [comment]
I am now using Swiper (https://swiperjs.com) with great success. This is the one you want.

**Comment by made-by-chris** [comment]
To anyone else finding this issue i recommend also checking if you have "user-select:none" on your slide elements. this destroys perf on mobile for me
