### ISSUE TITLE
Cannot read property getInfo() of undefined

### ISSUE THREAD

**Issue by darbymanning** [ganlanyuan/tiny-slider#62]
This is probably user error here, but this is my code:

```
var slider = tns({
    container: sliderContainer,
    mouseDrag: true,
    nav: false,
    controls: false
});

console.log(slider.getInfo());
```

Console error on page load:
`Uncaught TypeError: Cannot read property 'getInfo' of undefined`

Any ideas?

**Comment by ganlanyuan** [comment]
Tiny-slider should be inside &lt;body&gt;, because some functions require
`document.body`.

**Comment by darbymanning** [comment]
Hmm it is inside the `<body>`, the sliderContainer referenced is:
`var sliderContainer = document.querySelector(".js-slider")`
Or am I misunderstanding?

**Comment by ganlanyuan** [comment]
That's fine.
I will check it deeper later today.

Which version are you using?

**Comment by darbymanning** [comment]
Sure, I'm using 2.1.2

**Comment by ganlanyuan** [comment]
Hi, 
I just create a [new pen](https://codepen.io/ganlanyuan/pen/KvRoWg) with your options, seems everything fine.

**Comment by darbymanning** [comment]
I worked out what was going on here - I only had one slide in my slider, which prevents a slider object being created (slide count needs to be >1)

**Comment by ganlanyuan** [comment]
Glad you resolve the issue.
Yes, it's not necessary to create a slider for only one slide.
