### ISSUE TITLE
Is it possible to let the user manually start the autoplay

### ISSUE THREAD

**Issue by Verhoeckx** [ganlanyuan/tiny-slider#623]
Hello Tiny Slider developers,

Is it possible to start the autoplay stopped?
Or in other words: let the user manually start the autoplay (so he/she is in control)?

It would be great if this was possible!

Verhoeckx

**Comment by cpof-tea** [comment]
I think a good workaround right now - just pause slider after initialization
```js
const slider = tns({ autoplay: true });

slider.pause();
```

**Comment by Verhoeckx** [comment]
Hello cpo-tea,

That's a great solution! It works perfectly :-)!

Thanks for thinking a long!

Verhoeckx

**Comment by cpof-tea** [comment]
Alternative solution
```js
const slider = tns({
  autoplay: true,
  onInit() {
    slider.pause();
  }
});
```

**Comment by cpof-tea** [comment]
@Verhoeckx close the issue if your problem was solved, plz

**Comment by Verhoeckx** [comment]
Closing it happily!

**Comment by Verhoeckx** [comment]
Hello,

When I write that, I get the following error: "slider is undefined".

If I use the keyword 'this', I get the error: "this.pause is not a function".

'This' should be the right code, not?

Verhoeckx

-----------------------------------------------------------------------------------
LibreOffice – free and open source office suite: https://www.libreoffice.org
Respects your privacy, and gives you back control over your data

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
