### ISSUE TITLE
Lazyloading not working: all the images in Tiny Slider are loaded

### ISSUE THREAD

**Issue by Verhoeckx** [ganlanyuan/tiny-slider#625]
**Issue description**
Lazyloading not working: all the images in Tiny Slider are loaded.  
   
This is what I do:

1. I set the option lazyload to true.
2. I add the attribute 'data-src' to every image.
3. I add the class 'tns-lazy-img' to every image.

4. I remove all the data in the browser (CTRL + SHIFT + DEL).
5. I open the developer tools of the browser and select the tab 'network'.
6. I load the webpage with Tiny Slider.
  
Result:
All the images in the Tiny Slider are loaded.

_Is there still something else I have to do?_
  
**Slider settings:**
```
var slider = tns({
	container: '.slider',
	mode: 'carousel',
	axis: 'horizontal',
	items: 1,
	slideBy: '1',
	center: false,
	controls: false,
	nav: true,
	navPosition: 'bottom',
	arrowKeys: true,
	speed: 500,
	autoplay: true,
	autoplayPosition: 'bottom',
	autoplayTimeout: 10000,		
	autoplayText: ["▶", "❚❚"],		
	loop: true,
	lazyload: true
});	
```

_Tiny-slider version_:   2.9.3
_Browser name && version_:  Firefox 81, Chromium 85
_OS name && version_:   Fedora 32

**Comment by Verhoeckx** [comment]
Sorry, I left the src attribute and this was why the images were still loading :-|.

**Comment by dijkermans** [comment]
:-)
