### ISSUE TITLE
Cannot display thumbnails

### ISSUE THREAD

**Issue by paulcosmos** [ganlanyuan/tiny-slider#628]
__Issue description__:  

I am unable to get thumbnails to display. If I add a `navContainer` value no thumbnail images are are added but the DOM shows other elements relating to teh thumbnail navigation. 

If I don't specify a container, the `navAsThumbnails` option is just ignored and the dots remain. Presumably this is the desired fallback behaviour?

I'm using the Grav CMS and outputting content using Twig.

__Demo link/slider setting__:   

HTML/Twig mark-up
```
            <div id="pin-gallery">
                {% for image in page.media.images %}
                    <div>
                    <figure class="image is-1by1">
                        {{ image.cropResize(600,600).html(page.title , page.title )|raw }}
                    </figure>
                    </div>
                {% endfor %}
            </div>

            <ul id="thumbnails-nav">
                {% for image in page.media.images %}
                    <li></li>
                {% endfor %}
            </ul>
```
```
        var slider = tns({
            container: '#pin-gallery',
            items: 1,
            slideBy: 'page',
            autoplay: false,
            controls: false,
            navContainer: '#thumbnails-nav',
            navAsThumbnails: true,
            navPosition: 'bottom',
            mouseDrag: true,
            arrowKeys: true,
        });
```

_Tiny-slider version_:   
2.9.3

**Comment by romanown** [comment]
in #thumbnails-nav need place images `<img src="https://....>` . as main and as many as main. example as you code.
`<ul id="thumbnails-nav">
                {% for image in page.media.images %}
                    <li><img src=image></li>
                {% endfor %}
            </ul>`

**Comment by paulcosmos** [comment]
Ah, thanks, I managed to get it working. It wasn't clear from the instructions I had to specifiy the thumbnails myself, I had assumed it was automated by the plugin.
