### ISSUE TITLE
slideBy ignored when using goTo (prev/next)

### ISSUE THREAD

**Issue by darbymanning** [ganlanyuan/tiny-slider#63]
When using the goTo method with prev or next, the slideBy count is ignored. Is there a way to replicate how this works with the native prev/next buttons?

Example: https://codepen.io/darby/pen/XaYzbp

**Comment by ganlanyuan** [comment]
The `goTo` method is designed to go to exact slide, so the keywords "prev/next" will just go previous/next slide.
You could replicate the native prev/next buttons functions using `controlsContainer` option, which wraps around the customized prev/next buttons.

**Comment by darbymanning** [comment]
My issue really is that I want to use custom markup for the controls though. My personal preference is to not target data attributes for the controls or slides, I'd rather keep it consistent with the BEM naming methodology I've used in my project...

It still seems strange to me that goTo method for prev/next go to the next slide, whereas the native buttons respect the slideBy page option. Are you sure this is correct behaviour? I would expect them to be the same really.

**Comment by ganlanyuan** [comment]
Hmm, maybe you're right.
"prev/next" for the "goTo" function should work the same way as the native ones.
Thanks for your feedback. I will update this and let you know.

**Comment by ganlanyuan** [comment]
Fixed in [v2.1.3](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.1.3),
Could you check?

**Comment by darbymanning** [comment]
Top job.
