### ISSUE TITLE
Slider with one slide and show part next/prev

### ISSUE THREAD

**Issue by BGarcilaso** [ganlanyuan/tiny-slider#634]
__Issue description__:  Hi!

I'm triyng to program this slider with some specials peculiarities. I'm using the item's value with decimals (1.2) to show part of the next slide (or previous slide if the user goes back). My problem is that I don't know what can I do to get the efect of the next images:

This is how will see the first slide and the others except the last.

![Captura de pantalla 2020-10-22 181646](https://user-images.githubusercontent.com/25845578/96900885-e08c3d80-1492-11eb-9b9d-bf55183dcead.png)

Actually, my last slide has that position:

![Captura de pantalla 2020-10-22 181559](https://user-images.githubusercontent.com/25845578/96900907-e71ab500-1492-11eb-9c23-d6c0a543f64c.png)

And I need that its final position was like this image:
![Captura de pantalla 2020-10-22 181634](https://user-images.githubusercontent.com/25845578/96900968-f7cb2b00-1492-11eb-82f9-801d6886b150.png)

I need that the user see the first slide and part of the next when he move the slider to right. When he arrives to the last slide, I don't want space on the right side of slide. The last slide is located without right margin and instead of show part of the previous slide.

I create a demo to show you how its the slide configured.

__Demo link/slider setting__:   https://codepen.io/bgarcilaso/pen/PozbdVW

Thanks!

**Comment by mrksmts** [comment]
@BGarcilaso I see you closed this the next day after you created this issue, were you able to solve this?
