### ISSUE TITLE
Flickering issue on Safari

### ISSUE THREAD

**Issue by brakai295** [ganlanyuan/tiny-slider#635]
I'm seeing a weird flickering issue when using this slider on Safari/macOS (latest). The flickering occurs on the right side when I click 'next' and on the left when I click 'prev'.

Try it yourself: https://breathe-new.webflow.io/testing  

Tiny-slider version: 2.9.2

Other browsers (FF & Chrome) work fine. Any ideas?

**Comment by AkBarsA** [comment]
> I'm seeing a weird flickering issue when using this slider on Safari/macOS (latest). The flickering occurs on the right side when I click 'next' and on the left when I click 'prev'.
> 
> Tiny-slider version: 2.9.2
> 
> Other browsers (FF & Chrome) work fine. Any ideas?

Tell me how you solved the problem?
