### ISSUE TITLE
Multiple issues using fixedWidth: true

### ISSUE THREAD

**Issue by justindmyers** [ganlanyuan/tiny-slider#64]
**Asking a question or submit a bug?**  
- [ ] Question
- [x] Bug

**How can others reproduce the issue?**  
https://codepen.io/justindmyers/pen/WELozo

Tiny-slider version:   
OS version: Windows 10 64-bit
Browser version: Chrome 60.0.3112.113

When using `fixedWidth: true` and not having enough items to fill the screen, a few things happen:

- Cloned items are still displayed (i.e. a 2 slide carousel will show a full screen's width of carousel items). For my purposes, it would confuse the user to have the same items repeated over and over.
- Using `loop: false` throws an error
- Using `slider.goTo("next")` or `slider.goTo("prev")` causes the carousel to slide a seemingly random number of slides
- Carousel doesn't start working when resizing down to the correct number of slides (nav and controls stay hidden, mouseDrag doesn't work). The opposite is also true, if you start at a low enough screen width the carousel nav and controls show and if you increase the resolution they still work.

**Comment by ganlanyuan** [comment]
Will check this tmr

**Comment by ganlanyuan** [comment]
> - Cloned items are still displayed.
> - Using `loop: false` throws an error
> - Using `slider.goTo("next")` or `slider.goTo("prev")` causes the carousel to slide a seemingly random number of slides
> - Carousel doesn't start working when resizing down to the correct number of slides. 

All fixed, but I'm still doing some feature tests.

**Comment by ganlanyuan** [comment]
Hi @justindmyers 
Thanks for your feedback.
The `fixedWidth` related issues should be fixed in [v2.1.4](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.1.4), could you check ?

**Comment by ganlanyuan** [comment]
Close for now, feel free to reopen it if the issue still appears.
