### ISSUE TITLE
Add class to nav buttons when inactive

### ISSUE THREAD

**Issue by etiennebacher** [ganlanyuan/tiny-slider#643]
I'm trying to modify the style of the default nav buttons. It is easy to do so with the class `button.tns-nav-active` for the active button, but there is no class available for the inactive buttons. Is it possible to add a class for them, such as `tns-nav-inactive`?

I found the line `navActiveClass = 'tns-nav-active'` [here](https://github.com/ganlanyuan/tiny-slider/blob/master/src/tiny-slider.js) but I don't know what to write to add this class.

**Comment by thenomadicmann** [comment]
There isn't a need for this class. You can target those buttons using the [CSS :not selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:not). So `.tnv-nav button:not(.tns-nav-active)` would do the trick if you need to target all buttons not active.

**Comment by etiennebacher** [comment]
Indeed, thanks!
