### ISSUE TITLE
Script fails when using together with Turbolinks

### ISSUE THREAD

**Issue by S1SYPHOS** [ganlanyuan/tiny-slider#65]
**Asking a question or submit a bug?**  
- [ ] Question
- [x] Bug

**How can others reproduce the issue?**  
```js
// my tns function
function tinySlider() {
  const slider = tns({
    responsive: {
      '0': 1,
      '600': 2,
      '900': 3
    },
    slideBy: 1,
    autoplay: true,
    autoplayTimeout: 2500,
    autoplayHoverPause: true,
    gutter: 10,
    controlsContainer: '.slider-controls'
  });
}

// loading tns function
 window.onload = function() {
   tinySlider();
 };

// loading Turbolinks - see https://github.com/turbolinks/turbolinks
var Turbolinks = require("turbolinks");
Turbolinks.start();

// re-initiate tns function on load event
document.addEventListener("turbolinks:load", function() {
  tinySlider();
})
```

Tiny-slider version: 1.6.0
OS version: Fedora 26, 64bit
Browser version: FF 55, 64bit

Upon entering a page that has tiny slider, page load takes forever & eventually crashes the browser. Debugging tns points to this function:

```js
  function getSlideEdges() {
    slideEdges = [0];
    var topFirst = slideItems[0].getBoundingClientRect()[transformAttrLegacy], attr;
    for (var i = 1; i < slideCountNew; i++) {
      // next line seems to cause the problem
      attr = slideItems[i].getBoundingClientRect()[transformAttrLegacy];
      slideEdges.push(attr - topFirst);
    }
  }
```

Now, I know third-party stuff is not your field, but maybe you can point me in the right direction here?

**Comment by ganlanyuan** [comment]
Hi, I will take a look maybe tomorrow.

**Comment by S1SYPHOS** [comment]
Much appreciated. Turbolinks / ajax-like javascript in general are becoming a thing.
Since, as you may have noticed, I like `tns`, seeing them married would be great!

**Comment by ganlanyuan** [comment]
I see.
1. I didn't see `container` in `options`, are you using default `.slider`?
2. And do all pages using the same structure (`container` and `controlsContainer`)?

According to `turbolinks`:
> `turbolinks:load` fires once after the initial page load, and again after every Turbolinks visit. Access visit timing metrics with the `event.data.timing` object.
General idea:  
1. Can you try just initiate `tns` once?   
2. Before every Turbolinks visit, you may need run `slider.destroy()` to remove `eventListener`s, clean some memory.
3. Since `slider` is supposed to change, it's better to use `let`.

**Comment by S1SYPHOS** [comment]
Alright, way to go!
Will check this out, more soon, thanks for the fast reply :cake:

**Comment by S1SYPHOS** [comment]
Deleting `window.onload` + slider() function call from turbolink:load event did the trick, although I'm a little confused. Thanks anyway for the hint to load it just once 👍

**Comment by ganlanyuan** [comment]
Hi, the function `getSlideEdges` in version 1 requests that the slides be loaded before the initialization. But I will update it later to make it work better with dynamically loaded content.
Version 2 doesn't have this issue.

Regardless of version, to initiate `tns` more than 1 times will probably make troubles.

Thanks for letting me know your case anyway.

**Comment by S1SYPHOS** [comment]
The honour was mine!
