### ISSUE TITLE
Issue with custom controls when slider controls: false is set

### ISSUE THREAD

**Issue by darbymanning** [ganlanyuan/tiny-slider#66]
When `controls: false` is set, custom controls seem to always go the 'previous' direction. However, if `controls` isn't set to `false` it works as expected. See below:

https://codepen.io/darby/pen/XaYzbp

**Comment by ganlanyuan** [comment]
Thanks @darbymanning ,
The issue should be fixed in [v2.1.5](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.1.5),
Could you try it?
