### ISSUE TITLE
Bug with mouseDrag on slide images

### ISSUE THREAD

**Issue by enkota** [ganlanyuan/tiny-slider#67]
**Asking a question or submit a bug?**  
- [ ] Question
- [x] Bug

**How can others reproduce the issue?**  
Live link or Code example: https://jsfiddle.net/Lak267fo/2/

I am having a strange issue across all browsers using an image with mouseDrag. If you try dragging the slider it is not as smooth and the image will stick to the mouse. It works perfectly with the demo versions using text only slides. 

(Update: Everything works smoothly with background images so related to `<img>`)
Tiny-slider version:   
OS version:  MAC OS
Browser version: Safari 10.1.1

**Comment by ganlanyuan** [comment]
Hi @enkota ,
Thanks, I will check this issue today or tomorrow.

**Comment by ganlanyuan** [comment]
Hi, the issue should be fixed in [v2.1.6](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.1.6)
Could you try it?

**Comment by enkota** [comment]
@ganlanyuan that done the trick! thank you 👍

**Comment by enkota** [comment]
Hey @ganlanyuan thought i'd reopen this ticket. 

Again thanks for the mouseDrag fix, some related bugs have resulted as part of the change:

1 - On the mousedrag2 slider of the demo page, when you click and hold the slider to start dragging, the slides will almost freeze if you start moving it about the screen at faster speeds. It just doesn't feel as smooth as owlCarousel for instance. 

2 - Sometimes after dragging with the mouse, the cursor will stick to that point even when de-selected.

Only tested with Safari so far might be better in Chrome.

Thanks!

**Comment by ganlanyuan** [comment]
Sorry for late response.
Just add a fix in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/6ff06ae1456dc95a68e2a89ba5204bc3530f1527) which can be tested in the [demo page](http://ganlanyuan.github.io/tiny-slider/tests/index.html#mouse-drag_wrapper).
Please let me know if it works for you.

**Comment by enkota** [comment]
hey @ganlanyuan that's brilliant... butter smooth now :)

**Comment by ganlanyuan** [comment]
@prochorz Would you let me know in what situation this issue happens?
