### ISSUE TITLE
autoHeight not working on first load

### ISSUE THREAD

**Issue by ragivi** [ganlanyuan/tiny-slider#678]
Setting `autoHeight: true` is not working on first load, it only works when you navigate to any slide.

- Tiny-slider version: 2.9.3
- Browser name && version: Google Chrome 88.0.4324.190
- OS name && version: Windows 10

**Comment by ragivi** [comment]
Finally it was a problem with one component of my code.

**Comment by eiswurm** [comment]
I have a similar problem. When autoHeight is active, the slider does not work the first time the page is loaded. But this varies from browser to browser. In Chrome and Edge it is as described, only after reload of the page it works. In Firefox it does not work at all, not even on reload. In Safari, on the other hand, everything works, even on first load.
`<script>

  var slider = tns({
    container: '.tiny-portfolio',
    mode: 'carousel',
    autoplay: true,
    autoplayButtonOutput: false,
    speed: 1000,
    mouseDrag: true,
    controlsText: ['<span class="icon-circle-left2"></span>','<span class="icon-circle-right2"></span>'],
    autoHeight: true
  });
  </script>`

testet with the latest versions, no other script on the page

**Comment by Vanlen1er** [comment]
So, no solution for this problem atm ?
