### ISSUE TITLE
Cannot hide autoplay text (start/stop)

### ISSUE THREAD

**Issue by darbymanning** [ganlanyuan/tiny-slider#68]
__Issue description__:  
When `autoplay` is set to `true` the start/stop control is shown and I'm unable to disable it - even by explicitly setting `autoplayButton` to `false` (which is already the default setting).

__Demo link/slider setting__:   
https://codepen.io/darby/pen/XaYzbp

_Tiny-slider version_:   2.1.6
_Browser name && version_:  Chrome 60, Safari 10.1.2
_OS name && version_:   macOS Sierra 10.12.6

**Comment by ganlanyuan** [comment]
You may need to hide it via CSS manually.
`autoplayButton` option is for customized start/stop button.

**Comment by darbymanning** [comment]
Although it is possible to hide this through CSS, I think it would be best to have an option to have the markup not be output.

**Comment by ganlanyuan** [comment]
Hi,
What you would like to name the new option?
Or use `autoplayButton: 'disable'`?

**Comment by darbymanning** [comment]
hmm, well for the sake of consistency should probably be same as how `nav` / `navContainer` and `controls` / `controlsContainer` works - right? But I can see having simply `autoplayButton: false` is problematic for backwards compatibility. In an ideal world, we'd have:

Option | Type | Description
-- | -- | --
`autoplayButton` | Boolean | Default: `true`
`autoplayButtonContainer` | Node | String | `false` | Default: `false`. The autoplay start/stop button or selector.

So essentially - `autoplayButton` renames to `autoplayButtonContainer`, and `autoplayButton` is used to specify if markup is added or not.

I suppose `'disable'` does work, but really it feels like I should be setting a boolean here not a string.....whatever you think @ganlanyuan :)

**Comment by ganlanyuan** [comment]
The situation of `autoplayButton` is a little different with `navContainer` and `controlsContainer`.
For `navContainer`, I'm sure that all its children are `dots`.
For `controlsContainer`, I'm sure its first Child is the prev button and the second child is the next button.
For `autoplayButtonContainer`, similarly, I can say its only child is the `autoplayButton`, but then you have to wrap the `autoplayButton` with an extra node. I would like to keep it simple, just `autoplayButton`.

And for the option, I'd like to use `autoplayButtonOutput: true`, what do you think?

**Comment by ganlanyuan** [comment]
`autoplayButtonOutput` added in [v2.1.7](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.1.7), are you able to check it?

**Comment by darbymanning** [comment]
That's perfect, nice one @ganlanyuan 👍
