### ISSUE TITLE
Responsive items work incorrectly

### ISSUE THREAD

**Issue by kamelise** [ganlanyuan/tiny-slider#684]
__Issue description__:  Slider navcontainer doesn't display correct number of buttons when using responsive option "items".
This is basically the same issue that was reported here: https://github.com/ganlanyuan/tiny-slider/issues/91
I recorded video showing this issue on your own demonstration page https://ganlanyuan.github.io/tiny-slider/demo/ with "Responsive" example. Please see screen recording.

__Demo link/slider setting__:   

[responsive_items_issue.mov.zip](https://github.com/ganlanyuan/tiny-slider/files/6197334/responsive_items_issue.mov.zip)

_Tiny-slider version_:  2.9.3
_Browser name && version_:  Google Chrome Version 89.0.4389.90 (Official Build) (x86_64)
_OS name && version_:   macOS Catalina Version 10.15.6

**Comment by dijkermans** [comment]
Looks like the bullets are related to the amount of pages, which seems to be right.

**Comment by kamelise** [comment]
Oh, so that's the feature! I'm closing this issue then, but got a question: is there possibility to reflect number of total images as buttons? I.e. in video example that would be 6 buttons regardless of viewport width. Thanks!

**Comment by albanyacademy** [comment]
This is still an issue. https://codepen.io/wearingalampshade/pen/KKBKGba Pills are not properly hidden at load, and don't seem to reliably be hidden/displayed when triggering responsive breakpoints, and it seems the active index does not properly update from prev/next navigation when this issue occurs.
