### ISSUE TITLE
Always display on whole screen horizontally FIX

### ISSUE THREAD

**Issue by didiosn** [ganlanyuan/tiny-slider#686]
__Issue description__:  My tiny slider carousel is displayed on whole width of the page but I want only in his container

__Demo link/slider setting__:   I do not have a link, i'm on locahost, but I can provide screenshot.

_Tiny-slider version_:   Latest via CDN
_Browser name && version_:  Opera (Chrome)
_OS name && version_:   Windows 10

![image](https://user-images.githubusercontent.com/15895051/112459763-1c834180-8d56-11eb-8101-575388dc8979.png)

On this screen It should only displayed in the blue section, but its taking the whole screen to the sidebar. I tried to play with z-index but translate3d is not allowing that.

thanks

**Comment by dijkermans** [comment]
Looks like the parent container needs a position:relative and the slider position:absolute. I don't think it's an issue with tiny slider.

**Comment by didiosn** [comment]
Thanks for fast reply. 
I've tried to add those position but nothing changed. All codepen that I found on internet are not doing this. Please show me a simple code html css js that solve my problem.

Thank You.

**Comment by dijkermans** [comment]
Share a codepen and I'll have a look. If I add a wrapper with a specific width around tns-outer on the demo page, it just works

**Comment by didiosn** [comment]
Thanks for your patience I finally foud the fix which is a simple css : 

`.tns-ovh {
            overflow: hidden;
        }`

Hope it'll help someone.

**Comment by dijkermans** [comment]
On the demo page there was already;

.tns-ovh {
    overflow: hidden;
}
