### ISSUE TITLE
How can I find the tns slider instance from the container?

### ISSUE THREAD

**Issue by matt3224** [ganlanyuan/tiny-slider#69]
Hi,

I need to be able to find the tns instance from the container selector. In my setup sliders are created programatically. I need to be able to fire events on custom controls which supply the selector of the slider container.

The problem is I need to be able to run methods on the slider when the only info I have available to me is the container selector.

Here's an example to give you the idea of what i'm trying to do, i'm aware this code will not work as i'm trying to run a method on an element as opposed to the slider instance. It's just to show the what I need:

```js
let myUniqueSlider = tns({
    container: '.js-unique-slider',
    items: 3,
    slideBy: 'page',
    autoplay: true
});

document.querySelector('.js-unique-slider').goTo('next');
```

Any help is very much appreciated,

**Comment by ganlanyuan** [comment]
Hi, `myUniqueSlider` is the instance you are looking for.
So you can do `myUniqueSlider.goTo('next');`

**Comment by matt3224** [comment]
@ganlanyuan Thanks for that, in my project I am unable to know `myUniqueSlider` but I do know `.js-unique-slider` how can I get the former from the latter?

**Comment by ganlanyuan** [comment]
May I know how do you initiate the slider?

**Comment by ganlanyuan** [comment]
There is no way to get the slider instance only by a selector.
