### ISSUE TITLE
Any option to disable horizontal touch device scrolling?

### ISSUE THREAD

**Issue by pierrevano** [ganlanyuan/tiny-slider#694]
__Issue description__:  Is there any option to completely disable horizontal touch device scrolling? Or any workaround with css? I would like to be able to go between slides only with the control buttons. 

Currently this is my slider config:
```
var slider = tns({
    'container': '#slider',
    'items': 1,
    'loop': false,
    'swipeAngle': false,
    'speed': 400,
    'controls': true,
    'controlsPosition': 'bottom',
    'controlsText': ['Précédent', 'Suivant'],
    'nav': false,
    'mouseDrag': false,
    'arrowKeys': true
});
```

_Tiny-slider version_:   2.9.3
_Browser name && version_:  Chromium 90
_OS name && version_:   macOS 11.1

Thank you for any help!

**Comment by drine-kin** [comment]
Try adding this, it works for me (mobile)
```
slider.events.on('touchStart', function (e) {
	e.stopImmediatePropagation();
});
slider.events.on('touchMove', function (e) {
	e.stopImmediatePropagation();
});

slider.events.on('touchEnd', function ( e) {
	e.stopImmediatePropagation();
});
```

**Comment by pierrevano** [comment]
@drine-kim thanks for the feedback but your workaround disable all possible scrolling when I only want to disable horizontal scrolling when scrolling vertically. The same way I have it on desktop view. Any tricks?

**Comment by pierrevano** [comment]
Thanks a lot! It worked indeed!
