### ISSUE TITLE
Feature request - Add option to control dot navigation behaviour

### ISSUE THREAD

**Issue by Radiergummi** [ganlanyuan/tiny-slider#71]
I'm using TinySlider to build a slowly fading background gallery, so `speed` is set to 3s and `autoplayTimeout` to 5s. I use a simple dot navigation, and since the next dot is highlighted upon animation end, it seems like the wrong dot is highlighted for the last two seconds of the animation.  
Therefore, I'd like to know whether it'd be possible to add a configuration option `navAnimation` for the slider navigation which has two possible values: `start` and `end` (default).  
On `start`, the nav would switch its selected element as soon as the slider starts showing the next slide, on `end` it would switch the selected element once the slide animation is finished (as it is now).  
I'm not completely satisfied with the option naming though, so maybe a native english speaker would be able to come up with a better one.  
Thank you! 😊 

Edit: You can find a demo [here](http://bnm.dev.boxhorn-edv.com/).
*(Just noticed I got the start/end descriptions the wrong way round, corrected)*

**Comment by ganlanyuan** [comment]
Agree.
For the slide animations we have 2 options: `animateIn` and `animateOut`, so you can use different animations on the previous slide and current slide. 
For the dots, do we also need 2 options (as @Radiergummi says `start` and `end`) to define different animations on the dots `in` and `out`? Or one is enough?

**Comment by Radiergummi** [comment]
It comes down to a boolean decision, but I'd prefer to set this as a string value like `updateNav: 'end'` in the options rather than `updateNavOnIndexChange: true`.

**Comment by ganlanyuan** [comment]
I see.
Will add the option probably this weekend.

**Comment by ganlanyuan** [comment]
I add a [new branch](https://github.com/ganlanyuan/tiny-slider/tree/navAnimation) for this issue.
Now, `nav` status changes prior to the slider animation and a `transition` property was added to the `nav`. 
So now you can  define the normal styles using `[aria-selected]` and active using `[aria-selected="true"]`.   
[demo](https://codepen.io/ganlanyuan/pen/prMRXy)

Do you still need to add extra classes for the **normal** and **active** status?
For me, this seems enough.

**Comment by ganlanyuan** [comment]
Changes added in [v2.1.7](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.1.7)

**Comment by Radiergummi** [comment]
Just implemented the new version on my project - works like a charm. Thank you! 🍻
