### ISSUE TITLE
Tiny Slider fails on private or incognito browser sessions

### ISSUE THREAD

**Issue by antgonzales** [ganlanyuan/tiny-slider#72]
__Issue description__:  Tiny Slider fails on Safari for iOS, Safari on Mac OS, and Chrome mobile of iOS when browsing incognito or private due to lack of access to localStorage. I'm providing a link to the demo on Github, but this also fails on a project I'm currently working on.

__Demo link/slider setting__:   http://ganlanyuan.github.io/tiny-slider/tests/index.html

_Tiny-slider version_:   tiny-slider@2.1.6
_Browser name && version_:  Safari Version 10.1.2 (12603.3.8)
_OS name && version_:   Mac OS Sierra v10.12.6

**Comment by ganlanyuan** [comment]
Thanks @antgonzales ,
This will be fixed in next release.

**Comment by ganlanyuan** [comment]
Fix added in [v2.1.7](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.1.7), could you check it?

**Comment by ganlanyuan** [comment]
Feel free to reopen it if issue still exists.

**Comment by antgonzales** [comment]
@ganlanyuan sorry for the late response, works as expected. Nice work and thanks for the quick turn around!

**Comment by ganlanyuan** [comment]
No problem
