### ISSUE TITLE
Issue with getting accurate info from getInfo method on resize

### ISSUE THREAD

**Issue by darbymanning** [ganlanyuan/tiny-slider#73]
So here's my issue - I'm using some custom controls (for prev/next), and I want to detect if the number of items in the view is the same as the total slide count. If it is, I want to hide the prev/next buttons. I have tried getting this info on window resize using the `getInfo()` method, but I'm getting inaccurate results, ie. sometimes 2 slides are on view, but it will return '3'.

Example:
https://codepen.io/darby/pen/XaYzbp
Resize window to < 640px

This is also the case when using a generous setTimeout - it just isn't getting the correct info.

Perhaps I need a callback method for the responsive breakpoints or something?

**Comment by ganlanyuan** [comment]
For the purpose of *show/hide the prev/next buttons*, it's better to use native prev/next buttons which will be showed/hid automatically and smoothly.

`tiny-slider` will update the information (`getInfo()`) after resize done (no resizing in 100ms), so it will be delay 100ms. So you can still get the correct information using `setTimeout(fn(), 100)` even though it's not 100% accurate.
[Updated version](https://codepen.io/ganlanyuan/pen/XeJXva) of your demo.

If you want to get the `resize` event from `tiny-slider`, I can add it.

**Comment by ganlanyuan** [comment]
Will close it for now, feel free to reopen it.
