### ISSUE TITLE
Option navContainer results on Error

### ISSUE THREAD

**Issue by gutofoletto** [ganlanyuan/tiny-slider#74]
__Issue description__:  Setting the option navContainer to another element e.g ".slider-nav" results on: Uncaught TypeError: Cannot read property 'item' of undefined and does not show the nav dots.

__Demo link/slider setting__:   https://codepen.io/gutofoletto/pen/LzEGqd

_Tiny-slider version_:   2.16
_Browser name && version_:  Chrome Version 60.0.3112.113
_OS name && version_:   OSX 10.11

**Comment by ganlanyuan** [comment]
Hi,
That's because there is no actual `nav item` (dots) inside the ".slider-nav".
*Note: When using customized `nav`, make sure it's at least the same amount of the slides.*
[updated version](https://codepen.io/ganlanyuan/pen/MEYyBr?editors=1111)

**Comment by gutofoletto** [comment]
Hello!
Thanks for the clarification. Now it makes sense, but it is not very practical I assume.
So, I think the best way to handle custom dots with dynamic content is to override the default styling on ".tns-nav".

Best regards.

**Comment by ganlanyuan** [comment]
Agree.
The original purpose of customized dots are as thumbnails, so their behaviors are different with native ones. They never get hidden to reflect the changes of slide number on the viewport.
