### ISSUE TITLE
Showing error in Sveltekit?

### ISSUE THREAD

**Issue by mbparvezme** [ganlanyuan/tiny-slider#744]
Working on **Sveltekit** framework for my front-end. I want to use tiny-slider but it is showing error "**Windows not defined**". How can I use tiny-slider with Sveltekit?

**ERROR**
`window is not defined`
`ReferenceError: window is not defined`
`at Object.<anonymous> (< PATH >\node_modules\tiny-slider\dist\tiny-slider.js:5:13)`

**EXAMPLE**
`var slider = tns({
    container: '.my-slider',
    items: 3,
    slideBy: 'page',
    autoplay: true
  });`

Integration type: npm

**Comment by markfswe** [comment]
https://kit.svelte.dev/faq#how-do-i-use-x-with-sveltekit-how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window

**Comment by mbparvezme** [comment]
Thank you @ZerdoX-x.
