### ISSUE TITLE
vpInner incorrect value in onTouchOrMouseMove

### ISSUE THREAD

**Issue by justindmyers** [ganlanyuan/tiny-slider#76]
__Issue description__:  I have a strange bug where when using touch/mouseDrag the sensitivity is way off and seems to accelerate.

I tracked it down to line 1911 where `vpInner` is an incorrect value. For example: I have multiple carousels on the page where most report `vpInner` correctly at 516px (depending on screen width), but sometimes one or more carousels will report back the value 8px which causes the dragging/touch problem.

I cannot reproduce this outside of the project I'm working on but I'm thinking it might have something to do with it being an image heavy slider as it seems to mostly happen when I clear the browser cache and refresh.

Here's a gif to show the behavior that I'm talking about: https://imgur.com/a/iAFnX

 I've tested on Chrome, Firefox, and Edge with the same results.

**Comment by justindmyers** [comment]
Just found a solve:

Line 1911: 
`var percentageX = TRANSFORM ? disX * items * 100 / (vpInner * slideCountNew) : disX * 100 / vpInner;`

Line 1949: 
`var indexMoved = - disX * items / vpInner;`

vpInner is only using the value set on init so if something is wonky, the value never gets updated. I tested with using `innerWrapper.clientWidth` and it works just fine. I also noticed that vpInner never gets updated, even on resize, so this would fix any issues with that as well.

Line 1911: 
`var percentageX = TRANSFORM ? disX * items * 100 / (innerWrapper.clientWidth * slideCountNew) : disX * 100 / innerWrapper.clientWidth;`

Line 1949: 
`var indexMoved = - disX * items / innerWrapper.clientWidth;`

**Comment by ganlanyuan** [comment]
Thanks @justindmyers ,
I will check this probably tomorrow.

**Comment by ganlanyuan** [comment]
Hi, just checked.
It works as expected.
`vpInner` get updated on every window resize as well. https://github.com/ganlanyuan/tiny-slider/blob/4dfb401d679664eaceff1546a3ee2f11ceda2f3d/src/tiny-slider.js#L919

**Comment by justindmyers** [comment]
In the attached image, you can see that vpInner has a value of 8 while innerWrapper.clientWidth has a value of 550. I cannot seem to reproduce this outside of my development site, but the resize events are definitely not working in this case.

![Imgur](https://i.imgur.com/mVoOXvP.png)

I'll try to research a bit more tomorrow if I can.

**Comment by ganlanyuan** [comment]
Which version of tiny-slider are you using?

**Comment by justindmyers** [comment]
2.1.8

**Comment by ganlanyuan** [comment]
May I know the slider options?

**Comment by justindmyers** [comment]
I changed the `container` property a more generic element but otherwise these are the options I'm using:

Outer carousel:
```
{
  "items": 1,
  "slideBy": "page",
  "autoplay": false,
  "mouseDrag": false,
  "autoHeight": true,
  "autoplayDirection": "forward",
  "controls": true,
  "navContainer": "#carousel-variant",
  "speed": 400,
  "nested": "outer",
  "touch": false,
  "mode": "gallery",
  "container": ".outer"
}
```

Inner(nested) carousels:
```
{
  "items": 1,
  "slideBy": "page",
  "autoplay": false,
  "mouseDrag": true,
  "autoHeight": false,
  "autoplayDirection": "forward",
  "controls": true,
  "nested": "inner",
  "container": ".inner"
}
```

**Comment by justindmyers** [comment]
I've gone ahead and forked the slider to fix this issue on my side. I absolutely cannot recreate this anywhere else for some reason. Just let me know if you want to keep this open or have me go ahead and close it.

**Comment by ganlanyuan** [comment]
Keep it open for now.

Nested sliders are much more complicated. I will find more time to check this.
It'd be great if you can figure out the issue and send a PR.

**Comment by ganlanyuan** [comment]
Hey, 
I made a demo for this: https://codepen.io/ganlanyuan/pen/MOrMBO
Could you check if the same issue happen here?
