### ISSUE TITLE
ERROR: import via Webpack

### ISSUE THREAD

**Issue by nikitamarcius** [ganlanyuan/tiny-slider#78]
i have error: _Cannot use 'in' operator to search for 'insertRule' in undefined_

1. npm i -S tiny-slider
2. i use vue.js 2 (es6):

```
import { tns } from "tiny-slider/src/tiny-slider.module"

    export default {
        updated(){
            tns({
                container: '.my-slider',
                items: 3,
                slideBy: 'page',
                autoplay: true
            });
        }
    }
```

 "tiny-slider": "^2.1.8",
Google Chrom 60.0.3112.113
Windows 10

**Comment by ganlanyuan** [comment]
@nikitamarcius Sorry for the late reply.
I'm busy these days, but probably will check this within this week.

**Comment by nikitamarcius** [comment]
@ganlanyuan np

**Comment by mike3run** [comment]
I'm using webpack and importing it like shown works fine for me, so maybe its something else ??

**Comment by ganlanyuan** [comment]
Thanks @mike3run 
Hey @nikitamarcius , seems the error is related to https://github.com/ganlanyuan/tiny-slider/blob/315dd6464a766604fdf355a22821aa6a84c7ba53/src/helpers/addCSSRule.js#L4
Did you include the script in `<head>` ?

**Comment by nikitamarcius** [comment]
@ganlanyuan no. i my top message i showed how i use plugin (in single component).

**Comment by MeikG** [comment]
Same issue here, looks like it occurs when the WebPack files aren't at the bottom of the body. I get this error when my WebPack files are in either head or top of body. One fix could be to wrap the 'if in stylesheet' with:
`if (typeof document.styleSheets !== 'undefined') {
    ...
}`

Looks like it could be being executed before document.styleSheets is ready?

**Comment by ganlanyuan** [comment]
@nikitamarcius The issue should be fixed in [v2.2.1](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.2.1), could you check?

**Comment by MeikG** [comment]
I'll check first thing tomorrow and get back to you

**Comment by ganlanyuan** [comment]
Sure

**Comment by MeikG** [comment]
v2.2.1 has resolved the issue for me. Thanks guys, much appreciated!

**Comment by nikitamarcius** [comment]
@ganlanyuan tnx, its works!
