### ISSUE TITLE
navigation buttons around navigation dots

### ISSUE THREAD

**Issue by erralb** [ganlanyuan/tiny-slider#780]
Hi,

Is it possible to generate the tns-controls around the tns-nav ?
In the end I need to achieve something like this :
<img width="436" alt="Screenshot 2022-07-11 at 10 02 09" src="https://user-images.githubusercontent.com/790992/178217020-a70404db-c0f3-4727-a76f-78bd1c1a6f9d.png">

**Comment by Dredy** [comment]
On the demo page there is a "customize" section that does what You are expecting.

http://ganlanyuan.github.io/tiny-slider/demo/

**Comment by erralb** [comment]
@Dredy Sorry but which one ? I scrolled through the page again and did not find it.
The navigation buttons are always atop the dots.

**Comment by Dredy** [comment]
CUSTOMIZE
![image](https://user-images.githubusercontent.com/8537781/191304272-45f3a9e6-5537-47b3-9753-2fd39bbba158.png)

**Comment by erralb** [comment]
@Dredy faire enough I didn't see the arrows on the sides because of the clear colours ! 
That should work, thanks !
