### ISSUE TITLE
incompatible with Next.js "Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by kdong007** [ganlanyuan/tiny-slider#782]
__Issue description__:  
I used "tiny-slider-react" which it uses this package. This is what happens when loaded. I think there is something wrong with cjs/esm configs

<img width="735" alt="Screen Shot 2022-07-21 at 10 58 37 PM" src="https://user-images.githubusercontent.com/26269173/180373411-c669607c-25bf-42e2-b092-403a391344f0.png">

__Demo link/slider setting__:   

_Tiny-slider version_:   
2.9.4

_Browser name && version_:  
_OS name && version_:

**Comment by kdong007** [comment]
nvm. issues happens with 'tiny-slider-react' package

**Comment by levimykel** [comment]
@kdong007 How did you manage to fix this?

**Comment by kdong007** [comment]
@levimykel https://nextjs.org/docs/advanced-features/dynamic-import

**Comment by levimykel** [comment]
@kdong007 Thanks!
