### ISSUE TITLE
custom transition distance

### ISSUE THREAD

**Issue by faboulaws** [ganlanyuan/tiny-slider#8]
Hi,
First of all thanks for this plugin.

This plugin works great. however, when using **fixedWidth** option where  items have margins(left/right) some items are partially displayed(because of margin). When navigating the slider, the **fixedWidth** is used to calculate  transition distance (**translateX** variable). An option to control the transition  distance would be nice.

Thanks

**Comment by ganlanyuan** [comment]
Hi, 
Thanks for your feedback!
Would you mind to use `padding` instead of `margin`?

**Comment by ganlanyuan** [comment]
[0.4.0](https://github.com/ganlanyuan/tiny-slider/tree/v0.4.0) add a `gutter` option which can be used to set the margin.
Please let me know if this fix your issue.
Thanks

**Comment by faboulaws** [comment]
Thanks for the quick fix. The **gutter** option works well with **maxContainerWidth** and **loop = true**. I still had to change logic so that gutter is used as marginLeft instead  of marginRight of each slide item. This means that there might be a need for another option to specify where(left/right) the margin should be added for each item. 
Thanks

**Comment by ganlanyuan** [comment]
An option `gutterPosition` is now available to change this from [v0.4.1](https://github.com/ganlanyuan/tiny-slider/tree/v0.4.1). Could you check it?

**Comment by faboulaws** [comment]
Hi Again 

gutterPosition works great but there is and left margin added to the slider that in my case I dont need.

this code 
`  if (gutter !== 0 && gutterPosition === 'marginLeft') {
        ml = (loop)? itemsMax * slideWidth + gutter : gutter;
      }`

when replaced with

`  if (gutter !== 0 && gutterPosition === 'marginLeft') {
        ml = (loop)? itemsMax * slideWidth : gutter;
      }`

works for me

**Comment by ganlanyuan** [comment]
Is it because you already have `margin-left` in you css, so you don't need it?

**Comment by faboulaws** [comment]
Hi
I dont have a left margin. In my case I need the left margin of the first item to be visible.
Thanks

**Comment by ganlanyuan** [comment]
So you want only the first item shows left margin, other items don't show margin, is this the point?

**Comment by faboulaws** [comment]
I have a carousel where the items are not close to each other. So The need for the left margin. Also there is a space between the first item and the the beginning of the slider.

Please see a quick example of the layout below. It shows the first 2 items in the slider

<-----><------------><-----><------------>
margin       first         margin     second

Thanks

**Comment by ganlanyuan** [comment]
How about the last one? 
Is there some margin between the last item and the end of the slider?

**Comment by faboulaws** [comment]
No there is not.
Thanks

**Comment by ganlanyuan** [comment]
Hey, sorry I can't do like your case because usually the first and last slider items are vertical aligned with the slider.
But you can modify it to fit your need like what you mentioned before:
Replace  
```javascript
ml = (loop)? itemsMax * slideWidth + gutter : gutter;
``` 
with 
```javascript
ml = (loop)? itemsMax * slideWidth : gutter;
```

**Comment by faboulaws** [comment]
Ok. Thanks so much for your help
