### ISSUE TITLE
Feature request: Classes for current slide/dot

### ISSUE THREAD

**Issue by mike3run** [ganlanyuan/tiny-slider#80]
Right now Im using the aria labels to style those but maybe adding a quick class like `slide-active` or similar might help (?)

**Comment by ganlanyuan** [comment]
Will add this in next release.

**Comment by mike3run** [comment]
Thank you very much for the hard work! I found out about this library yesterday looking for vanilla slick alternatives.

**Comment by ganlanyuan** [comment]
`.tns-nav-active`, `.tns-slide-active` were added in [v2.2.0](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.2.0)

**Comment by lextoc** [comment]
With a `fixedWidth` and a wide container where a lot of slides are visible, each and every one of them gets the `.tns-slide-active` class while my `items` is set to `1`. I've centered the active slide and I wanted to give it special styling but instead all slides visible in viewport receive this special styling.

Slider configuration: 
```
    this.slider = tns({
      container: '.js-homepage-our-home__slider',
      items: 1,
      center: true,
      fixedWidth: 500,
      gutter: 50,
      prevButton: document.querySelector('.js-homepage-our-home__prev'),
      nextButton: document.querySelector('.js-homepage-our-home__next'),
      mouseDrag: true,
      rewind: true,
    });
```
What I'm getting (all slides active):
![What I'm getting](https://user-images.githubusercontent.com/4405004/50207135-e16f5800-036d-11e9-8232-7274aa2bebd1.png)

What I want:
![Desired effect](https://i.imgur.com/98939Nm.jpg)

**Comment by lextoc** [comment]
> Hey @lextoc ,
> `items` option has no effect in `fixedWidth` slider. `items` in `fixedWidth` slider is based on viewport.
> You could use `displayIndex`/`index` (refer to [here](https://github.com/ganlanyuan/tiny-slider#methods)) to target the center one.

That did the trick, thanks!

**Comment by Green-Zero-Development** [comment]
Here's an example of using displayIndex to add an active class to the slide in the center for anyone lurking months later (like I was):


~~~~
window.onload = function() { 
  var info = slider.getInfo(),
  indexCurrent = info.displayIndex;
  info.slideItems[indexCurrent - 1].classList.add('active');
}

document.querySelector('.next-button').onclick = function () {
  var info = slider.getInfo(),
  indexCurrent = info.displayIndex;
  info.slideItems[indexCurrent].classList.add('active');
  info.slideItems[indexCurrent - 1].classList.remove('active');
}

document.querySelector('.previous-button').onclick = function () {
  var info = slider.getInfo(),
  indexCurrent = info.displayIndex;
  info.slideItems[indexCurrent - 2].classList.add('active');
  info.slideItems[indexCurrent - 1].classList.remove('active');
}
~~~~

**Comment by pandalion** [comment]
So when I log 
`console.log(indexCurrent);` I get 1 which is correct at the start.

But following this if I log the item
 `console.log(info.slideItems[indexCurrent]);`

it logs the fourth slide?? can anyone help please?

**Comment by pratapraman** [comment]
What about when we drag the slider ?

**Comment by dubisoft-solutions** [comment]
the feature is not implemented yet. Dots works as expected, but all the visible slides have the **tns-slide-active** class, so still, no way to apply custom styling to the slide in the center

my options are:

`
{
        container: '.feedback-notes-slider',
        items: 3,
        slideBy: 1,
        autoplay: true,
        navAsThumbnails: true,
        center: true,
        controls: false,
        autoplayButtonOutput: false,
        navPosition: 'bottom',
    }
`

Probably this ticket should be re-opened. The feature can be very useful!

**Comment by WhiteMac** [comment]
I agree it would be useful to have a class for the true current slide, separate from a blanket class for all slides visible in the viewport. Here's how I solved it.

Add the following `onInit` option and custom event to your slider.

```js
let slider = tns({
	//your other options here
	onInit: function(info) {
		info.slideItems[info.index].classList.add('tns-slide-current');
	}
});

slider.events.on('indexChanged', (info, event) => {
	if (info.index != info.indexCached) {
		info.slideItems[info.indexCached].classList.remove('tns-slide-current');
		info.slideItems[info.index].classList.add('tns-slide-current');
	}
});
```

This solution should work robustly no matter how you navigate your slides (arrows, bullets, dragging, etc).

**Comment by WhiteMac** [comment]
I agree it would be useful to have a class for the true current slide, separate from a blanket class for all slides visible in the viewport. Here's how I solved it.

Add the following `onInit` option and custom event to your slider.

```js
let slider = tns({
	//your other options here
	onInit: (info) => {
		info.slideItems[info.index].classList.add('tns-slide-current');
	}
});

slider.events.on('indexChanged', (info, event) => {
	if (info.index != info.indexCached) {
		info.slideItems[info.indexCached].classList.remove('tns-slide-current');
		info.slideItems[info.index].classList.add('tns-slide-current');
	}
});
```

This solution should work robustly no matter how you navigate your slides (arrows, bullets, dragging, etc).
