### ISSUE TITLE
Suggestion: Remove go-native dependency on modules package

### ISSUE THREAD

**Issue by mike3run** [ganlanyuan/tiny-slider#81]
When using modules people are most likely using babel already or bringing their own polyfills to the table, the fact that go-native is around 25% the size of the library might be something to consider, here's my webpack bundle analyzed for reference:

![screen shot 2017-09-29 at 1 15 09 pm](https://user-images.githubusercontent.com/7088511/31039031-db97c288-a53f-11e7-9c4e-82d7f2a1e823.png)

**Comment by ganlanyuan** [comment]
Agree.
Will remove the go-native dependency in next main release.

**Comment by ganlanyuan** [comment]
Removed go-native dependency in [v2.2.1](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.2.1).
Will consider remove other polyfills in next main release.
