### ISSUE TITLE
Syntax error in new version

### ISSUE THREAD

**Issue by matheusgrieger** [ganlanyuan/tiny-slider#83]
https://github.com/ganlanyuan/tiny-slider/blob/63e2cf22ecf8afb443cbeb1015097b4a03252581/src/helpers/calc.js#L12

There is a small syntax error in the new version that is breaking everything: a semicolon at eol, which causes `div` to not be defined.

**Comment by ganlanyuan** [comment]
Oh, yes, thanks.
I will update this tomorrow.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by matheusgrieger** [comment]
Thank you!

**Comment by ganlanyuan** [comment]
Fixed in [v2.2.2](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.2.2).
