### ISSUE TITLE
Mouse Drag Bug

### ISSUE THREAD

**Issue by mike3run** [ganlanyuan/tiny-slider#84]
Go to demo page:
http://ganlanyuan.github.io/tiny-slider/tests/index.html

In slider `Mouse-drag`

Drag quickly the slides, eventually 2 dots or more become active

![screen shot 2017-10-04 at 7 06 39 pm](https://user-images.githubusercontent.com/7088511/31205460-2b9105ce-a937-11e7-8d62-b2e8d79195ea.png)

I think this happens when you have infinite mode on which is the default combined with mouseDrag on

**Comment by ganlanyuan** [comment]
Thanks @mike3run 
It's  fixed in v2.2.3.
The demo may take some time to update.

**Comment by mike3run** [comment]
Thank you very much for responding so quickly, I'd like to help more but Im still learning the ins and outs of your code, i'll wait for the CI integration to dive right in to help 😄
