### ISSUE TITLE
JS error after destroy()

### ISSUE THREAD

**Issue by rolandtoth** [ganlanyuan/tiny-slider#86]
After destroying the slider I get this error:

`Uncaught TypeError: Cannot read property 'style' of null`

Corresponding line is 1867:

`target.style[TRANSITIONDURATION] = duration;`

Slider init:

```javascript
mainSlider = tns({
    container: document.querySelector(selector),
    gutter: 0,
    edgePadding: 0,
    items: 1,
    slideBy: 'page',
    controls: true,
    nav: false,
    loop: true,
    controlsText: ['◀', '▶'],
    speed: 600,
    autoplay: true,
    autoplayTimeout: 10000,
    arrowKeys: true,
    mouseDrag: true,
    lazyload: false
});
```

_Tiny-slider version_:   2.2.3
_Browser name && version_:  Chrome 59
_OS name && version_:   Win10

**Comment by ganlanyuan** [comment]
Thanks, @rolandtoth 
This issue should be fixed in [v2.2.4](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.2.4)

**Comment by rolandtoth** [comment]
Thanks! Will try soon and report back.

**Comment by rolandtoth** [comment]
The error is gone, thanks!

**Comment by cmoeser** [comment]
Also receiving JS error after destroying. 
Error: Uncaught TypeError: Cannot read property 'clientWidth' of null
line 1288
version 2.2.4
Chrome Version 63.0.3239.108
Windows 8

**Comment by ganlanyuan** [comment]
Hey @cmoeser 
Could you make a demo or post your settings?

**Comment by kylegoines** [comment]
i also receive the issue @cmoeser is experiencing)
`Uncaught TypeError: Cannot read property 'clientWidth' of null line: 927`
After I `.destroy()` i try to `.rebuild()` and get that error

**Comment by kylegoines** [comment]
thank you ffor such a prompt response!

my config for the slider is as follows

this.slideshow  = tns( {
            container: this.sliderElem, // this is a static elemnt
            items: 1,
            slideBy: 'page',
            mode: 'gallery',
        } );

let me know if theres anything else i can provide you.

**Comment by kylegoines** [comment]
@ganlanyuan i seem to have stumbled on the issue at hand. I call the container with the explicit element object rather than `.className` which is tripping up somewhere in the codebase

**Comment by WellingtonGAlves** [comment]
I solved it as follows

1 - I check if the Datatable has been initialized, if yes
1.1 - Via ajax I paste a new HTML below the HTML that is the DataTable
2 - I delete the HTML where the DataTable is
3 - initialize the DataTable in the HTML I pasted via Ajax

`if (destroy_datatable) {
          $ .ajax ({
            headers: {
                'X-CSRF-TOKEN': $ ('meta [name = "csrf-token"]'). Attr ('content')
            },
            type: "GET",
            dataType: "html",
            url: "/ html / table-sales /" + parameter,
            success: function (data) {
              // alert (data);
              $ ('# control'). append (data);
              $ ('#' + auxiliary_parameter) .remove ();
              auxiliary_parameter = parameter;
              setTimeout (initialize_dataTable, 1000, route);
            },
            error: function (data) {
              alert ('Error');
              alert (data);
            },
          });
          destroy_datatable = false;
        } else {
          setTimeout (initialize_dataTable, 1000, route);
        }`
