### ISSUE TITLE
Responsive not working with fixed width container

### ISSUE THREAD

**Issue by justindmyers** [ganlanyuan/tiny-slider#87]
__Issue description__:  I'm using a wrapper element on my carousel that's narrower than the screen size and I noticed that while the breakpoint is being hit on the width of the container, it isn't applying all updates.

This image shows that the screen width is at 1043px and the breakpoint is at 960px. While the gutter and itemWidth have been applied, the carousel hasn't updated the positioning of the items.
![capture](https://user-images.githubusercontent.com/58646/31526973-247d7e2c-af7f-11e7-84fc-76439cf6995e.jpg)

As soon as the outer container hits 960px, the carousel updates and the first item is now flush left with it's container:
![capture-2](https://user-images.githubusercontent.com/58646/31526975-27580856-af7f-11e7-95d3-8ea198bec0c4.jpg)

It looks as if the breakpoint properties are applying on the screen width but the carousel positioning isn't updated until the container width hits the breakpoint.

For a centered, set-width carousel this causes some major problems.

**Comment by ganlanyuan** [comment]
Hi, I created a [demo page](https://ganlanyuan.github.io/slider-test/) based on the options shown on the screenshot.
Could you check if the same issue happens here?

**Comment by justindmyers** [comment]
Yes, I was able to recreate it. If you check the attached image, I added a container width smaller than the page width and you can see that at 961px, it's not behaving properly.

You can also just set .slider-container to a different max-width (like 940px) and it will have the same effect.

![capture](https://user-images.githubusercontent.com/58646/32581091-4cca8144-c49d-11e7-9a74-6b19334b1d63.PNG)

**Comment by ganlanyuan** [comment]
Should be fixed in [v2.3.3](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.3.3)

**Comment by ganlanyuan** [comment]
Same issue with #100
