### ISSUE TITLE
Any way to set a fixed height ?

### ISSUE THREAD

**Issue by VincentCharpentier** [ganlanyuan/tiny-slider#89]
__Issue description__:  I'm trying to make a slider in a fixed dimension container

__Demo link/slider setting__:   none

_Tiny-slider version_:   any
_Browser name && version_:  any
_OS name && version_:   any

I'm struggling to have a slider in a fixed dimension container.

For eg. consider that I have a 600x400 zone for my slider (1 item displayed at a time)
I have images of various size (portrait and lanscanpe format) that may be bigger.

I wrap my images in div so I can put CSS rules to make image fit in div (same behavior as CSS rule background-size:contain); So I usually have blank space in those div.

However the slider won't work properly with this kind of setup.

Is this unintended behavior ?

If you need I can make a codepen to show you

**Comment by ganlanyuan** [comment]
Yes, can you please make a codepen demo?

-------- Original Message --------

**Comment by VincentCharpentier** [comment]
here it is: https://codepen.io/VincentCharpentier/pen/bomqao?editors=0010

In the javascript panel you can change a condition to turn on the slider. You should notice that : 
- container won't respect it's defined width anymore. 
- Items inside won't respect the "center image" behavior anymore.

If you think there is a way to workaround It would be very nice to suggest one 👍 

Thanks for your help

**Comment by VincentCharpentier** [comment]
I tried to wrap my slider element inside a container (with fixed width) but it get even worse: https://codepen.io/VincentCharpentier/pen/rGqyRg?editors=0110

**Comment by mike3run** [comment]
I think you just gotta css a bit better, try to add the rules to the slides not the container

https://codepen.io/mike3run/pen/wrYXeE?editors=1100

**Comment by VincentCharpentier** [comment]
Thanks for your help.
On Google Chrome (Version 61.0.3163.100) the container item go full width on your codepen.
I wish I could have fixed height and width for the whole slider (I can repeat size rules on item, it's not a problem)

**Comment by VincentCharpentier** [comment]
Just to be 100% clear, here are the requirements I'm trying to meet:
- Slider width and height are defined (in px or %) - Or I can put it in a sized container if needed
- Images must not overflow (resized to fit)
- when an image does not cover fully the slider, it is centered (vertically or horizontally or both)

this seems to be a common use-case I hope I can find a way to do this with tiny-slider

**Comment by VincentCharpentier** [comment]
Ok so I found a work-around with extra wrapping and css
https://codepen.io/VincentCharpentier/pen/rGqyRg?editors=0100

**Comment by mike3run** [comment]
Yeah that's not up to JS to achieve 😄

**Comment by VincentCharpentier** [comment]
In fact it is the plugin that is breaking my css flexboxes by setting
display:inline-block on every item, which is not related to js.

Plugin may need to automatically wrap items to avoid putting inline style
to them and break the layout.

I may try to do a PR soon to suggest a fix

**Comment by mike3run** [comment]
But you can have a more generic slide which will inherit what the JS does and inside of that place your real flex div

**Comment by ganlanyuan** [comment]
Thanks @mike3run 

The `container` will always be 100% of its parent's `innerWidth`, so if you want the slider width to be fixed, you can put it in a fixed size wrapper.
To set the a fixed height to the slider, you can set a `height` to each slide. Then use `flex` to make the images inside the slides centered.

**Comment by alivefromupstairs** [comment]
desired look:
![image](https://user-images.githubusercontent.com/46059092/66258652-b5f41780-e79f-11e9-9b14-d669bd797b49.png)

Setting a fixed height on each slide and `width: auto; object-fit: contain` would give edge to an edge gutter.

**Comment by scsskid** [comment]
there is another solution without nedding a fixed height:

```css
.tns-slider {
    display: flex;
}

```

thats it, if you styling dependend on box dimensions of slide like background or box-shadow etc, you need to work with an additional inner slide container

**Comment by brycekirk** [comment]
> there is another solution without nedding a fixed height:
> 
> ```css
> .tns-slider {
>     display: flex;
> }
> ```

You also need to add `height: 100%` to a wrapper div inside the slide div

**Comment by michael-oxborrow** [comment]
@VincentCharpentier I found that I didn't need to wrap my images in divs.
I set a max-height value and object-fit: contain to each image.
Hope this helps.
...and I agree the implementation needs looking at.
