### ISSUE TITLE
Is there a way to change the transition from slide to fade?

### ISSUE THREAD

**Issue by lonepalmus** [ganlanyuan/tiny-slider#9]
well, yeah, thats it :)

**Comment by ganlanyuan** [comment]
Hey,
Will consider add this function soon. Maybe not only fade, other transforms can be added too.
Please let me know if you have any idea about this.

**Comment by lonepalmus** [comment]
that sounds great! well besides the fade, i dont have any fancy ideas. Slide and fade seems to be default options for most sliders. Maybe it could be to give users the possibility to create custom transitions?

**Comment by ganlanyuan** [comment]
Agree.
Will let you know when the function is added.

**Comment by ganlanyuan** [comment]
Hey, 
The feature is added in [dev2](https://github.com/ganlanyuan/tiny-slider/tree/dev2). 
To change a slider from **carousel** to **fade** , just change the `mode` option from `carousel` to `gallery`:
```javascript
var slider = tns({
  mode: 'gallery',
  other: options
});
```
To use other animations (like [animate.css](https://daneden.github.io/animate.css/)), 3 options (classes) are available to define the animation. A delay can also be setup between each two slides if you have more than one slide in a page.
```javascript
var slider = tns({
  mode: 'gallery',
  animateIn: 'fadeInDown',
  animateOut: 'fadeOutDown',
  // animateNormal: 'tns-normal',
  animateDelay: 300,
  other: options
});
```
I'm doing a E2E testing right now. Would you be able to try it out at the same time?
Thanks

**Comment by ganlanyuan** [comment]
The feature is added to master branch.

**Comment by yellow1912** [comment]
I'm thinking if you should leave the animation to the users somehow. For example, there are many libraries out there such as Animate.css and GSAP tween that support advanced animation. It would be totally cool to allow end-users to use those libs if they want to.

**Comment by ganlanyuan** [comment]
@yellow1912 Yes, it does allow user-defined animations.
You can use any library or write the animation by yourself. Simply pass the classes to the options. An example can be found [here](https://github.com/ganlanyuan/tiny-slider/blob/master/examples.md#user-content-animation).
You can do js animation as well using [custom events](https://github.com/ganlanyuan/tiny-slider#custom-events).

**Comment by yellow1912** [comment]
Interesting. I expected the animateIn and animateOut to take "functions", but perhaps it can work the way you say as well.
