### ISSUE TITLE
Responsive items wrong

### ISSUE THREAD

**Issue by thiagogsr** [ganlanyuan/tiny-slider#91]
__Issue description__:  
When I'm using the tiny-slider in responsive mode it is working as well but the `getInfo()` method returns the `items` property wrong when my resolution is between 768px and 914px (returns 1 instead of 3), 1024px and 1218px (returns 3 instead of 5). When my resolution is between 914px and 1024px, it works as well, the same for 1218px+. I already tested without the gutter, but it is not the problem. I'm using the `items` value to fetch the `middle` item (1 or 2 or 3, for each resolution).

__Demo link/slider setting__:   
```javascript
const slider = tns({
      container: "#slider",
      controlsContainer: ".avatar-slide-controls",
      nav: false,
      gutter: 20,
      items: 1,
      responsive: {
        768: {
          items: 3
        },
        1024: {
          items: 5
        }
      }
    })
```
_Tiny-slider version_:  2.2.4
_Browser name && version_:  Chrome Version 61.0.3163.100 (Official Build) (64-bit)
_OS name && version_:  OSX 10.13

**Comment by thiagogsr** [comment]
Demo: https://codepen.io/thiagogsr/full/RLmgvK

![image](https://user-images.githubusercontent.com/1802025/31902379-0a099ca4-b7fb-11e7-90dd-0e2288d18aa1.png)

**Comment by ganlanyuan** [comment]
Hi, 
I don't know what's wrong with the codepen page, but when I copy all the code from there to create a new page, everything is fine.
https://github.com/ganlanyuan/slider-test2
https://ganlanyuan.github.io/slider-test2/

**Comment by thiagogsr** [comment]
Hi @ganlanyuan, this is really strange, the codepen issue is exactly the same of my application.

I opened the codepen and your page with the same resolution, the codepen has the bug and yours not. 

Well, I don't know what is happening, so I will close this issue for now.
