### ISSUE TITLE
Compliance issue

### ISSUE THREAD

**Issue by ghost** [ganlanyuan/tiny-slider#92]
First off like your slider a lot!

I do have one small issue with compliance you added though, according to the testing tool axe and W3C you are not allowed to put **aria-selected** on an element with type button.

If you use button you should use the label: **aria-pressed** instead.

Here is a link to the docs:

https://www.w3.org/TR/wai-aria-practices/examples/button/button.html

**Comment by ganlanyuan** [comment]
Thanks, will check today

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by mickske** [comment]
Sent you a PR to save you some time ;)

**Comment by ganlanyuan** [comment]
Thanks @mickske

**Comment by ganlanyuan** [comment]
According to [here](https://www.w3.org/TR/wai-aria-practices/#button), `aria-pressed` is for toggle button, which is not suitable for slider dots.
I will consider replace `<button>` with other elements.

**Comment by mickske** [comment]
Fair enough makes sense to me. Maybe just choose anchor elements instead of buttons. Which does support the aria-selected element.

Just afraid you will break people's implementation who will be relying on buttons through there css at the moment maybe?

**Comment by ganlanyuan** [comment]
Exactly!
