### ISSUE TITLE
Autoplay/Control carousel even when all elements are visible

### ISSUE THREAD

**Issue by rejas** [ganlanyuan/tiny-slider#93]
__Issue description__:  

Hi, when I have exactly 3 items in my carousel and set the items parameter also to 3 (see below in my config) no autplay,(and my custom control neither) is working although I would like to scroll through the elements (having a different one of the three in the middle of the carousel). Of course once I set the items parameter lower (like for my mobile view in the options) then the autoplay/controls work like one expects. 
So, is it somehow possible to navigate through three items or is it a bug or not a feature? Thanks for your work anyway, really appreciate it.

__Demo link/slider setting__:   

    var slider = tns({
        container: this.container,
        controlsContainer: this.options.controlsContainer,
        navContainer: this.options.navContainer,
        items: 1,
        autoplay: true,
        autoplayTimeout: 300,
        edgePadding: 10,
        gutter: this.padding,
        loop: true,
        responsive: {
            480: {
                items: 3
            }
        },
        autoplayButtonOutput: false
    });

_Tiny-slider version_:   2.2.5
_Browser name && version_:  chrome firefox etc
_OS name && version_:   windows10

**Comment by ganlanyuan** [comment]
Hey @rejas ,
This is expected.

When all slider items can be displayed in one page (as your case: items 3, total 3), the slider will be frozen, so there is no `autoplay` or `controls`.

**Comment by rejas** [comment]
So I guess I have to manually listen to the events and trigger next/prev actions? Or wont the slider react to those at all?

**Comment by ganlanyuan** [comment]
No, the slider will not response.
BTY, I want to know why you still want this if all items are present and the `autoplay` (or `prev/next`) will just repeat the current status.

**Comment by rejas** [comment]
The customer wants that all items get into the middle once when autoplaying (or navigating) through them, even when all are visible at the sides so to speak. Maybe I can talk them out of it but I am not sure. Would you be option to an option to enable this?

**Comment by ganlanyuan** [comment]
Hum, 
This is an edge case. Let me consider it a little more.
Is it hard to add one more slide?

**Comment by rejas** [comment]
I dont think adding a slide is an option for the customer (content-wise).

**Comment by ganlanyuan** [comment]
A new option `freezable` added in [v2.3.0](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.3.0).
Now you can set `freezable: false` to achieve it.

**Comment by rejas** [comment]
THIS! IS! AWESOME! Great news to start off a monday working week (after having a cold the rest of last week so excuse my silence) Works out of the box, fixes my problems. Thanks a lot for your quick work!!!
