### ISSUE TITLE
Edge Padding

### ISSUE THREAD

**Issue by mick-feller** [ganlanyuan/tiny-slider#97]
Is there a way to make the edge padding only on a side where there are more slides available.

i have for example the autoplay and loop set to false. and edgepadding to 30 now in initial state it's showing half a slide on the left hand side, while there shouldn't be any.

Don't know if this feature is available at the moment and if i'm doing something wrong?

**Comment by ganlanyuan** [comment]
`edgePadding` works a little bit different with what you expected.
When it's set to `true`, there are always half of slides on the left and right even in initial status.

**Comment by viktorlarsson** [comment]
We had a similar issue, but we actually did something like this:

`{
	480: {
		items: 1.2
	},
	768: {
		items: 2.2
	},
	992: {
		items: 2.2
	},
	1200: {
		items: 3.2
	},
}`

This produces a negative margin on the right item but not on the last item in the slider.

**Comment by ganlanyuan** [comment]
@viktorlarsson 
Your idea is interesting. I didn't expect it can be used this way, but it seems a good solution.

**Comment by viktorlarsson** [comment]
We we're actually joking like "it would be nice to do this" and put the number in and accidently pressed save and live reload kicked in and then it worked :D

**Comment by ganlanyuan** [comment]
It would make sense that the `edgePadding` only on right side if `loop` set to `false` refer to [OwlCarousel2 stagepadding](https://owlcarousel2.github.io/OwlCarousel2/demos/stagepadding.html).
I will work on this when I have more time recently.

**Comment by ganlanyuan** [comment]
Removed left `edgePadding` when `loop: false` from v2.3.8
