### ISSUE TITLE
Cannot import tiny slider's module in react

### ISSUE THREAD

**Issue by harrymamba** [ganlanyuan/tiny-slider#98]
__Issue description__:  I'm trying to use the slider in a react app. Importing it with `import { tns } from 'tiny-slider/src/tiny-slider.module'` as stated on the docs and with this PR #39 and #41. Im getting an `Unexpected token import` error. I also tried lowering the version to 1.5.2 which is the NPM package after #41 was merged but still getting the same thing.

How can I make this work? Thanks!

_Tiny-slider version_:   2.2.5 / 1.5.2
_Browser name && version_:  Chrome v61.0.3
_OS name && version_:  Sierra 10.12.6

**Comment by ganlanyuan** [comment]
Hey @harrymamba 
Sorry I couldn't help with this since I'm not familiar with react. 
Hope someone else can help.

**Comment by harrymamba** [comment]
Got it to work. Updated my webpack to v2. :)

**Comment by tushariscoolster** [comment]
Got it working by making own component in react
`import React, { Component } from 'react'
import PropTypes from 'prop-types'
import 'tiny-slider/dist/tiny-slider.css'
const getTns = () => import('tiny-slider/src/tiny-slider')

class Slider extends Component {
  constructor (props) {
    super(props)
    this.sliderRef = React.createRef()
  }
  componentDidMount () {
    const defaultSetting = {
      container: this.sliderRef.current
    }
    const { setting } = this.props
    const finalSetting = { ...defaultSetting, ...setting }
    console.log(finalSetting)
    getTns().then(({ tns }) => {
      tns(finalSetting)
    })
  }

  render () {
    const { children } = this.props
    return (
      <div ref={this.sliderRef}>
        {children}
      </div>
    )
  }
}

Slider.propTypes = {
  children: PropTypes.node.isRequired,
  setting: PropTypes.object.isRequired
}

export default Slider
`

**Comment by marcvangend** [comment]
In case anyone is interested, let me share my method of implementing Tiny Slider in React, using functional components and hooks.

**Component: TinySlider.js**

```
import React, { useState, useEffect } from 'react';
import { tns } from 'tiny-slider/src/tiny-slider';
import 'tiny-slider/dist/tiny-slider.css';

const TinySlider = ({ children, listRef }) => {
  const [slider, setSlider] = useState(null);

  useEffect(() => {
    if (!slider) {
      setSlider(
        tns({
          // options...
        })
      );
    }
  }, [slider, listRef]);

  return <div>{children}</div>;
};

export default TinySlider;
```

**Usage in another component:**
```
import React, { useRef } from 'react';
import TinySlider from './TinySlider';

const MyComponent = () => {
  const listRef = useRef(null);

  return (
    <div>
      <h1>This is my slider</h1>
      <TinySlider listRef={listRef}>
        <ul ref={listRef}>
          <li><img src="" alt="" /></li>
          <li><img src="" alt="" /></li>
          <li><img src="" alt="" /></li>
        </ul>
      </TinySlider>
    </div>
  );
};

export default MyComponent;
```

For the record, I did not test this with dynamically changing items. In that case, you might need to refresh or rebuild the slider somewhere.
