### ISSUE TITLE
How can I pause autoplayed slider without destroying it programatically?

### ISSUE THREAD

**Issue by wendon** [ganlanyuan/tiny-slider#99]
I created a tiny slider with autoplay option true.
But I need to pause this slider on a button click?
How can I archive this? I can't find any appropriate method in documentation.

**Comment by ganlanyuan** [comment]
Add an `autoplayButton: ".your-button-class"` option. Please refer to [options](https://github.com/ganlanyuan/tiny-slider#options).

```javascript
var slider = tns({
    container: '.my-slider',
    items: 3,
    slideBy: 'page',
    autoplay: true,
    autoplayButton: '.your-button-class'
});
```

**Comment by ganlanyuan** [comment]
Close for now. 
Feel free to reopen it for further questions.
